DFXswiss/api

src/subdomains/generic/kyc/services/kyc.service.ts

[NOTASK] fix autoIdent errors

---

src/subdomains/generic/kyc/services/kyc.service.ts

[NOTASK] fix autoIdent error 2

---

src/shared/utils/util.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.entity.ts

[NOTASK] fix autoIdent errors 3

---

src/subdomains/generic/gs/dto/support-data.dto.ts
src/subdomains/generic/gs/gs.service.ts
src/subdomains/supporting/notification/services/notification.service.ts

[DEV-2596] notification in SupportTool

---

src/subdomains/generic/gs/dto/support-data.dto.ts
src/subdomains/generic/gs/gs.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/generic/user/services/webhook/webhook-notification.service.ts
src/subdomains/generic/user/services/webhook/webhook.service.ts
src/subdomains/supporting/notification/services/notification.service.ts

[NOTASK]&[DEV-2594] Improvements, bankData in SupportTool

---

infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
src/integration/blockchain/frankencoin/dto/frankencoin.dto.ts
src/integration/blockchain/frankencoin/frankencoin-client.ts
src/integration/blockchain/frankencoin/frankencoin.service.ts

[DEV-2595] adapt the frankencoin log

---

infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
src/integration/blockchain/frankencoin/dto/frankencoin.dto.ts
src/integration/blockchain/frankencoin/frankencoin-client.ts
src/integration/blockchain/frankencoin/frankencoin.service.ts
src/integration/sift/dto/sift.dto.ts
src/integration/sift/services/sift.service.ts
src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto.service.spec.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/history/mappers/transaction-dto.mapper.ts
src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
src/subdomains/generic/user/models/auth/auth.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/supporting/payment/entities/transaction.entity.ts
src/subdomains/supporting/payment/services/transaction-notification.service.ts
src/subdomains/supporting/payment/services/transaction-request.service.ts

[DEV-2518]&[NOTASK] transaction sift event, improve bankDataVerification

---

migration/1716910408337-TransactionRequestUserNotNull.js
src/subdomains/supporting/payment/entities/transaction-request.entity.ts

[DEV-2582] User non nullable

---

migration/1717159823109-addCountryBankTransactionVerificationEnable.js
src/shared/models/country/country.entity.ts

[DEV-2618] add country bankTransactionVerificationEnable

---

src/shared/models/country/country.entity.ts
src/subdomains/core/aml/aml.module.ts
src/subdomains/core/aml/aml.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-2617] auto bank transaction verification

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-registration.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/generic/gs/gs.service.ts

[NOTASK] fix buyCrypto webhook

---

src/subdomains/core/aml/aml.service.ts

[FIX] fix amlCheck

---

migration/1717506324942-MultichainDeposits.js
src/integration/alchemy/alchemy-network-mapper.ts
src/shared/models/asset/asset.service.ts
src/shared/utils/util.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-registration.service.ts
src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
src/subdomains/core/buy-crypto/routes/swap/__mocks__/crypto-route.entity.mock.ts
src/subdomains/core/buy-crypto/routes/swap/swap.controller.ts
src/subdomains/core/buy-crypto/routes/swap/swap.service.ts
src/subdomains/core/monitoring/observers/payment.observer.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-registration.service.ts
src/subdomains/core/sell-crypto/route/sell.controller.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/core/staking/services/staking.service.ts
src/subdomains/generic/user/models/auth/auth.service.ts
src/subdomains/generic/user/models/user/user.controller.ts
src/subdomains/supporting/address-pool/deposit/__mocks__/deposit.entity.mock.ts
src/subdomains/supporting/address-pool/deposit/deposit.entity.ts
src/subdomains/supporting/address-pool/deposit/deposit.service.ts
src/subdomains/supporting/address-pool/deposit/dto/deposit-dto.mapper.ts
src/subdomains/supporting/address-pool/deposit/dto/deposit.dto.ts
src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
src/subdomains/supporting/payment/services/transaction-request.service.ts

[NOTASK] add missing relation

---

src/subdomains/generic/gs/gs.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts

[DEV-2639] supportTool bankData search

---

src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/supporting/notification/factories/mail.factory.ts

[DEV-2640] High risk mail refactoring

---

src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/aml/enums/aml-reason.enum.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[DEV-2644] New amlReason chargebackNotPossible

---

infrastructure/bicep/dfx-api.bicep
infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
src/config/config.ts
src/integration/blockchain/frankencoin/controllers/frankencoin.controller.ts
src/integration/blockchain/frankencoin/dto/frankencoin.dto.ts
src/integration/blockchain/frankencoin/frankencoin-client.ts
src/integration/blockchain/frankencoin/frankencoin.module.ts
src/integration/blockchain/frankencoin/frankencoin.service.ts
src/subdomains/supporting/log/log.service.ts

[DEV-2609] Frankencoin supply and tvl monitoring

---

src/subdomains/supporting/pricing/domain/entities/price.ts

[FIX] fix price error

---

README.md
src/integration/blockchain/frankencoin/dto/frankencoin.dto.ts
src/integration/blockchain/frankencoin/frankencoin.service.ts
src/integration/exchange/services/exchange.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/supporting/pricing/domain/entities/price-rule.entity.ts
src/subdomains/supporting/pricing/domain/entities/price.ts
src/subdomains/supporting/pricing/domain/interfaces/index.ts
src/subdomains/supporting/pricing/services/integration/coin-gecko.service.ts
src/subdomains/supporting/pricing/services/integration/currency.service.ts
src/subdomains/supporting/pricing/services/integration/fixer.service.ts
src/subdomains/supporting/pricing/services/integration/pricing-dex.service.ts
src/subdomains/supporting/pricing/services/integration/pricing-ebel2x.service.ts
src/subdomains/supporting/pricing/services/integration/pricing-frankencoin.service.ts
src/subdomains/supporting/pricing/services/integration/pricing-provider.ts
src/subdomains/supporting/pricing/services/pricing.service.ts

[DEV-2266] Price path improvements

---

src/subdomains/supporting/pricing/domain/entities/price.ts

[FIX] fix priceSteps

---

src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/generic/kyc/services/kyc-notification.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/supporting/notification/enums/index.ts
src/subdomains/supporting/notification/factories/mail.factory.ts

[DEV-2653] ident mail

---

infrastructure/bicep/dfx-api.bicep
infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
src/integration/blockchain/frankencoin/frankencoin.service.ts
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/trading/dto/update-trading-rule.dto.ts
src/subdomains/generic/kyc/services/kyc-notification.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/supporting/notification/enums/index.ts
src/subdomains/supporting/notification/factories/mail.factory.ts

[DEV-2661]&[NOTASK]&[DEV-2653] amlRule update, env renaming, ident mails

---

src/subdomains/generic/gs/dto/support-data.dto.ts
src/subdomains/generic/gs/gs.module.ts
src/subdomains/generic/gs/gs.service.ts
src/subdomains/generic/kyc/services/limit-request.service.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts

[DEV-2659]&[DEV-2660] Add supportTool limitRequests, supportIssues

---

src/subdomains/core/sell-crypto/route/dto/confirm-sell.dto.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/generic/gs/dto/support-data.dto.ts
src/subdomains/generic/gs/gs.module.ts
src/subdomains/generic/gs/gs.service.ts
src/subdomains/generic/kyc/services/limit-request.service.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts

[DEV-2659]&[DEV-2660] Support tool improvements, permit fix

---

src/subdomains/core/aml/aml.service.ts

[FIX] fix amlCheck for checkoutTx

---

src/subdomains/core/aml/aml.service.ts
src/subdomains/supporting/payment/services/fee.service.ts

[NOTASK] Refactoring

---

migration/1718282641572-buyCryptoStatusDefault.js
src/shared/services/process.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto-fees.entity.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-job.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts

[DEV-2664] refresh buyCrypto fee

---

migration/1718282641572-buyCryptoStatusDefault.js
src/shared/services/process.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto-fees.entity.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-job.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts

* [DEV-2664] refresh buyCrypto fee
* [DEV-2664] Refactoring
* [DEV-2664] Refactoring 2
* [DEV-2664] add migration
* [DEV-2664] Add custom type check
* [DEV-2664] Refactoring 3
---------
- Login/logout
- KYC page
[DEV-2664]: https://dfxswiss.atlassian.net/browse/DEV-2664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2664]: https://dfxswiss.atlassian.net/browse/DEV-2664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2664]: https://dfxswiss.atlassian.net/browse/DEV-2664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

[DEV-2664] refresh buyCrypto fee (#1361)

---

src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts

DEV-2592 swissqrbill reference fix

---

src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts

* move reference data to additionalInformation
* move reference to message data
- Login/logout
- KYC page

DEV-2592 swissqrbill reference fix (#1372)

---

src/shared/i18n/de/invoice.json
src/shared/i18n/en/invoice.json
src/shared/i18n/fr/invoice.json
src/shared/utils/util.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
src/subdomains/core/buy-crypto/routes/buy/dto/invoice.dto.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/generic/kyc/kyc.module.ts
src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc-log.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/generic/user/models/user-data/user-data.controller.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/payment/services/swiss-qr.service.ts

[DEV-2592]&[FIX] Refactoring, fix auto create bankData

---

migration/1718370557278-WebhookDataIdentifier.js
src/shared/utils/util.ts
src/subdomains/generic/user/services/webhook/dto/create-webhook.dto.ts
src/subdomains/generic/user/services/webhook/webhook.entity.ts
src/subdomains/generic/user/services/webhook/webhook.service.ts

[NOTASK] webhook data hash

---

migration/1718311906077-addSiftResponse.js
migration/1718370557278-WebhookDataIdentifier.js
src/integration/sift/dto/sift.dto.ts
src/integration/sift/services/sift.service.ts
src/shared/utils/util.ts
src/subdomains/core/buy-crypto/buy-crypto.module.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/generic/user/models/account-merge/account-merge.service.ts
src/subdomains/generic/user/services/webhook/dto/create-webhook.dto.ts
src/subdomains/generic/user/services/webhook/webhook.entity.ts
src/subdomains/generic/user/services/webhook/webhook.service.ts
src/subdomains/supporting/fiat-payin/entities/checkout-tx.entity.ts
src/subdomains/supporting/fiat-payin/services/fiat-payin-sync.service.ts
src/subdomains/supporting/payment/entities/transaction-request.entity.ts
src/subdomains/supporting/payment/services/transaction-request.service.ts

[NOTASK]&[NOTASK] webhook data hash, mergeRequest only with mail

---

src/subdomains/supporting/payment/controllers/special-external-account.controller.ts
src/subdomains/supporting/payment/dto/input/create-special-external-account.dto.ts
src/subdomains/supporting/payment/payment.module.ts
src/subdomains/supporting/payment/services/special-external-account.service.ts

[DEV-2674] add SpecialAccountController

---

src/shared/services/process.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-registration.service.ts
src/subdomains/core/staking/services/staking.service.ts
src/subdomains/supporting/bank-tx/bank-tx-repeat/bank-tx-repeat.service.ts
src/subdomains/supporting/bank-tx/bank-tx/bank-tx.entity.ts
src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
src/subdomains/supporting/payin/services/payin.service.ts
src/subdomains/supporting/payment/services/transaction-job.service.ts
src/subdomains/supporting/payment/transaction.module.ts

[DEV-2611] synchronize transaction user

---

package-lock.json
package.json
src/integration/checkout/dto/checkout.dto.ts
src/integration/checkout/services/checkout.service.ts
src/integration/sift/services/sift.service.ts
src/shared/services/payment-info.service.ts
src/shared/services/process.service.ts
src/subdomains/core/buy-crypto/buy-crypto.module.ts
src/subdomains/core/buy-crypto/process/buy-crypto.controller.ts
src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto.service.spec.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-registration.service.ts
src/subdomains/core/staking/services/staking.service.ts
src/subdomains/generic/user/models/account-merge/account-merge.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/generic/user/services/webhook/webhook.service.ts
src/subdomains/supporting/bank-tx/bank-tx-repeat/bank-tx-repeat.service.ts
src/subdomains/supporting/bank-tx/bank-tx/bank-tx.entity.ts
src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
src/subdomains/supporting/fiat-payin/services/checkout-tx.service.ts
src/subdomains/supporting/fiat-payin/services/fiat-payin-sync.service.ts
src/subdomains/supporting/payin/services/payin.service.ts
src/subdomains/supporting/payment/controllers/special-external-account.controller.ts
src/subdomains/supporting/payment/dto/input/create-special-external-account.dto.ts
src/subdomains/supporting/payment/payment.module.ts
src/subdomains/supporting/payment/services/special-external-account.service.ts
src/subdomains/supporting/payment/services/transaction-job.service.ts
src/subdomains/supporting/payment/transaction.module.ts

[NOTASK]&[DEV-2673] MergeRequest Refactoring, CHF sell iban check fix

---

src/subdomains/supporting/payment/services/transaction-job.service.ts

[FIX] fix transaction sync

---

src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/supporting/bank-tx/bank-tx/bank-tx.entity.ts
src/subdomains/supporting/payment/dto/input/create-special-external-account.dto.ts

[DEV-2677] bankData name refactoring

---

migration/1718358825622-TransactionRequestCleanup.js
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts

[DEV-2647] Cleanup

---

migration/1718358825622-TransactionRequestCleanup.js
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts

[DEV-2647]&[DEV-2686] Cleanup, kycStep update fix

---

infrastructure/bicep/dfx-api.bicep
infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
package-lock.json
package.json
src/config/config.ts
src/integration/exchange/exchange.module.ts
src/integration/exchange/services/p2b.service.ts

[DEV-2666] integrate p2b exchange

---

infrastructure/bicep/dfx-api.bicep
infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
package-lock.json
package.json
src/config/config.ts
src/integration/exchange/exchange.module.ts
src/integration/exchange/services/p2b.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/core/staking/services/staking.service.ts
src/subdomains/supporting/payin/entities/crypto-input.entity.ts
src/subdomains/supporting/payin/services/payin.service.ts
src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
src/subdomains/supporting/payin/strategies/register/impl/base/register.strategy.ts
src/subdomains/supporting/payin/strategies/register/impl/bitcoin.strategy.ts
src/subdomains/supporting/payin/strategies/register/impl/lightning.strategy.ts
src/subdomains/supporting/payin/strategies/register/impl/monero.strategy.ts

[DEV-2666]&[DEV-2670] Integrate p2b, forward on pass

---

package-lock.json
package.json
src/integration/exchange/exchange.module.ts
src/integration/exchange/services/p2b.service.ts
src/subdomains/core/aml/aml-helper.service.ts
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto.service.spec.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
src/subdomains/core/buy-crypto/routes/buy/dto/buy-payment-info.dto.ts
src/subdomains/core/sell-crypto/process/__tests__/buy-fiat.service.spec.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/supporting/dex/dex.controller.ts
src/subdomains/supporting/dex/services/dex-bitcoin.service.ts
src/subdomains/supporting/dex/services/dex-monero.service.ts
src/subdomains/supporting/dex/services/dex.service.ts
src/subdomains/supporting/dex/strategies/supplementary/impl/base/evm.strategy.ts
src/subdomains/supporting/dex/strategies/supplementary/impl/base/supplementary.strategy.ts
src/subdomains/supporting/dex/strategies/supplementary/impl/bitcoin.strategy.ts
src/subdomains/supporting/dex/strategies/supplementary/impl/monero.strategy.ts

[DEV-2670] Fixed AML check

---

migration/1718702723340-LiquidityOrderIndex.js
src/subdomains/core/sell-crypto/process/services/buy-fiat-registration.service.ts
src/subdomains/core/staking/services/staking.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/dex/entities/liquidity-order.entity.ts

DB improvements

---

src/integration/checkout/services/checkout.service.ts

Update URL of card failure page

---

migration/1718803670219-AddPriceDefinitionAllowedDate.js
src/subdomains/core/buy-crypto/process/dto/update-buy-crypto.dto.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/dto/update-buy-fiat.dto.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts

[DEV-2678] exchangeRateApprovalDate

---

migration/1718874027084-AddAssetFinancialType.js
src/shared/models/asset/asset.controller.ts
src/shared/models/asset/asset.entity.ts
src/shared/models/asset/asset.service.ts
src/shared/models/asset/dto/update-asset.dto.ts

[DEV-2581] add financialType

---

src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.controller.spec.ts
src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
src/subdomains/core/buy-crypto/routes/buy/dto/buy-payment-info.dto.ts
src/subdomains/core/buy-crypto/routes/swap/dto/swap-payment-info.dto.ts
src/subdomains/core/buy-crypto/routes/swap/swap.controller.ts
src/subdomains/core/sell-crypto/route/dto/sell-payment-info.dto.ts
src/subdomains/core/sell-crypto/route/sell.controller.ts
src/subdomains/supporting/payment/dto/transaction-helper/transaction-details.dto.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-2701] Return timestamp in payment info

---

migration/1719236716020-AddAmlResponsible.js
src/subdomains/core/aml/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/dto/update-buy-crypto.dto.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/dto/update-buy-fiat.dto.ts

[DEV-2691] amlCheck responsible

---

migration/1719236716020-AddAmlResponsible.js
src/config/config.ts
src/integration/exchange/services/exchange-tx.service.ts
src/integration/sift/services/sift.service.ts
src/shared/models/language/language.service.ts
src/subdomains/core/aml/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/dto/update-buy-crypto.dto.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/dto/update-buy-fiat.dto.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/generic/user/models/auth/auth.controller.ts
src/subdomains/generic/user/models/auth/auth.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/generic/user/models/user/tests/user.service.spec.ts
src/subdomains/generic/user/models/user/user.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts
src/subdomains/supporting/payment/services/transaction-request.service.ts

[DEV-2691] & [DEV-2518] & Set language from IP & bankData verification improvement & activate refresh fee

---

src/integration/sift/dto/sift.dto.ts
src/integration/sift/services/sift.service.ts

* [DEV-2518] add creat account sift
* [DEV-2518] Add sift event api
* Fix unit test
* [DEV-2518] Add update account
* [DEV-2518] Add create_order and refactoring
* [DEV-2518] Refactoring
* [DEV-2518] Add create transaction
* [DEV-2518] Add transaction
* [DEV-2518] add transaction update
* [DEV-2518] Add create sift transaction
* [DEV-2518] Add bank decline to transaction
* [DEV-2518] Add authStatusReason and create transaction if checkout failed
* [DEV-2518] Fix problems
* [DEV-2518] Add migration
* [DEV-2518] Save sift response
* [DEV-2518] Add SiftPaymentMethodMap
* [DEV-2518] Refactoring
* [DEV-2518] Refactoring
* [DEV-2518] Refactoring 2
* [DEV-2518] change to siftResponse
* [DEV-2518] Add aml decline mapper
* [DEV-2518] Fix
* [DEV-2518] Add migration
* [DEV-2518] Adapt unit test
* …

[DEV-2518] Events integration sift fix transaction (#1405)

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts

[NO-TASK] Fixed crypto AML check

---

src/integration/blockchain/shared/evm/evm-client.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/supporting/payin/entities/crypto-input.entity.ts
src/subdomains/supporting/payin/services/payin.service.ts
src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
src/subdomains/supporting/payin/strategies/register/impl/base/register.strategy.ts
src/subdomains/supporting/payin/strategies/register/impl/bitcoin.strategy.ts

[DEV-2696] Permits to deposit

---

src/integration/sift/dto/sift.dto.ts
src/integration/sift/services/sift.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/payment/services/transaction-request.service.ts

[DEV-2713] add swap for paymentMethod

---

infrastructure/bicep/parameters/prd.json

update zchfGraphUrl to 3dotshub

---

src/subdomains/core/aml/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-notification.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/generic/kyc/services/limit-request.service.ts

[NO-TASK] Fixed relations, refactoring

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-notification.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts

[NO-TASK] More fixes

---

src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/supporting/payment/services/swiss-qr.service.ts

[DEV-2734] Use org. data for business account

---

src/shared/utils/util.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/supporting/payment/services/swiss-qr.service.ts

[DEV-2733] more specialChar detection + [DEV-2734] Use org. data for business account (#1417) 

---

src/config/config.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts

[NOTASK] Reduced network start amount, fix buyCrypto user activation

---

src/subdomains/generic/user/models/account-merge/account-merge.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-2712] merge check

---

src/shared/utils/async-cache.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-2737] paymentInfo network start fee

---

migration/1718892189636-SupportIssueInformation.js
src/subdomains/supporting/bank/bank.module.ts
src/subdomains/supporting/bank/bank/bank.controller.ts
src/subdomains/supporting/bank/bank/dto/bank.dto.ts
src/subdomains/supporting/bank/bank/dto/bank.mapper.ts
src/subdomains/supporting/support-issue/dto/create-support-issue.dto.ts
src/subdomains/supporting/support-issue/entities/support-issue.entity.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts
src/subdomains/supporting/support-issue/support-issue.controller.ts

[DEV-2614] Support improvements

---

src/subdomains/generic/user/models/bank-data/bank-data.service.ts

[DEV-2735] set verifiedName auto

---

migration/1718892189636-SupportIssueInformation.js
src/shared/utils/async-cache.ts
src/subdomains/generic/user/models/account-merge/account-merge.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/bank/bank.module.ts
src/subdomains/supporting/bank/bank/bank.controller.ts
src/subdomains/supporting/bank/bank/dto/bank.dto.ts
src/subdomains/supporting/bank/bank/dto/bank.mapper.ts
src/subdomains/supporting/notification/services/notification-job.service.ts
src/subdomains/supporting/notification/services/notification.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts
src/subdomains/supporting/support-issue/dto/create-support-issue.dto.ts
src/subdomains/supporting/support-issue/entities/support-issue.entity.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts
src/subdomains/supporting/support-issue/support-issue.controller.ts

[DEV-2712]&[DEV-2737] merge check, paymentInfo network start fee

---

src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[NOTASK] set bankTransactionVerification with identificationType

---

src/subdomains/core/aml/aml-helper.service.ts
src/subdomains/generic/user/models/wallet/wallet.entity.ts

[DEV-2762] add amlRule AE iban block

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-registration.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-registration.service.ts
src/subdomains/generic/kyc/services/name-check.service.ts
src/subdomains/generic/kyc/services/tfa.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/generic/user/services/webhook/webhook.service.ts

[DEV-2774] replace exist with exists method

---

src/subdomains/generic/kyc/services/integration/ident.service.ts

[DEV-2754] videoIdent limit

---

src/subdomains/core/aml/aml.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-2770] Auto set verifiedCountry

---

src/integration/sift/services/sift.service.ts

[NO-TASK] Add IP to sift transaction

---

src/app.controller.ts

[NO-TASK] Add services to redirect ref

---

src/subdomains/generic/kyc/services/name-check.service.ts

[DEV-2772] nameCheck not relevant sanctioned

---

migration/1719957070772-AddBuyCryptoChargebackIban.js
src/subdomains/core/buy-crypto/process/dto/update-buy-crypto.dto.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts

[DEV-2773] buyCrypto chargebackIban

---

src/subdomains/generic/kyc/entities/name-check-log.entity.ts
src/subdomains/generic/kyc/services/name-check.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts

[DEV-2771] nameCheck improvement

---

src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-2777] update userData with kycStep update

---

migration/1720456949278-AddChargebackAllowedDate.js
src/subdomains/core/buy-crypto/process/dto/update-buy-crypto.dto.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/dto/update-buy-fiat.dto.ts

[DEV-2758] add chargebackAllowedDate

---

src/subdomains/core/history/mappers/transaction-dto.mapper.ts

[DEV-2783] NetworkStartFee mapper refactoring

---

src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/repositories/buy-crypto.repository.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts

[DEV-2782] buyCrypto remove save in feeRefresh

---

src/integration/sift/dto/sift.dto.ts
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/aml/aml-helper.service.ts
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/enums/aml-reason.enum.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[DEV-2763] amlCheck monero input

---

src/integration/sift/dto/sift.dto.ts
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/aml/aml-helper.service.ts
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/enums/aml-reason.enum.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[DEV-2789] card name mismatch

---

src/integration/infrastructure/azure-storage.service.ts
src/subdomains/generic/kyc/services/integration/document-storage.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-2755] improve merge

---

src/integration/infrastructure/azure-storage.service.ts
src/subdomains/core/aml/aml-helper.service.ts
src/subdomains/core/aml/aml.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/history/dto/history-query.dto.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/core/trading/services/trading-order.service.ts
src/subdomains/generic/kyc/services/integration/document-storage.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/support-issue/dto/create-support-issue.dto.ts

[NOTASK]&[DEV-2755] Improve auto merge, improve merge

---

src/subdomains/core/trading/services/trading-order.service.ts

[NO-TASK] Zero trading slippage tolerance

---

src/integration/blockchain/shared/evm/evm-client.ts

[NO-TASK] Slippage tolerance precision

---

src/subdomains/generic/user/models/user-data/user-data.service.ts

[FIX] fix merge

---

migration/1720608014547-AddBuyCryptoChargebackOutput.js
src/subdomains/core/buy-crypto/buy-crypto.module.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto.service.spec.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/fiat-output/dto/create-fiat-output.dto.ts
src/subdomains/supporting/fiat-output/fiat-output.entity.ts
src/subdomains/supporting/fiat-output/fiat-output.module.ts
src/subdomains/supporting/fiat-output/fiat-output.service.ts

[DEV-2796] Auto create buyCrypto fiatOutput

---

src/integration/blockchain/shared/util/blockchain.util.ts

[DEV-2732] base explorer url fallback

---

migration/1720712636550-TradingExpectedAmount.js
src/subdomains/core/trading/entities/trading-order.entity.ts

[NO-TASK] Fixed build

---

src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/supporting/fiat-payin/services/fiat-payin-sync.service.ts
src/subdomains/supporting/notification/factories/mail.factory.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-2794] sift updates & fixes

---

migration/1720789084318-AssetDecimals.js
src/integration/blockchain/blockchain.module.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/integration/blockchain/shared/evm/evm-decimals.service.ts
src/shared/models/asset/asset.entity.ts
src/shared/repositories/repository.factory.ts
src/shared/services/process.service.ts

[NO-TASK] Added asset decimals

---

src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/supporting/fiat-output/fiat-output.service.ts

[DEV-2823] avoid fiatOutput duplications

---

src/shared/models/asset/asset.controller.ts
src/shared/models/asset/asset.service.ts
src/shared/services/process.service.ts
src/subdomains/core/liquidity-management/liquidity-management.module.ts
src/subdomains/core/liquidity-management/services/liquidity-management-balance.service.ts
src/subdomains/core/trading/dto/trading.dto.ts
src/subdomains/core/trading/entities/trading-order.entity.ts
src/subdomains/core/trading/enums/index.ts
src/subdomains/core/trading/services/trading-rule.service.ts
src/subdomains/core/trading/services/trading.service.ts
src/subdomains/core/trading/trading.module.ts
src/subdomains/subdomains.module.ts
src/subdomains/supporting/log/log-job.module.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts
src/subdomains/supporting/pricing/services/asset-prices.service.ts

[DEV-2803] log trading data

---

src/subdomains/core/trading/services/trading-rule.service.ts
src/subdomains/core/trading/services/trading.service.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-2831][DEV-2832] Trading log improvements

---

src/integration/alchemy/alchemy-network-mapper.ts
src/integration/alchemy/services/alchemy.service.ts
src/integration/blockchain/arbitrum/arbitrum-client.ts
src/integration/blockchain/base/base-client.ts
src/integration/blockchain/bsc/bsc-client.ts
src/integration/blockchain/optimism/optimism-client.ts
src/integration/blockchain/polygon/polygon-client.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/integration/blockchain/shared/evm/evm.service.ts
src/integration/blockchain/shared/evm/evm.util.ts
src/integration/blockchain/shared/services/crypto.service.ts

[NO-TASK] Using decimals field

---

migration/1720894069676-addIEntitySetting.js
migration/1720894487055-addIEntitySetting.js
src/shared/models/setting/setting.entity.ts

[NO-TASK] Add iEntity to Setting table

---

src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-2834] Kyc ident improvement

---

src/shared/models/setting/setting.service.ts

[FIX] fix setting bug

---

src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-2843] fix ident userData update bug

---

migration/1721145312353-AddBuyCryptoBuyFiatBankData.js
src/subdomains/core/aml/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/dto/update-buy-crypto.dto.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/dto/update-buy-fiat.dto.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/generic/user/models/bank-data/dto/update-bank-data.dto.ts

[DEV-2821] buyCrypto/buyFiat bankData

---

src/subdomains/core/aml/aml.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-2868] Auto set kycFileId

---

migration/1721646752233-AddDeactivationDate.js
src/subdomains/core/aml/aml.service.ts
src/subdomains/generic/user/models/auth/auth.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user/dto/user-dto.mapper.ts
src/subdomains/generic/user/models/user/user.entity.ts
src/subdomains/generic/user/models/user/user.repository.ts
src/subdomains/generic/user/models/user/user.service.ts

[DEV-2801] deactivationDate + userDataReactivation

---

src/subdomains/supporting/payment/entities/fee.entity.ts
src/subdomains/supporting/payment/services/fee.service.ts

[DEV-2844] relative discount fee

---

src/subdomains/generic/kyc/services/kyc.service.ts

[FIX] fix kyc identDocumentId bug

---

src/shared/models/setting/dto/info-banner.dto.ts
src/shared/models/setting/setting.controller.ts

[DEV-2752] info-banner endpoint

---

src/shared/models/setting/dto/info-banner.dto.ts
src/shared/models/setting/setting.controller.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[NOTASK] change kyc auto ident business identDocId

---

src/subdomains/core/payment-link/services/payment-activation.service.ts

[DEV-2785] activation webhook improvement

---

src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-job.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts

[DEV-2799] buyFiat refreshFee update

---

src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts

[DEV-2877] Auto refund checkoutTx

---

src/subdomains/generic/forwarding/services/lnurl-forward.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[NOTASK]&[FIX] fix getting amount, fix ident review

---

src/config/config.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts

[NO-TASK] Switched to MSATs

---

src/subdomains/core/payment-link/entities/payment-link-payment.entity.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts

[NO-TASK] Refactoring, fixed sat conversion

---

src/integration/blockchain/shared/util/blockchain.util.ts
src/subdomains/generic/user/models/user/dto/user-dto.mapper.ts
src/subdomains/generic/user/models/user/dto/user-v2.dto.ts

[DEV-2791] add explorerUrl to UserAddressDto

---

src/subdomains/core/aml/aml.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts

[DEV-2899] Improve verifiedName and merge

---

src/integration/blockchain/shared/util/blockchain.util.ts
src/shared/models/setting/dto/info-banner.dto.ts
src/shared/models/setting/setting.controller.ts
src/shared/utils/util.ts
src/subdomains/core/aml/aml.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
src/subdomains/core/buy-crypto/routes/buy/dto/create-buy.dto.ts
src/subdomains/core/buy-crypto/routes/buy/dto/get-buy-payment-info.dto.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/sell-crypto/route/dto/create-sell.dto.ts
src/subdomains/core/sell-crypto/route/dto/get-sell-payment-info.dto.ts
src/subdomains/core/trading/services/trading.service.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts
src/subdomains/generic/kyc/dto/input/kyc-data.dto.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/generic/user/models/bank-data/dto/create-bank-data.dto.ts
src/subdomains/generic/user/models/user/dto/update-address.dto.ts
src/subdomains/generic/user/models/user/dto/user-dto.mapper.ts
src/subdomains/generic/user/models/user/dto/user-v2.dto.ts
src/subdomains/supporting/bank/bank-account/dto/create-bank-account.dto.ts
src/subdomains/supporting/bank/bank-account/dto/iban.dto.ts

[DEV-2899]&[NOTASK]&[DEV-2791] explorerUrl to userAddressDto, trim input kycData, improve verifiedName/merge

---

src/subdomains/core/payment-link/dto/payment-request.mapper.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts

[DEV-2895] return payment request if exists

---

src/subdomains/core/payment-link/dto/payment-request.mapper.ts
src/subdomains/core/payment-link/entities/payment-link-payment.entity.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts

[DEV-2895] Payment improvements

---

src/shared/utils/util.ts

[NOTASK] new special char

---

src/subdomains/core/aml/aml-helper.service.ts
src/subdomains/generic/user/models/wallet/wallet.entity.ts

[DEV-2905] skip susMail check

---

src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
src/subdomains/supporting/payment/entities/transaction.entity.ts

[DEV-2888] transaction type buyFiatOutput

---

src/subdomains/generic/kyc/services/name-check.service.ts

[DEV-2908] Business nameCheck

---

src/subdomains/core/aml/aml-helper.service.ts
src/subdomains/generic/kyc/services/name-check.service.ts
src/subdomains/generic/user/models/wallet/wallet.entity.ts
src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
src/subdomains/supporting/payment/entities/transaction.entity.ts

[DEV-2905]&[DEV-2888] AmlRule skip susMail check, transaction type buyFiatOutput

---

src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts

[NOTASK] Improve supportTool

---

migration/1722260156443-LegalEntitySignatoryPower.js
src/subdomains/generic/kyc/controllers/kyc.controller.ts
src/subdomains/generic/kyc/dto/input/kyc-data.dto.ts
src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts

- [DEV-2909](https://dfxswiss.atlassian.net/browse/DEV-2909) - new KYC steps 
- Login/logout
- KYC page
[DEV-2909]: https://dfxswiss.atlassian.net/browse/DEV-2909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-2909] New KYC steps

---

migration/1722260156443-LegalEntitySignatoryPower.js
src/integration/lightning/lightning-client.ts
src/integration/lightning/lightning-helper.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts
src/subdomains/generic/kyc/controllers/kyc.controller.ts
src/subdomains/generic/kyc/dto/input/kyc-data.dto.ts
src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/kyc/dto/mapper/kyc-info.mapper.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

- [DEV-2802] [DEV-2805] [DEV-2807] [DEV-2909] New KYC-steps
- [NO-TASK] fix error of invoice desc_hash metadata
- Login/logout
- KYC page
[DEV-2802]: https://dfxswiss.atlassian.net/browse/DEV-2802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2805]: https://dfxswiss.atlassian.net/browse/DEV-2805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2807]: https://dfxswiss.atlassian.net/browse/DEV-2807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2909]: …

[DEV-2802], [DEV-2805], [DEV-2807], [DEV-2909], [NO-TASK] 

---

src/subdomains/generic/kyc/services/kyc-notification.service.ts

[NOTASK] fix kyc reminderMails

---

src/subdomains/generic/kyc/controllers/kyc.controller.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-2932] NationalityStep refactoring

---

src/subdomains/core/aml/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-2929] weeklyCheckout aml limit

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts

[FIX] fix chargebackNotPossible mail wo bankData

---

migration/1722976135849-AccountTypeDefaultNull.js
src/subdomains/generic/gs/gs.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/generic/user/models/user/dto/user-v2.dto.ts
src/subdomains/generic/user/models/user/dto/user.dto.ts
src/subdomains/supporting/payment/entities/fee.entity.ts
src/subdomains/supporting/payment/services/fee.service.ts

[DEV-2910] accountType default null

---

.github/workflows/api-dev.yaml
package-lock.json

[DEV-2948] node update

---

migration/1723313441422-AddChargebackAllowedBy.js
src/subdomains/core/buy-crypto/process/dto/update-buy-crypto.dto.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/dto/update-buy-fiat.dto.ts

[DEV-2968] chargebackAllowedBy

---

src/subdomains/core/monitoring/observers/payment.observer.ts

[DEV-2944] Improve monitoring

---

src/subdomains/core/aml/aml.service.ts
src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
src/subdomains/core/liquidity-management/adapters/actions/liquidity-pipeline.adapter.ts

[NOTASK] Reload bankData after merge

---

src/subdomains/core/liquidity-management/services/liquidity-management-pipeline.service.ts

[NO-TASK] LM execution loop

---

src/subdomains/core/liquidity-management/adapters/actions/liquidity-pipeline.adapter.ts
src/subdomains/core/liquidity-management/services/liquidity-management-pipeline.service.ts

[NO-TASK] LM improvements

---

src/subdomains/generic/user/models/user/dto/user-dto.mapper.ts
src/subdomains/generic/user/models/user/dto/user-v2.dto.ts

[NO-TASK] add Payment Link permission to User DTO

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
src/subdomains/core/liquidity-management/adapters/actions/liquidity-pipeline.adapter.ts
src/subdomains/core/liquidity-management/entities/liquidity-management-pipeline.entity.ts
src/subdomains/core/liquidity-management/services/liquidity-management-pipeline.service.ts
src/subdomains/generic/kyc/controllers/kyc-admin.controller.ts
src/subdomains/generic/user/models/user/dto/user-dto.mapper.ts
src/subdomains/generic/user/models/user/dto/user-v2.dto.ts
src/subdomains/supporting/notification/entities/mail/personal-mail.ts
src/subdomains/supporting/notification/factories/mail.factory.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts

[DEV-2824]&[NOTASK] Improve transfer action, bcc in personalMails

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/payment-link.module.ts

[DEV-2975]&[NOTASK] added payment link short, reset timelimit chargebackNotPossible mail

---

migration/1723809890294-AddPaymentQuoteWebhook.js
src/shared/utils/queue-handler.ts
src/subdomains/core/payment-link/dto/create-payment-link.dto.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/dto/update-payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/payment-link-payment.module.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/core/payment-link/services/payment-webhook.service.ts

[DEV-2933] payment quote webhook

---

migration/1723914432929-AddPaymentLinksName.js
src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts

[DEV-3000] userData paymentLinksName

---

migration/1723914432929-AddPaymentLinksName.js
migration/1724053870032-NoPaymentUniqueIndex.js
src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/create-invoice-payment.dto.ts
src/subdomains/core/payment-link/entities/payment-activation.entity.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts

[DEV-2975]&[DEV-3004]&[NOTASK]&[DEV-3000] paymentLink short arg, drop payment unique index, improvement, paymentLinksName

---

migration/1724071909790-AddPaymentLinkRecipient.js
src/subdomains/core/payment-link/dto/create-payment-link-payment.dto.ts
src/subdomains/core/payment-link/dto/create-payment-link.dto.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/dto/update-payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/repositories/payment-link.repository.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts

[DEV-3003] payment link recipient

---

migration/1724158978862-AddPaymentTxCount.js
src/shared/utils/async-map.ts
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-link-payment.entity.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts

[DEV-2978] payment wait endpoint

---

src/integration/sift/dto/sift.dto.ts
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/aml/enums/aml-reason.enum.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto.service.spec.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/__tests__/buy-fiat.service.spec.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[DEV-2942] VideoIdentNeeded

---

src/subdomains/core/payment-link/dto/create-payment-link-payment.dto.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts

[DEV-3015] currency as string

---

src/subdomains/core/payment-link/repositories/payment-link.repository.ts

[DEV-2694] only return payment links of active routes

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
src/subdomains/supporting/payment/services/transaction-request.service.ts

[DEV-2794] Just send buy crypto with FIAT orders/transactions to sift

---

src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts

[DEV-3025] Added sell action to exchange adapter

---

src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/repositories/payment-link.repository.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts

[DEV-3028] link and payment external id

---

src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/repositories/payment-link.repository.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts

* [DEV-3028] link and payment external id
* [DEV-3028] external payment id not for create
* [DEV-3028] changes after review
- Login/logout
- KYC page
[DEV-3028]: https://dfxswiss.atlassian.net/browse/DEV-3028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3028]: https://dfxswiss.atlassian.net/browse/DEV-3028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3028]: https://dfxswiss.atlassian.net/browse/DEV-3028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-3028] link and payment external id (#1552)

---

src/subdomains/core/monitoring/observers/payment.observer.ts
src/subdomains/core/sell-crypto/process/dto/update-buy-fiat.dto.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts

[NOTASK] change renamed col in dto

---

src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/base/bitcoin-based.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/base/evm.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/base/send.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/lightning.strategy.ts

[NOTASK] fix lightning return

---

src/subdomains/supporting/support-issue/entities/support-issue.entity.ts

[DEV-3044] add SupportIssueType.NOTIFICATION_OF_CHANGES

---

src/subdomains/generic/user/models/auth/auth.service.ts

[NOTASK] Reactivate account with mail login

---

migration/1725021580953-UserAddressType.js
src/integration/blockchain/shared/services/crypto.service.ts
src/subdomains/generic/user/models/auth/auth.service.ts
src/subdomains/generic/user/models/user/dto/update-user-admin.dto.ts
src/subdomains/generic/user/models/user/user.entity.ts
src/subdomains/generic/user/models/user/user.service.ts

[DEV-1929] user addressType

---

src/subdomains/supporting/log/log-job.service.ts

[DEV-2835] log financialType balance

---

src/shared/i18n/de/kyc.json
src/shared/i18n/en/kyc.json
src/shared/i18n/fr/kyc.json
src/shared/i18n/it/kyc.json

[DEV-3045] change "Notification of Changes" contact point

---

migration/1725021580953-UserAddressType.js
src/integration/blockchain/shared/services/crypto.service.ts
src/shared/i18n/de/kyc.json
src/shared/i18n/en/kyc.json
src/shared/i18n/fr/kyc.json
src/shared/i18n/it/kyc.json
src/subdomains/generic/kyc/dto/ident-check-error.enum.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc-notification.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user/dto/update-user-admin.dto.ts
src/subdomains/generic/user/models/user/user.entity.ts
src/subdomains/generic/user/models/user/user.service.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-1929]&[DEV-2835] user addressType, balance log financialType

---

src/subdomains/supporting/log/log-job.service.ts

[DEV-3056] log balance chf

---

migration/1725292202834-BankAccountUserDataNullable.js
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/supporting/bank/bank-account/bank-account.entity.ts
src/subdomains/supporting/bank/bank-account/bank-account.service.ts
src/subdomains/supporting/bank/bank-account/is-dfx-iban.validator.ts
src/subdomains/supporting/payment/entities/special-external-account.entity.ts
src/subdomains/supporting/payment/services/special-external-account.service.ts

[DEV-3053] Separate bannedBic buy sell

---

src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/update-payment-link-payment.dto.ts
src/subdomains/core/payment-link/entities/payment-link-payment.entity.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts

[DEV-3038] paymentLinkPayment device update

---

src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/supporting/log/log-job.module.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payin/services/payin.service.ts

[DEV-2836] Improve balance log

---

src/subdomains/supporting/log/log-job.service.ts

[DEV-3067] change balance log structure

---

migration/1725292202834-BankAccountUserDataNullable.js
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/aml/services/sanction.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/update-payment-link-payment.dto.ts
src/subdomains/core/payment-link/entities/payment-link-payment.entity.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/generic/kyc/services/kyc-notification.service.ts
src/subdomains/supporting/bank/bank-account/bank-account.entity.ts
src/subdomains/supporting/bank/bank-account/bank-account.service.ts
src/subdomains/supporting/bank/bank-account/is-dfx-iban.validator.ts
src/subdomains/supporting/log/log-job.module.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payin/services/payin.service.ts
src/subdomains/supporting/payment/entities/special-external-account.entity.ts
src/subdomains/supporting/payment/services/special-external-account.service.ts

[NOTASK]&[DEV-2816]&[DEV-3056]&[DEV-3066]&[DEV-3060]&[DEV-3053]&[DEV-3038]&[DEV-2836] Improvements

---

src/subdomains/supporting/log/log-job.service.ts

[DEV-3056] Fix balance CHF

---

migration/1725348870382-HexEndpoint.js
src/integration/alchemy/services/alchemy.service.ts
src/integration/blockchain/shared/evm/dto/evm-signed-transaction-reponse.dto.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/shared/services/process.service.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-activation.entity.ts
src/subdomains/core/payment-link/entities/payment-quote.entity.ts
src/subdomains/core/payment-link/enums/index.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-cron.service.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/generic/forwarding/controllers/lnurlp-forward.controller.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts

[DEV-3035] hex endpoint

---

migration/1725348870382-HexEndpoint.js
src/config/config.ts
src/integration/alchemy/services/alchemy.service.ts
src/integration/blockchain/shared/evm/dto/evm-signed-transaction-reponse.dto.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/shared/services/process.service.ts
src/shared/utils/util.ts
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/create-invoice-payment.dto.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-activation.entity.ts
src/subdomains/core/payment-link/entities/payment-link-payment.entity.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/entities/payment-quote.entity.ts
src/subdomains/core/payment-link/entities/standard.config.ts
src/subdomains/core/payment-link/enums/index.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-cron.service.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/generic/forwarding/controllers/__tests__/lnurl-forward.spec.ts
src/subdomains/generic/forwarding/controllers/lnurlp-forward.controller.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/supporting/payin/entities/crypto-input.entity.ts

[DEV-3014] payment link standards

---

src/subdomains/supporting/bank/bank-account/bank-account.service.ts

[DEV-3085] fix adding already requested bankAccount

---

src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-link-payment.entity.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/payment-link.module.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/generic/forwarding/controllers/__tests__/lnurl-forward.spec.ts
src/subdomains/generic/forwarding/forwarding.module.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts

[DEV-3087] payment not found response

---

src/integration/infrastructure/azure-storage.service.ts
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-link-payment.entity.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/payment-link.module.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/generic/forwarding/controllers/__tests__/lnurl-forward.spec.ts
src/subdomains/generic/forwarding/forwarding.module.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts
src/subdomains/generic/gs/gs.service.ts
src/subdomains/generic/kyc/services/integration/kyc-document.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts

[DEV-3087] payment not found response [DEV-3091] Ident kyc step check [NO-TASK] document migration

---

src/integration/lightning/lightning-helper.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-registration.service.ts
src/subdomains/core/payment-link/entities/payment-activation.entity.ts
src/subdomains/core/payment-link/entities/payment-quote.entity.ts
src/subdomains/core/payment-link/enums/index.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-registration.service.ts
src/subdomains/supporting/payin/services/payin.service.ts

[DEV-3036] input handling

---

src/subdomains/supporting/log/log-job.service.ts

[DEV-3057] balance log totalBalance

---

src/integration/blockchain/shared/evm/abi/uniswap-v3-nft-manager.abi.json
src/integration/blockchain/shared/evm/evm-client.ts
src/shared/models/asset/asset.entity.ts
src/subdomains/core/liquidity-management/adapters/balances/blockchain.adapter.ts

[DEV-3071] Implemented pool position balances

---

src/subdomains/core/liquidity-management/adapters/balances/bank.adapter.ts
src/subdomains/core/liquidity-management/dto/input/liquidity-management-rule-creation.dto.ts
src/subdomains/core/liquidity-management/enums/index.ts
src/subdomains/core/liquidity-management/factories/liquidity-balance-integration.factory.ts
src/subdomains/core/liquidity-management/liquidity-management.module.ts
src/subdomains/core/monitoring/observers/bank.observer.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/bank/bank/__mocks__/bank.entity.mock.ts
src/subdomains/supporting/bank/bank/bank.entity.ts
src/subdomains/supporting/bank/bank/bank.service.ts
src/subdomains/supporting/bank/bank/dto/bank.dto.ts

[DEV-3075] checkout balances in balanceAdapter

---

src/subdomains/generic/user/models/user/dto/update-user-admin.dto.ts
src/subdomains/generic/user/models/user/user.service.ts

[DEV-3080] user update endpoint set ref

---

src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payin/services/payin.service.ts

[DEV-3077] log balance differentiate pending balances

---

migration/1725958684942-ActivationStatusRename.js
src/config/config.ts
src/shared/services/process.service.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-activation.entity.ts
src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/entities/payment-quote.entity.ts
src/subdomains/core/payment-link/enums/index.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-cron.service.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/generic/forwarding/controllers/__tests__/lnurl-forward.spec.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts

[DEV-3104] payment config

---

migration/1725958684942-ActivationStatusRename.js
src/config/config.ts
src/shared/services/process.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-activation.entity.ts
src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/entities/payment-quote.entity.ts
src/subdomains/core/payment-link/enums/index.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-cron.service.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/generic/forwarding/controllers/__tests__/lnurl-forward.spec.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payin/entities/crypto-input.entity.ts
src/subdomains/supporting/payin/services/payin.service.ts

[DEV-3077]&[NOTASK] not forward payment inputs, pending balance improvements

---

migration/1725997902507-CryptoInputPaymentQuote.js
src/config/config.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-registration.service.ts
src/subdomains/core/payment-link/entities/payment-quote.entity.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-registration.service.ts
src/subdomains/supporting/payin/entities/crypto-input.entity.ts
src/subdomains/supporting/payin/services/payin.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3104] input fix

---

src/subdomains/supporting/log/log-job.service.ts

[DEV-3114] balance log minusBalance

---

src/subdomains/supporting/bank-tx/bank-tx/bank-tx.controller.ts

[DEV-2950] restrict uploadSepaFiles endpoint

---

src/subdomains/supporting/log/log-job.service.ts

[DEV-3120] balanceByFinancialType minusBalance

---

src/subdomains/generic/gs/gs.service.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-3124] skip undefined balanceLog

---

migration/1726061526398-RemoveLimitRequestCols.js
src/subdomains/supporting/support-issue/dto/create-support-issue.dto.ts
src/subdomains/supporting/support-issue/dto/limit-request.dto.ts
src/subdomains/supporting/support-issue/entities/limit-request.entity.ts
src/subdomains/supporting/support-issue/services/limit-request.service.ts

[DEV-3112] remove unused limitRequest cols

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3118] amlCheck minVolume refactoring

---

migration/1726136380521-WalletsWithDummyAddresses.js
src/subdomains/generic/user/models/user/dto/user-dto.mapper.ts
src/subdomains/generic/user/models/wallet/wallet.entity.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[NO-TASK] Added config for wallets with dummy addresses

---

src/shared/models/asset/asset.service.ts
src/subdomains/supporting/dex/services/dex-polygon.service.ts

[DEV-3097] MATIC rename

---

migration/1725896607355-AddRouteTable.js
src/shared/services/process.service.ts
src/subdomains/core/buy-crypto/buy-crypto.module.ts
src/subdomains/core/buy-crypto/routes/buy/buy.entity.ts
src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
src/subdomains/core/buy-crypto/routes/swap/swap.entity.ts
src/subdomains/core/buy-crypto/routes/swap/swap.service.ts
src/subdomains/core/core.module.ts
src/subdomains/core/route/dto/create-route.dto.ts
src/subdomains/core/route/dto/update-route.dto.ts
src/subdomains/core/route/route.controller.ts
src/subdomains/core/route/route.entity.ts
src/subdomains/core/route/route.module.ts
src/subdomains/core/route/route.repository.ts
src/subdomains/core/route/route.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/core/sell-crypto/route/sell.entity.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/core/trading/services/trading-job.service.ts
src/subdomains/supporting/address-pool/address-pool.module.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3055]&[FIX]&[DEV-3134] route table, amlCheck missing outputAsset, fix plusBalance balanceLog

---

src/subdomains/core/route/route.module.ts
src/subdomains/supporting/support-issue/services/limit-request-notification.service.ts

[FIX] fix limitRequest mails

---

src/subdomains/supporting/log/log-job.service.ts

[NO-TASK] Simplified balance log

---

src/subdomains/generic/gs/gs.service.ts

[DEV-3141] gs endpoint json improvement

---

migration/1726484428228-AddKycLogEventDate.js
src/subdomains/generic/kyc/controllers/kyc-admin.controller.ts
src/subdomains/generic/kyc/dto/input/create-kyc-log.dto.ts
src/subdomains/generic/kyc/entities/kyc-log.entity.ts
src/subdomains/generic/kyc/services/kyc-log.service.ts

[DEV-3145] kycLog eventDate

---

src/subdomains/generic/user/models/user/dto/user-dto.mapper.ts
src/subdomains/generic/user/models/user/dto/user-v2.dto.ts

[DEV-3093] new disabledAddresses field in UserV2Dto

---

src/subdomains/core/buy-crypto/buy-crypto.module.ts
src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.service.spec.ts
src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
src/subdomains/core/buy-crypto/routes/swap/swap.service.ts
src/subdomains/core/route/route.module.ts
src/subdomains/core/route/route.service.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/core/sell-crypto/sell-crypto.module.ts

[DEV-3146] Auto create route

---

migration/1726241282692-SupportIssueUId.js
src/subdomains/generic/gs/gs.service.ts
src/subdomains/supporting/support-issue/dto/create-support-issue.dto.ts
src/subdomains/supporting/support-issue/entities/support-issue.entity.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts
src/subdomains/supporting/support-issue/support-issue.controller.ts

[DEV-2825] Implemented support issue UID

---

src/shared/services/process.service.ts
src/subdomains/core/buy-crypto/buy-crypto.module.ts
src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
src/subdomains/core/buy-crypto/routes/swap/swap.service.ts
src/subdomains/core/route/route.service.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/core/sell-crypto/sell-crypto.module.ts

[DEV-3147] remove route sync

---

src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/update-payment-link.dto.ts
src/subdomains/core/payment-link/services/payment-link.service.ts

[DEV-3148] paymentLink update endpoint

---

src/subdomains/supporting/support-issue/services/support-document.service.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts

[NO-TASK] Fixed support document sync

---

migration/1726840507343-TradingSwapFee.js
src/subdomains/core/trading/entities/trading-order.entity.ts
src/subdomains/core/trading/services/trading-order.service.ts

[DEV-3143] Added trading swap fee

---

src/subdomains/generic/kyc/controllers/kyc.controller.ts

[NOTASK] fix ident webhook error

---

src/subdomains/generic/kyc/dto/input/ident-result.dto.ts
src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts

[NO-TASK] Back to interface

---

src/subdomains/generic/kyc/dto/ident-result-data.dto.ts
src/subdomains/generic/kyc/dto/kyc-result-data.dto.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[NO-TASK] Fixed sumsub ident

---

src/subdomains/generic/kyc/controllers/kyc-admin.controller.ts
src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[NO-TASK] Added manual ident sync

---

src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/history/dto/refund-internal.dto.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/supporting/payin/services/payin.service.ts

[NOTASK] exception when input already returned

---

src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts

[DEV-3156] Implemented sumsub SDK

---

src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts

[NOTASK]&[DEV-3156] sumsub sdk, find refundUser fix

---

src/subdomains/generic/kyc/services/integration/sum-sub.service.ts

[DEV-3156] Switched sumsub KYC level

---

src/subdomains/generic/kyc/controllers/kyc.controller.ts
src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-2966]&[DEV-2967] add two new optional KYC steps

---

src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/supporting/payment/entities/special-external-account.entity.ts
src/subdomains/supporting/payment/services/special-external-account.service.ts

[NOTASK] add accountIban block

---

src/subdomains/core/trading/entities/trading-rule.entity.ts
src/subdomains/core/trading/services/trading.service.ts
src/subdomains/supporting/pricing/domain/entities/price-rule.entity.ts
src/subdomains/supporting/pricing/pricing.module.ts
src/subdomains/supporting/pricing/services/integration/pricing-constant.service.ts
src/subdomains/supporting/pricing/services/pricing.service.ts

[DEV-2657] Implemented constant pricing

---

migration/1727443350989-MergeReason.js
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/kyc-log.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/account-merge/account-merge.entity.ts
src/subdomains/generic/user/models/account-merge/account-merge.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[NO-TASK] Improved merge logs

---

src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/history/history.module.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/core/transaction/transaction-util.module.ts
src/subdomains/core/transaction/transaction-util.service.ts

[DEV-3176] set refundTarget for chargebackIban

---

migration/1727443350989-MergeReason.js
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/history/history.module.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/core/trading/entities/trading-rule.entity.ts
src/subdomains/core/trading/services/trading.service.ts
src/subdomains/core/transaction/transaction-util.module.ts
src/subdomains/core/transaction/transaction-util.service.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/kyc-log.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/account-merge/account-merge.entity.ts
src/subdomains/generic/user/models/account-merge/account-merge.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/bank/bank-account/is-dfx-iban.validator.ts
src/subdomains/supporting/pricing/domain/entities/price-rule.entity.ts
src/subdomains/supporting/pricing/pricing.module.ts
src/subdomains/supporting/pricing/services/integration/pricing-constant.service.ts
src/subdomains/supporting/pricing/services/pricing.service.ts

[DEV-3187]&[DEV-2657]&[NOTASK] constant pricing, merge logs, dfx iban not allowed

---

src/shared/models/asset/asset.service.ts
src/subdomains/core/trading/entities/trading-rule.entity.ts

[DEV-2657] Fix & refactoring

---

src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/create-invoice-payment.dto.ts
src/subdomains/core/payment-link/dto/create-payment-link-payment.dto.ts
src/subdomains/core/payment-link/services/payment-link.service.ts

[NO-TASK]: webhook param on Payment endpoint

---

src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/create-invoice-payment.dto.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/generic/gs/gs.service.ts

[NOTASK]&[DEV-3175] Improvement payment endpoint, array logic in gs endpoint

---

infrastructure/bicep/dfx-api.bicep
infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
src/config/config.ts
src/subdomains/core/payment-link/payment-link-payment.module.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/generic/gs/gs.service.ts
src/subdomains/supporting/address-pool/deposit/deposit.service.ts
src/subdomains/supporting/payin/strategies/register/impl/monero.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/monero.strategy.ts
src/subdomains/supporting/payout/payout.module.ts

[NOTASK] Refactoring array logic gs endpoint

---

src/subdomains/generic/user/models/account-merge/account-merge.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts

[DEV-3204] iban merge for master

---

src/subdomains/generic/gs/gs.service.ts
src/subdomains/generic/user/models/account-merge/account-merge.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts

[DEV-3204]&[DEV-3215] iban merge for master, fix gs array function

---

src/subdomains/generic/user/models/auth/auth.controller.ts
src/subdomains/generic/user/models/auth/auth.service.ts
src/subdomains/generic/user/models/auth/dto/verify-sign-message.dto.ts

[DEV-2524] add signature verification endpoint

---

src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc-notification.service.ts
src/subdomains/supporting/notification/factories/mail.factory.ts
src/subdomains/supporting/notification/notification.module.ts

[DEV-3212] Refactoring ident error mail

---

src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/generic/forwarding/controllers/lnurlp-forward.controller.ts
src/subdomains/generic/forwarding/dto/payment.dto.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts

[DEV-3209] Open payment wait endpoint

---

src/integration/exchange/dto/exchange-tx.dto.ts
src/integration/exchange/entities/exchange-tx.entity.ts
src/integration/exchange/exchange.module.ts
src/integration/exchange/mappers/exchange-tx.mapper.ts
src/integration/exchange/services/exchange-tx.service.ts
src/subdomains/supporting/bank-tx/bank-tx/entities/bank-tx.entity.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/log/log-job.module.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-3217] financeLog pending Amounts

---

src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/services/payment-link.service.ts

[DEV-3198] Added recipient to payment link config

---

src/subdomains/supporting/log/log-job.service.ts

[NOTASK] fix financialLog exchangeAmount

---

src/subdomains/supporting/bank-tx/bank-tx/entities/bank-tx.entity.ts

[NOTASK] fix financialLog 2

---

src/subdomains/supporting/log/log-job.service.ts

[NOTASK] fix financialLog 4

---

migration/1728551171987-AddAssetFiatAmlRule.js
src/shared/models/asset/asset.entity.ts
src/shared/models/fiat/fiat.entity.ts
src/subdomains/core/aml/enums/aml-rule.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/generic/user/models/wallet/dto/wallet.dto.ts
src/subdomains/generic/user/models/wallet/wallet.entity.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3232] asset amlRule

---

migration/1728487950655-PaymentFee.js
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts

[DEV-3117] Payment fee

---

migration/1727885942716-RenameBankDataCols.js
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/buy-crypto/process/dto/update-buy-crypto.dto.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/generic/user/models/bank-data/dto/create-bank-data.dto.ts
src/subdomains/generic/user/models/bank-data/dto/update-bank-data.dto.ts

[DEV-2989] rename bankData col

---

migration/1728464997390-AddBankDataLabelCurrencyCol.js
src/shared/services/process.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/supporting/bank/bank-account/bank-account.entity.ts
src/subdomains/supporting/bank/bank-account/bank-account.service.ts

[DEV-3063] bankAccount bankData sync

---

src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts

[FIX] fix amlCheck buyFiat outputAsset

---

migration/1728909581873-AddAssetFiatAmlRuleFromAmlRuleTo.js
src/shared/models/asset/asset.entity.ts
src/shared/models/fiat/fiat.entity.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3253] add amlRuleFrom, amlRuleTo

---

src/integration/exchange/entities/exchange-tx.entity.ts
src/integration/exchange/services/exchange-tx.service.ts
src/subdomains/supporting/bank-tx/bank-tx/entities/bank-tx.entity.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-3229] financialLog chf pendingAmount

---

src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/enums/aml-rule.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3254] amlRule assetAmount

---

src/config/config.ts
src/integration/blockchain/shared/evm/dto/evm-raw-input-data.dto.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/subdomains/generic/gs/gs-evm.controller.ts
src/subdomains/generic/gs/gs-evm.service.ts

[DEV-3214] create sendRawInputData endpoint

---

src/subdomains/supporting/log/log-job.service.ts

[FIX] fix financialLog

---

src/integration/alchemy/controllers/alchemy.controller.ts
src/integration/alchemy/services/alchemy-webhook.service.ts
src/shared/utils/util.ts

[DEV-2892] Use alchemy webhook signature

---

infrastructure/bicep/dfx-api.bicep
infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
package-lock.json
package.json
src/config/config.ts
src/integration/alchemy/alchemy-network-mapper.ts
src/integration/alchemy/controllers/alchemy.controller.ts
src/integration/alchemy/services/alchemy-webhook.service.ts
src/integration/alchemy/services/alchemy.service.ts
src/integration/blockchain/bsc/bsc-client.ts
src/integration/blockchain/bsc/bsc.module.ts
src/integration/blockchain/bsc/bsc.service.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/shared/utils/util.ts
src/subdomains/core/liquidity-management/adapters/balances/blockchain.adapter.ts

[DEV-3048] BSC to alchemy

---

migration/1729019908345-symbol3Unique.js
src/shared/models/country/country.entity.ts

[DEV-3167] change symbol3 to unique

---

infrastructure/bicep/dfx-api.bicep
infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
src/config/config.ts
src/subdomains/supporting/log/log-job.module.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-3234] special balance addresses

---

src/integration/exchange/entities/exchange-tx.entity.ts
src/integration/exchange/services/exchange-tx.service.ts
src/subdomains/supporting/bank-tx/bank-tx/entities/bank-tx.entity.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-3230] financialLog pendingBalances 2

---

migration/1729093904453-FeeFinancialType.js
src/subdomains/supporting/payment/entities/fee.entity.ts

[DEV-3268] fee financialType col

---

src/shared/services/process.service.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/fiat-output/fiat-output.service.ts

[DEV-3265] fiatOutput complete

---

migration/1729093904453-FeeFinancialType.js
src/shared/services/process.service.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/fiat-output/fiat-output.service.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payment/entities/fee.entity.ts

[FIX] fix filter pending sender list

---

src/integration/alchemy/services/alchemy.service.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/subdomains/supporting/payin/services/base/payin-evm.service.ts
src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts

[DEV-3048] toBlock in get asset transfers

---

migration/1729153982778-LiquidityManagementNotifications.js
src/subdomains/core/liquidity-management/adapters/actions/liquidity-pipeline.adapter.ts
src/subdomains/core/liquidity-management/entities/liquidity-management-rule.entity.ts
src/subdomains/core/liquidity-management/services/liquidity-management-pipeline.service.ts
src/subdomains/core/liquidity-management/services/liquidity-management-rule.service.ts

[DEV-3238] LM notifications

---

src/subdomains/supporting/log/log-job.service.ts

[DEV-3231] financialLog pending eur amount

---

migration/1729153982778-LiquidityManagementNotifications.js
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/liquidity-management/adapters/actions/liquidity-pipeline.adapter.ts
src/subdomains/core/liquidity-management/entities/liquidity-management-rule.entity.ts
src/subdomains/core/liquidity-management/services/liquidity-management-pipeline.service.ts
src/subdomains/core/liquidity-management/services/liquidity-management-rule.service.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-3238]&[DEV-DEV-3231]&[NOTASK] fix pending exchange order, lm notification, lm error message, financialLog pending amount

---

src/integration/blockchain/shared/evm/evm-client.ts
src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts

[NO-TASK] Alchemy sync fix

---

src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts

[FIX] fix chargeback bankTx

---

src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts

[DEV-3279] fix bankTx pending amounts

---

src/subdomains/supporting/log/log-job.service.ts

[DEV-3277] fix financialLog bug

---

src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts

[DEV-3048] map token entries decimals

---

src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/history/dto/refund-internal.dto.ts
src/subdomains/core/transaction/transaction-util.service.ts
src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts

[NOTASK] refund checkoutTx for users

---

src/integration/blockchain/monero/dto/monero.dto.ts
src/integration/blockchain/monero/monero-client.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts

[DEV-3224] Monero hex endpoint

---

src/integration/blockchain/shared/evm/evm-client.ts
src/shared/utils/cron.ts
src/subdomains/supporting/payin/services/base/payin-evm.service.ts
src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts

[DEV-3048] improvement get history

---

src/integration/blockchain/monero/dto/monero.dto.ts
src/integration/blockchain/monero/monero-client.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/shared/utils/cron.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/supporting/bank/bank-account/bank-account.service.ts
src/subdomains/supporting/payin/services/base/payin-evm.service.ts
src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts

[DEV-3224]&[NOTASK]&[DEV-2964]&[DEV-3048] monero hex endpoint, checkout refundTarget, nationality step changes, history improvement

---

src/subdomains/supporting/payin/strategies/send/impl/monero.strategy.ts

[DEV-3225] Monero returns

---

src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/generic/kyc/controllers/kyc.controller.ts
src/subdomains/generic/kyc/dto/input/start-2fa.dto.ts
src/subdomains/generic/kyc/dto/mapper/kyc-info.mapper.ts
src/subdomains/generic/kyc/dto/output/kyc-info.dto.ts
src/subdomains/generic/kyc/dto/output/setup-2fa.dto.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/kyc/services/tfa.service.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/notification/enums/index.ts
src/subdomains/supporting/notification/factories/mail.factory.ts
src/subdomains/supporting/payin/strategies/send/impl/monero.strategy.ts

[DEV-3225] Monero returns [DEV-3123] Mail 2FA

---

src/subdomains/supporting/log/log-job.service.ts

[DEV-3282] fix financialLog bug

---

migration/1729588433771-PaymentConfirmation.js
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-link-payment.entity.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts

[DEV-3271] payment confirm

---

src/subdomains/supporting/support-issue/services/support-issue.service.ts
src/subdomains/supporting/support-issue/support-issue.controller.ts

[DEV-3123] add getIssues endpoint

---

migration/1729588433771-PaymentConfirmation.js
src/config/config.ts
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-link-payment.entity.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts
src/subdomains/supporting/support-issue/support-issue.controller.ts

[NOTASK]&[DEV-3282] DB timeout, financialLog bug

---

src/subdomains/supporting/log/log-job.service.ts

[NOTASK] more financeLog logging

---

src/subdomains/supporting/log/log-job.service.ts

[DEV-3285] show total zero values

---

src/subdomains/supporting/log/log-job.service.ts

[NOTASK] fix plusBalanceChf

---

src/shared/utils/util.ts
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/get-payment-link-history.dto.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/repositories/payment-link.repository.ts
src/subdomains/core/payment-link/services/payment-link.service.ts

[DEV-3043] Payment list (history)

---

src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts

[DEV-3270] Config payment expiry

---

src/shared/utils/util.ts
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/get-payment-link-history.dto.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/repositories/payment-link.repository.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/generic/forwarding/controllers/lnurlp-forward.controller.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts
src/subdomains/generic/kyc/repositories/mail-change-log.repository.ts
src/subdomains/generic/kyc/repositories/merge-log.repository.ts
src/subdomains/supporting/log/log-job.service.ts

[NOTASK]&[DEV-3043] payment list history, financialLog sort, kyc logs

---

src/subdomains/generic/user/models/wallet/dto/wallet.dto.ts

[DEV-3294] allow update wallet displayName

---

src/subdomains/core/payment-link/services/payment-link.service.ts

[DEV-3216] Wait for pending payment

---

package-lock.json
package.json
src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts

[DEV-3048] Alchemy BSC update

---

package-lock.json
package.json
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts

[DEV-3048]&[NOTASK] alchemy bsc update, financeLog fix

---

src/main.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/aml/services/aml.service.ts
src/subdomains/generic/kyc/controllers/kyc.controller.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-3165]&[NOTASK] webhook verification sumsub, financialLog fix 2

---

src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payin/entities/crypto-input.entity.ts
src/subdomains/supporting/payin/services/payin.service.ts

[NOTASK] financialLog reset date

---

src/subdomains/supporting/log/log-job.service.ts

[NOTASK] try quick fix

---

src/subdomains/core/aml/services/aml.service.ts
src/subdomains/generic/user/models/account-merge/account-merge.entity.ts
src/subdomains/generic/user/models/account-merge/account-merge.service.ts
src/subdomains/generic/user/models/user-data/user-data.controller.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3298] merge kycLevel improvement

---

src/integration/exchange/services/exchange-tx.service.ts
src/shared/models/asset/asset.service.ts
src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/liquidity-management/adapters/actions/base/evm-l2-bridge.adapter.ts
src/subdomains/generic/user/models/account-merge/account-merge.entity.ts
src/subdomains/generic/user/models/account-merge/account-merge.service.ts
src/subdomains/generic/user/models/user-data/user-data.controller.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/bank-tx/bank-tx.module.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/bank-tx/bank-tx/services/sepa-parser.service.ts
src/subdomains/supporting/fiat-output/fiat-output.service.ts

[NOTASK] add logger in fiatOutput job

---

src/subdomains/core/history/controllers/transaction.controller.ts

[NOTASK] fix refund with invalid iban

---

migration/1729938623909-UserDataCTKey.js
src/config/config.ts
src/shared/services/api-key.service.ts
src/subdomains/core/history/controllers/history.controller.ts
src/subdomains/core/history/services/history.service.ts
src/subdomains/core/staking/services/staking.service.ts
src/subdomains/generic/user/models/user-data/user-data.controller.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/generic/user/models/user/user.controller.ts
src/subdomains/generic/user/models/user/user.service.ts

[DEV-3296] CT userData api key

---

migration/1729938623909-UserDataCTKey.js
migration/1730310677880-AddUserIpLog.js
src/config/config.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/shared/models/ip-log/ip-log.entity.ts
src/shared/models/ip-log/ip-log.service.ts
src/shared/services/api-key.service.ts
src/subdomains/core/buy-crypto/routes/swap/swap.entity.ts
src/subdomains/core/history/controllers/history.controller.ts
src/subdomains/core/history/services/history.service.ts
src/subdomains/core/staking/services/staking.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/generic/user/models/user/dto/user-dto.mapper.ts
src/subdomains/generic/user/models/user/user.controller.ts
src/subdomains/generic/user/models/user/user.service.ts
src/subdomains/supporting/payin/services/payin.service.ts

* [DEV-3296] CT userData api key
* [DEV-3296] add migration
* [DEV-3296] Refactoring
* [DEV-3296] Refactoring 2
* [DEV-3296] Refactoring 3
* [DEV-3296] Refactoring 4
- Login/logout
- KYC page
[DEV-3296]: https://dfxswiss.atlassian.net/browse/DEV-3296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3296]: https://dfxswiss.atlassian.net/browse/DEV-3296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3296]: https://dfxswiss.atlassian.net/browse/DEV-3296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …

[DEV-3296] CT userData api key (#1741)

---

.vscode/settings.json
rest-client/dfx-api.http
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts

[NOTASK] delete chargebackOutput for buyCrypto reset

---

migration/1730807216547-CollectiveFiatPayouts.js
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-job.service.ts
src/subdomains/generic/gs/gs.service.ts
src/subdomains/generic/user/models/account-merge/account-merge.service.ts
src/subdomains/supporting/fiat-output/fiat-output.entity.ts
src/subdomains/supporting/fiat-output/fiat-output.service.ts

[DEV-3228] Collective fiat payouts

---

src/subdomains/generic/kyc/dto/ident-result-data.dto.ts
src/subdomains/generic/kyc/dto/input/kyc-data.dto.ts
src/subdomains/generic/kyc/dto/manual-ident-result.dto.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3346] Fix manual Ident

---

src/subdomains/supporting/support-issue/dto/create-support-issue.dto.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts
src/subdomains/supporting/support-issue/support-issue.controller.ts

[DEV-3227] supportIssue by support

---

migration/1730705112313-AddSenderAddresses.js
src/integration/blockchain/ain/node/dto/btc-transaction.dto.ts
src/subdomains/core/transaction/transaction-util.service.ts
src/subdomains/supporting/payin/entities/crypto-input.entity.ts
src/subdomains/supporting/payin/interfaces/index.ts
src/subdomains/supporting/payin/services/payin-bitcoin.service.ts
src/subdomains/supporting/payin/services/payin.service.ts
src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
src/subdomains/supporting/payin/strategies/register/impl/bitcoin.strategy.ts
src/subdomains/supporting/payin/strategies/register/impl/lightning.strategy.ts
src/subdomains/supporting/payin/strategies/register/impl/monero.strategy.ts

[DEV-2812] add sender addresses

---

migration/1730705112313-AddSenderAddresses.js
src/integration/blockchain/ain/node/dto/btc-transaction.dto.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-job.service.ts
src/subdomains/core/transaction/transaction-util.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/supporting/payin/entities/crypto-input.entity.ts
src/subdomains/supporting/payin/interfaces/index.ts
src/subdomains/supporting/payin/services/payin-bitcoin.service.ts
src/subdomains/supporting/payin/services/payin.service.ts
src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
src/subdomains/supporting/payin/strategies/register/impl/bitcoin.strategy.ts
src/subdomains/supporting/payin/strategies/register/impl/lightning.strategy.ts
src/subdomains/supporting/payin/strategies/register/impl/monero.strategy.ts

[FIX] fix kyc verification

---

src/integration/bank/services/olkypay.service.ts

[NO-TASK] Fix for future Olkypay transactions

---

src/subdomains/generic/kyc/entities/kyc-step.entity.ts

[NOTASK] fix manual ident completion 2

---

migration/1731136439777-AddCategoryValidLog.js
src/integration/blockchain/frankencoin/frankencoin.service.ts
src/subdomains/supporting/log/dto/create-log.dto.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/log/log.entity.ts
src/subdomains/supporting/log/log.service.ts

[DEV-3304] Add valid and category column

---

migration/1731428656810-buySellBankData.js
src/shared/services/process.service.ts
src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.service.spec.ts
src/subdomains/core/buy-crypto/routes/buy/buy.entity.ts
src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
src/subdomains/core/sell-crypto/route/sell.entity.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/supporting/bank/bank-account/bank-account.service.ts

[DEV-3352] replace bankAccounts with bankData

---

src/subdomains/supporting/log/log-job.service.ts

[FIX] fix financeLog

---

src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts

[DEV-3359] Alchemy Webhook - ignore 0x values

---

src/subdomains/supporting/log/dto/create-log.dto.ts
src/subdomains/supporting/log/log.controller.ts
src/subdomains/supporting/log/log.service.ts

[DEV-3356] Update log entry

---

src/shared/utils/util.ts
src/subdomains/supporting/bank-tx/bank-tx/entities/bank-tx.entity.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/fiat-output/fiat-output.service.ts
src/subdomains/supporting/log/dto/create-log.dto.ts
src/subdomains/supporting/log/dto/log.dto.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/log/log.controller.ts
src/subdomains/supporting/log/log.service.ts
src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts

[NOTASK] financeLog changes correct buyCryptoFee

---

migration/1731574551987-countryNationalityStepEnable.js
src/shared/models/country/country.entity.ts
src/shared/models/country/dto/country-dto.mapper.ts
src/shared/models/country/dto/country.dto.ts

[DEV-3365] country nationalityStepEnable

---

migration/1731574551987-countryNationalityStepEnable.js
src/shared/models/country/country.entity.ts
src/shared/models/country/dto/country-dto.mapper.ts
src/shared/models/country/dto/country.dto.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-job.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/generic/kyc/controllers/kyc.controller.ts
src/subdomains/supporting/fiat-output/fiat-output.service.ts

* [DEV-3365] country nationalityStepEnable
* [DEV-3365] add migration
- Login/logout
- KYC page
[DEV-3365]: https://dfxswiss.atlassian.net/browse/DEV-3365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3365]: https://dfxswiss.atlassian.net/browse/DEV-3365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-3365] country nationalityStepEnable (#1779)

---

src/integration/alchemy/services/alchemy.service.ts
src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/supporting/bank/bank-account/bank-account.controller.ts

[NOTASK] Refactoring bankAccount buy/sell sync

---

src/subdomains/generic/kyc/controllers/kyc.controller.ts
src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/kyc/dto/mapper/kyc-file.mapper.ts
src/subdomains/generic/kyc/entities/kyc-file-log.entity.ts
src/subdomains/generic/kyc/entities/kyc-file.entity.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/kyc.module.ts
src/subdomains/generic/kyc/repositories/kyc-file-log.repository.ts
src/subdomains/generic/kyc/repositories/kyc-file.repository.ts
src/subdomains/generic/kyc/services/integration/kyc-document.service.ts
src/subdomains/generic/kyc/services/kyc-file.service.ts
src/subdomains/generic/kyc/services/kyc-log.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/kyc/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.controller.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3081] Create KycFile DB table + endpoint

---

README.md
migration/1731963190430-ChangeSpecialCode.js
src/shared/services/payment-info.service.ts
src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
src/subdomains/core/buy-crypto/routes/buy/dto/get-buy-quote.dto.ts
src/subdomains/core/buy-crypto/routes/swap/dto/get-swap-quote.dto.ts
src/subdomains/core/buy-crypto/routes/swap/swap.controller.ts
src/subdomains/core/sell-crypto/route/dto/get-sell-quote.dto.ts
src/subdomains/core/sell-crypto/route/sell.controller.ts
src/subdomains/generic/user/models/auth/auth.service.ts
src/subdomains/generic/user/models/auth/dto/auth-credentials.dto.ts
src/subdomains/generic/user/models/user/dto/create-user.dto.ts
src/subdomains/generic/user/models/user/user.controller.ts
src/subdomains/generic/user/models/user/user.service.ts
src/subdomains/supporting/payment/dto/input/create-fee.dto.ts
src/subdomains/supporting/payment/entities/fee.entity.ts
src/subdomains/supporting/payment/services/fee.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-2394] Change discount code to special code

---

src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3377] restrict ident with userDataExisting

---

src/subdomains/generic/kyc/services/kyc.service.ts

[NO-TASK] Commented KYC file sync

---

src/config/config.ts

[NO-TASK]: Railgun signature regex

---

migration/1732015898509-removeBankAccountBuySell.js
src/shared/services/process.service.ts
src/subdomains/core/buy-crypto/routes/buy/__mocks__/buy.entity.mock.ts
src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
src/subdomains/core/buy-crypto/routes/buy/buy.entity.ts
src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
src/subdomains/core/buy-crypto/routes/buy/dto/create-buy.dto.ts
src/subdomains/core/sell-crypto/route/__mocks__/sell.entity.mock.ts
src/subdomains/core/sell-crypto/route/sell.entity.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
src/subdomains/supporting/bank/bank-account/__mocks__/bank-account.entity.mock.ts
src/subdomains/supporting/bank/bank-account/bank-account.entity.ts
src/subdomains/supporting/bank/bank/__tests__/bank.service.spec.ts
src/subdomains/supporting/bank/bank/bank.service.ts

* [DEV-3373] remove bankAccount in buy/sell
* [DEV-3373] fix unit test
* [DEV-3373] add migration
- Login/logout
- KYC page
[DEV-3373]: https://dfxswiss.atlassian.net/browse/DEV-3373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3373]: https://dfxswiss.atlassian.net/browse/DEV-3373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3373]: https://dfxswiss.atlassian.net/browse/DEV-3373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-3373] remove bank account buy sell (#1795)

---

src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/transaction/transaction-util.module.ts
src/subdomains/core/transaction/transaction-util.service.ts

[NOTASK] fix refund block multiAccountIbans

---

migration/1732636815181-AddCustodyProvider.js
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/custody-provider/__mocks__/custody-provider.entity.mock.ts
src/subdomains/generic/user/models/custody-provider/custody-provider.controller.ts
src/subdomains/generic/user/models/custody-provider/custody-provider.entity.ts
src/subdomains/generic/user/models/custody-provider/custody-provider.repository.ts
src/subdomains/generic/user/models/custody-provider/custody-provider.service.ts
src/subdomains/generic/user/models/custody-provider/dto/custody-provider.dto.ts
src/subdomains/generic/user/models/user/user.entity.ts
src/subdomains/generic/user/user.module.ts

[DEV-2350]&[FIX] custody provider, fix ident split bug

---

infrastructure/bicep/dfx-api.bicep
src/config/config.ts
src/integration/sift/dto/sift.dto.ts
src/integration/sift/services/sift.service.ts
src/shared/utils/util.ts
src/subdomains/core/liquidity-management/services/liquidity-management.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/generic/user/models/user/tests/user.service.spec.ts
src/subdomains/generic/user/models/user/user.service.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-3058] Decision api sift [DEV-3391] Improved merge checks

---

migration/1733047979126-addTransactionCols.js
src/config/config.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/history/controllers/transaction-admin.controller.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/history/dto/update-transaction.dto.ts
src/subdomains/core/history/history.module.ts
src/subdomains/core/history/mappers/transaction-dto.mapper.ts
src/subdomains/core/history/services/history.service.ts
src/subdomains/core/referral/referral.module.ts
src/subdomains/core/referral/reward/dto/update-ref-reward.dto.ts
src/subdomains/core/referral/reward/ref-reward.controller.ts
src/subdomains/core/referral/reward/ref-reward.entity.ts
src/subdomains/core/referral/reward/services/ref-reward-dex.service.ts
src/subdomains/core/referral/reward/services/ref-reward-job.service.ts
src/subdomains/core/referral/reward/services/ref-reward-notification.service.ts
src/subdomains/core/referral/reward/services/ref-reward-out.service.ts
src/subdomains/core/referral/reward/services/ref-reward.service.ts
src/subdomains/core/statistic/statistic.controller.ts
src/subdomains/generic/gs/gs.service.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payment/dto/input/update-transaction-internal.dto.ts
src/subdomains/supporting/payment/entities/transaction.entity.ts
src/subdomains/supporting/payment/services/transaction.service.ts

[NOTASK] RefReward refactoring

---

migration/1733221494398-removeBankDataUniqueIndex.js
src/subdomains/core/sell-crypto/route/sell.entity.ts
src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts

[DEV-3402] remove unique index

---

migration/1733221494398-removeBankDataUniqueIndex.js
src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts

* [DEV-3402] remove unique index
* [DEV-3402] add check again
* [DEV-3402] add migration
- Login/logout
- KYC page
[DEV-3402]: https://dfxswiss.atlassian.net/browse/DEV-3402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3402]: https://dfxswiss.atlassian.net/browse/DEV-3402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3402]: https://dfxswiss.atlassian.net/browse/DEV-3402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-3402] remove unique index (#1820)

---

package-lock.json
package.json
src/config/config.ts
src/subdomains/generic/kyc/dto/ident.dto.ts
src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/kyc/enums/content-type.enum.ts
src/subdomains/generic/kyc/services/integration/ident.service.ts
src/subdomains/generic/kyc/services/integration/kyc-document.service.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts
src/subdomains/generic/kyc/services/kyc-client.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/kyc/kyc.service.ts
src/subdomains/generic/user/models/user-data/dto/upload-file.dto.ts
src/subdomains/generic/user/models/user-data/user-data.controller.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/generic/user/models/user/dto/download-user-data.dto.ts
src/subdomains/supporting/support-issue/services/support-document.service.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts

[DEV-3387] Files download endpoint 

---

package-lock.json
package.json
src/config/config.ts
src/subdomains/generic/kyc/dto/ident.dto.ts
src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/kyc/enums/content-type.enum.ts
src/subdomains/generic/kyc/services/integration/ident.service.ts
src/subdomains/generic/kyc/services/integration/kyc-document.service.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts
src/subdomains/generic/kyc/services/kyc-client.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/kyc/kyc.service.ts
src/subdomains/generic/user/models/user-data/dto/upload-file.dto.ts
src/subdomains/generic/user/models/user-data/user-data.controller.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/generic/user/models/user/dto/download-user-data.dto.ts
src/subdomains/supporting/support-issue/services/support-document.service.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts

[DEV-3387] Files download endpoint

---

src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/kyc/services/integration/kyc-document.service.ts
src/subdomains/generic/kyc/services/kyc-client.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/kyc/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3387] Fixes & improvements

---

src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/kyc/services/integration/kyc-document.service.ts
src/subdomains/generic/kyc/services/kyc-client.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/kyc/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

* [DEV-3387] fixes & improvements
* [DEV-3387] log error if no verifiedName
- Login/logout
- KYC page
[DEV-3387]: https://dfxswiss.atlassian.net/browse/DEV-3387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3387]: https://dfxswiss.atlassian.net/browse/DEV-3387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-3387] Fixes & improvements (#1823)

---

src/config/config.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
src/subdomains/generic/user/models/user-data/kyc-identification-type.enum.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3406] additional export data

---

src/config/config.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/generic/kyc/services/integration/kyc-document.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3406] Export fixes

---

src/subdomains/core/aml/services/aml-helper.service.ts

[NOTASK] Crucial pending aml errors

---

src/config/config.ts
src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/kyc/enums/file-category.enum.ts
src/subdomains/generic/kyc/services/integration/kyc-document.service.ts
src/subdomains/generic/kyc/services/kyc-client.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/kyc/kyc.service.ts

[DEV-3413] Additional export data

---

src/config/config.ts
src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/kyc/enums/file-category.enum.ts
src/subdomains/generic/kyc/services/integration/kyc-document.service.ts
src/subdomains/generic/kyc/services/kyc-client.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/kyc/kyc.service.ts
src/subdomains/supporting/dex/services/base/dex-evm.service.ts

[NO-TASK] removed pending amount cap, [DEV-3413] additional export data

---

migration/1733331767293-addCountryTxCols.js
src/config/config.ts
src/shared/models/country/country.entity.ts
src/shared/models/country/dto/country-dto.mapper.ts
src/shared/models/country/dto/country.dto.ts
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/generic/kyc/dto/kyc-error.enum.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/bank/bank-account/bank-account.controller.ts
src/subdomains/supporting/bank/bank-account/dto/create-bank-account.dto.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts

[NOTASK] remove iban check for internal use

---

src/integration/blockchain/frankencoin/dto/frankencoin.dto.ts
src/integration/blockchain/frankencoin/frankencoin-client.ts
src/integration/blockchain/frankencoin/frankencoin.service.ts

[DEV-3245] Update LogInfo for Ponder V1 and V2

---

src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/generic/user/models/account-merge/account-merge.service.ts

[DEV-3203] merge mail refactoring

---

src/subdomains/generic/user/models/user-data/user-data.controller.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[NO-TASK] Return ZIP as StreamableFile

---

src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/account-merge/account-merge.service.ts
src/subdomains/generic/user/models/user-data/user-data.controller.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3203]&[NO-TASK] merge mail refactoring, return ZIP as StreamableFile

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts

[NOTASK] fix checkoutTx bug

---

src/integration/alchemy/dto/alchemy-transaction.dto.ts
src/integration/alchemy/dto/alchemy-transaction.mapper.ts
src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts

[DEV-3048] BSC to alchemy adapt manual sync

---

src/integration/alchemy/dto/alchemy-transaction.dto.ts
src/integration/alchemy/dto/alchemy-transaction.mapper.ts
src/subdomains/core/monitoring/observers/payment.observer.ts
src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts

[NOTASK] Refactoring cryptoInput monitoring

---

src/integration/blockchain/shared/enums/blockchain.enum.ts
src/subdomains/core/payment-link/dto/payment-link-config.dto.ts
src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts

[DEV-3445] define payment link compatible blockchains

---

src/integration/blockchain/shared/enums/blockchain.enum.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/payment-link/dto/payment-link-config.dto.ts
src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/generic/kyc/dto/mapper/kyc-info.mapper.ts
src/subdomains/generic/user/models/auth/auth.controller.ts
src/subdomains/generic/user/models/auth/auth.service.ts
src/subdomains/generic/user/models/user/user.service.ts

define payment link compatible blockchains, update auth endpoint for address addition, Improved KYC step filtering

---

src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts

[DEV-3462] Set amountInChf only in amlCheck

---

src/integration/alchemy/controllers/alchemy.controller.ts
src/integration/alchemy/services/alchemy-webhook.service.ts
src/main.ts

[NO-TASK] change alchemy webhook to raw request

---

src/integration/alchemy/controllers/alchemy.controller.ts
src/subdomains/generic/kyc/controllers/kyc.controller.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts

[NO-TASK] Fix

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/supporting/bank/bank-account/bank-account.controller.ts

[DEV-3469] userBankData update refactoring

---

migration/1734357833598-addUserDataAmlListCols.js
src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3473] add new amlList cols

---

src/subdomains/supporting/payment/dto/transaction-helper/quote-error.enum.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3468] nationality quoteError

---

migration/1734357833598-addUserDataAmlListCols.js
src/config/config.ts
src/integration/blockchain/bsc/bsc-client.ts
src/shared/auth/ip-country.guard.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/bank/bank-account/bank-account.controller.ts
src/subdomains/supporting/bank/bank-account/dto/bank-account.dto.ts
src/subdomains/supporting/payment/dto/transaction-helper/quote-error.enum.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3469]&[DEV-3473] userBankData update refactoring, new amlList cols

---

src/subdomains/core/history/mappers/transaction-dto.mapper.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[DEV-3379] limitExceeded transactionState

---

src/integration/blockchain/frankencoin/dto/frankencoin.dto.ts
src/integration/blockchain/frankencoin/frankencoin-client.ts
src/integration/blockchain/frankencoin/frankencoin.service.ts

[DEV-3467] Frankencoin Log Data from Ponder

---

src/integration/blockchain/frankencoin/dto/frankencoin.dto.ts
src/integration/blockchain/frankencoin/frankencoin-client.ts
src/integration/blockchain/frankencoin/frankencoin.service.ts
src/subdomains/generic/kyc/controllers/kyc-admin.controller.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3460]&[DEV-3467]: Implemented file sync, Frankencoin Log Data from Ponder

---

src/subdomains/generic/user/models/user/user.service.ts

[NO-TASK] Fixed sign up

---

src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3470] kyc nationality auto failed

---

src/integration/sift/dto/sift.dto.ts
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/aml/enums/aml-reason.enum.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[DEV-3497] amlReason missing liq

---

src/integration/sift/dto/sift.dto.ts
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/aml/enums/aml-reason.enum.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/supporting/log/dto/log.dto.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[NOTASK] fix externalReview ident bug

---

src/subdomains/core/history/controllers/transaction.controller.ts

[NOTASK] fix checkout refund

---

src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/supporting/payin/entities/crypto-input.entity.ts
src/subdomains/supporting/payin/services/payin.service.ts
src/subdomains/supporting/support-issue/entities/support-issue.entity.ts

[NOTASK] SupportIssueReason, remove unused code, improve kyc ident check

---

src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/history/dto/refund-data.dto.ts

[DEV-3509] fix refund bankFee bug

---

src/shared/utils/util.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/generic/user/models/auth/auth.service.ts
src/subdomains/supporting/bank/bank-account/bank-account.service.ts

[NOTASK] fix undefined bug for unknown ibanCountry

---

src/subdomains/core/transaction/transaction-util.service.ts

[NOTASK] refund fix 2

---

migration/1736008113726-addUserDataAmlListStatus.js
src/subdomains/core/aml/enums/aml-list-status.enum.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts

[DEV-3515] amlListStatus

---

src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
src/subdomains/core/buy-crypto/routes/buy/dto/get-buy-quote.dto.ts
src/subdomains/core/buy-crypto/routes/swap/dto/get-swap-quote.dto.ts
src/subdomains/core/buy-crypto/routes/swap/swap.controller.ts
src/subdomains/core/sell-crypto/route/dto/get-sell-quote.dto.ts
src/subdomains/core/sell-crypto/route/sell.controller.ts
src/subdomains/supporting/payment/services/fee.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3501] integrate wallet in quote

---

src/shared/repositories/repository.factory.ts
src/subdomains/core/monitoring/observers/payment.observer.ts

[DEV-3512] monitoring refReward manualCheck

---

migration/1736008113726-addUserDataAmlListStatus.js
src/shared/repositories/repository.factory.ts
src/subdomains/core/aml/enums/aml-list-status.enum.ts
src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
src/subdomains/core/buy-crypto/routes/buy/dto/get-buy-quote.dto.ts
src/subdomains/core/buy-crypto/routes/swap/dto/get-swap-quote.dto.ts
src/subdomains/core/buy-crypto/routes/swap/swap.controller.ts
src/subdomains/core/monitoring/observers/payment.observer.ts
src/subdomains/core/sell-crypto/route/dto/get-sell-quote.dto.ts
src/subdomains/core/sell-crypto/route/sell.controller.ts
src/subdomains/generic/kyc/dto/mapper/kyc-info.mapper.ts
src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts
src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/payment/services/fee.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

* [DEV-3515] amlListStatus
* [DEV-3515] add migration
- Login/logout
- KYC page
[DEV-3515]: https://dfxswiss.atlassian.net/browse/DEV-3515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3515]: https://dfxswiss.atlassian.net/browse/DEV-3515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-3515] amlListStatus (#1880)

---

src/subdomains/generic/kyc/dto/ident-result.dto.ts
src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3439] Add pending if type init

---

src/subdomains/generic/kyc/dto/ident-result.dto.ts
src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3439] Add pending if type init (#1887)

---

migration/1736346664324-addForeignName.js
src/shared/models/country/country.entity.ts
src/shared/models/country/dto/country-dto.mapper.ts
src/shared/models/country/dto/country.dto.ts

[DEV-3518] Add foreignName to country table

---

migration/1732580379505-AddMinConfirmation.js
migration/1732808206829-RemoveMasterKeyWallet.js
migration/1736346664324-addForeignName.js
src/integration/blockchain/ain/node/btc-client.ts
src/shared/models/country/country.entity.ts
src/shared/models/country/dto/country-dto.mapper.ts
src/shared/models/country/dto/country.dto.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/auth/auth.service.ts
src/subdomains/generic/user/models/user/user.service.ts
src/subdomains/generic/user/models/wallet/dto/wallet.dto.ts
src/subdomains/generic/user/models/wallet/wallet.entity.ts
src/subdomains/generic/user/models/wallet/wallet.service.ts
src/subdomains/supporting/payin/services/base/payin-evm.service.ts
src/subdomains/supporting/payin/services/payin-bitcoin.service.ts
src/subdomains/supporting/payin/services/payin-monero.service.ts
src/subdomains/supporting/payin/strategies/send/impl/base/bitcoin-based.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/base/evm.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/base/evm.token.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/base/send.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/bitcoin.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/monero.strategy.ts
src/subdomains/supporting/payment/entities/transaction-specification.entity.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-1506]&[DEV-3518]&[DEV-2350]&[NOTASK] min confirmation, foreignName, costody provider, kyc webhook fix

---

src/integration/exchange/dto/__mocks__/exchange-tx.entity.mock.ts
src/subdomains/supporting/log/__tests__/log-job.service.spec.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-3500] fix financeLog bug

---

src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/shared/utils/util.ts
src/subdomains/supporting/payment/services/transaction-notification.service.ts

[DEV-3511] mail bankTx currency exchange

---

src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/supporting/payment/services/transaction-notification.service.ts

[NOTASK] fix txUnassigned mail

---

.github/workflows/api-pr.yaml
.github/workflows/api-prd.yaml
migration/1736952747456-addTransactionRequestUid.js
src/integration/sift/services/sift.service.ts
src/shared/services/process.service.ts
src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
src/subdomains/core/buy-crypto/routes/buy/dto/buy-payment-info.dto.ts
src/subdomains/core/buy-crypto/routes/swap/dto/swap-payment-info.dto.ts
src/subdomains/core/buy-crypto/routes/swap/swap.controller.ts
src/subdomains/core/history/mappers/transaction-dto.mapper.ts
src/subdomains/core/referral/reward/ref-reward.entity.ts
src/subdomains/core/referral/reward/services/ref-reward.service.ts
src/subdomains/core/sell-crypto/route/dto/sell-payment-info.dto.ts
src/subdomains/core/sell-crypto/route/sell.controller.ts
src/subdomains/supporting/payment/__mocks__/transaction-request.entity.mock.ts
src/subdomains/supporting/payment/entities/transaction-request.entity.ts
src/subdomains/supporting/payment/services/transaction-request.service.ts
src/subdomains/supporting/payment/services/transaction.service.ts
src/subdomains/supporting/support-issue/dto/create-support-issue.dto.ts
src/subdomains/supporting/support-issue/entities/support-issue.entity.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts
src/subdomains/supporting/support-issue/support-issue.controller.ts
src/subdomains/supporting/support-issue/support-issue.module.ts

* [DEV-3532] refReward userSwitch status
* [DEV-3532] fix missing code
- Login/logout
- KYC page
[DEV-3532]: https://dfxswiss.atlassian.net/browse/DEV-3532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3532]: https://dfxswiss.atlassian.net/browse/DEV-3532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-3532] ref reward user switch status (#1897)

---

src/subdomains/core/trading/services/trading-rule.service.ts

[DEV-3441] Paused trading rule

---

src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/trading/services/trading-rule.service.ts
src/subdomains/supporting/payment/services/transaction.service.ts

[NOTASK]&[DEV-3441]&[DEV-3539] payment auto confirm, paused trading rule, fix transaction bug

---

src/integration/exchange/services/exchange-tx.service.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/log/dto/log.dto.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-3528] improve financeLog

---

src/config/config.ts
src/integration/exchange/services/exchange-tx.service.ts
src/shared/services/process.service.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/referral/reward/services/ref-reward.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/log/dto/log.dto.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payment/services/fee.service.ts

[DEV-3549] No home address document for organizations

---

src/subdomains/supporting/log/log-job.service.ts

[NOTASK] financeLog filter pair ids

---

src/subdomains/supporting/log/__tests__/log-job.service.spec.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-3545] financeLog improvements 2

---

infrastructure/bicep/dfx-api.bicep
infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
src/config/config.ts
src/integration/blockchain/deuro/deuro-client.ts
src/integration/blockchain/deuro/deuro.service.ts
src/integration/blockchain/frankencoin/frankencoin-client.ts
src/integration/blockchain/frankencoin/frankencoin.service.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/integration/blockchain/shared/frankencoin/frankencoin-based.service.ts
src/subdomains/core/liquidity-management/adapters/actions/base/frankencoin-based.adapter.ts
src/subdomains/core/liquidity-management/adapters/actions/deuro.adapter.ts
src/subdomains/core/liquidity-management/adapters/actions/frankencoin.adapter.ts
src/subdomains/core/liquidity-management/enums/index.ts
src/subdomains/core/liquidity-management/factories/liquidity-action-integration.factory.ts
src/subdomains/core/liquidity-management/liquidity-management.module.ts
src/subdomains/generic/gs/gs.controller.ts

[DEV-3446] FPS/nDEPS minting

---

src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/dto/payment-request.mapper.ts

[DEV-3088] Add hint in EVM response

---

src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/enums/content-type.enum.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts

[DEV-3563] Get video media

---

src/subdomains/generic/kyc/services/integration/sum-sub.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3563] Fixed video download and manual file sync

---

migration/1737629605853-UserDataRelationSignatoryOptional.js
src/subdomains/generic/user/models/user-data-relation/dto/create-user-data-relation.dto.ts
src/subdomains/generic/user/models/user-data-relation/dto/update-user-data-relation.dto.ts
src/subdomains/generic/user/models/user-data-relation/user-data-relation.controller.ts
src/subdomains/generic/user/models/user-data-relation/user-data-relation.entity.ts
src/subdomains/generic/user/models/user-data-relation/user-data-relation.service.ts

[DEV-3567] userDataRelation optional signatory

---

src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/history/mappers/transaction-dto.mapper.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/supporting/log/__tests__/log-job.service.spec.ts
src/subdomains/supporting/log/log-job.service.ts

[NOTASK] change financeLogger to verbose

---

src/subdomains/generic/kyc/dto/mapper/kyc-step.mapper.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3568] Added KYC step status

---

migration/1737809090150-UserDataPostAmlCheck.js
src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts

[DEV-3572] add postAmlCheck

---

migration/1737809090150-UserDataPostAmlCheck.js
src/subdomains/generic/kyc/dto/mapper/kyc-step.mapper.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3568]&[DEV-3572] added kycStep status, postAmlCheck

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts

[DEV-3576] fix aml merge volume bug

---

src/subdomains/core/aml/aml.module.ts
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/buy-crypto/buy-crypto.module.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/core/sell-crypto/sell-crypto.module.ts

[DEV-3573] kycFileId refactoring

---

src/config/config.ts
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/generic/user/models/auth/auth.service.ts

[NOTASK] remove amlList check

---

src/subdomains/generic/kyc/controllers/kyc-admin.controller.ts
src/subdomains/generic/kyc/dto/input/create-kyc-log.dto.ts
src/subdomains/generic/kyc/entities/manual-log.entity.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/kyc.module.ts
src/subdomains/generic/kyc/repositories/manual-log.repository.ts
src/subdomains/generic/kyc/services/kyc-log.service.ts

[DEV-3584] KYC logs with file upload

---

README.md
src/config/config.ts
src/integration/sift/dto/sift.dto.ts
src/shared/auth/ip-country.guard.ts
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/aml/enums/aml-reason.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/generic/kyc/controllers/kyc-admin.controller.ts
src/subdomains/generic/kyc/dto/input/create-kyc-log.dto.ts
src/subdomains/generic/kyc/entities/manual-log.entity.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/kyc.module.ts
src/subdomains/generic/kyc/repositories/manual-log.repository.ts
src/subdomains/generic/kyc/services/kyc-log.service.ts
src/subdomains/generic/user/models/auth/dto/auth-credentials.dto.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts
src/subdomains/supporting/payment/services/swiss-qr.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[NOTASK] allow number regions, save userData update

---

infrastructure/bicep/dfx-api.bicep
infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
src/config/config.ts
src/shared/services/process.service.ts
src/shared/utils/util.ts
src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
src/subdomains/core/monitoring/monitor-connection-pool.service.ts
src/subdomains/core/monitoring/monitoring.module.ts
src/subdomains/generic/gs/gs.service.ts

[DEV-3583] Check connection pool

---

src/subdomains/generic/kyc/dto/ident-result.dto.ts
src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3577] Download video when its available (after webhook)

---

src/config/config.ts
src/subdomains/core/monitoring/monitor-connection-pool.service.ts

[DEV-3583] Monitor connection pool

---

infrastructure/bicep/dfx-api.bicep
infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
migration/1738319166726-KycLogFile.js
src/config/config.ts
src/shared/services/process.service.ts
src/shared/utils/util.ts
src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
src/subdomains/core/monitoring/monitor-connection-pool.service.ts
src/subdomains/core/monitoring/monitoring.module.ts
src/subdomains/generic/gs/dto/support-data.dto.ts
src/subdomains/generic/gs/gs.service.ts
src/subdomains/generic/kyc/dto/ident-result.dto.ts
src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/entities/kyc-file.entity.ts
src/subdomains/generic/kyc/entities/kyc-log.entity.ts
src/subdomains/generic/kyc/services/integration/kyc-document.service.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts
src/subdomains/generic/kyc/services/kyc-client.service.ts
src/subdomains/generic/kyc/services/kyc-log.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/kyc/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.controller.ts

[DEV-3583] DB connection pool [DEV-3584] KYC log file relation

---

migration/1738595868385-AddBankAmlEnabled.js
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/supporting/bank/bank/bank.entity.ts

[DEV-3607] bank amlEnabled

---

migration/1738595868385-AddBankAmlEnabled.js
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/trading/services/trading-rule.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/supporting/bank/bank/bank.entity.ts

[DEV-3584] Result fix

---

migration/1738681331278-FiatOutputReport.js
src/shared/utils/util.ts
src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-job.service.ts
src/subdomains/generic/kyc/dto/mapper/kyc-info.mapper.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/supporting/fiat-output/dto/ep2-report.dto.ts
src/subdomains/supporting/fiat-output/ep2-report.service.ts
src/subdomains/supporting/fiat-output/fiat-output.entity.ts
src/subdomains/supporting/fiat-output/fiat-output.module.ts
src/subdomains/supporting/fiat-output/fiat-output.service.ts

[NOTASK] Refactoring kyc info mapper

---

src/subdomains/core/aml/services/aml-helper.service.ts

AssetAmount to 100k

---

src/config/config.ts
src/shared/services/dfx-cron.service.ts
src/shared/shared.module.ts
src/shared/utils/cron.ts
src/shared/utils/custom-cron-expression.ts
src/shared/utils/lock.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3625] Download file renaming [DEV-3624] identificationType update [DEV-3583] DFX cron decorator

---

src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3641] Download media independent from kyc status

---

src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/payment/dto/transaction-helper/quote-error.enum.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3640] aml improvements

---

src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto.service.spec.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/__tests__/buy-fiat.service.spec.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts

[DEV-3633] fix manual aml update

---

src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
src/subdomains/core/buy-crypto/routes/buy/dto/buy-payment-info.dto.ts
src/subdomains/supporting/payment/dto/transaction-helper/quote-error.enum.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3646] add QuoteError NameRequired

---

src/subdomains/core/monitoring/observers/checkout.observer.ts

[DEV-3601] Add syncDate to checkout observer

---

migration/1738429095584-WalletAddFraudWarning.js
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
src/subdomains/generic/user/models/wallet/wallet.entity.ts

[DEV-3388] deposit mail warning addition

---

migration/1739643604085-AddFeeExcludingAssets.js
src/subdomains/supporting/payment/dto/input/create-fee.dto.ts
src/subdomains/supporting/payment/entities/fee.entity.ts
src/subdomains/supporting/payment/services/fee.service.ts

[DEV-3551] fee excludedAssets

---

package-lock.json
package.json
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3542] unify user data name input

---

src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3550] block kyc sumSubBlockLabels

---

migration/1737629409528-addTransactionRequestUidUnique.js
src/subdomains/supporting/payment/entities/transaction-request.entity.ts

[DEV-3534] transactionRequest uid unique

---

src/shared/utils/parallel-queue.ts
src/shared/utils/queue-handler.ts
src/subdomains/core/history/controllers/history.controller.ts
src/subdomains/core/payment-link/services/payment-webhook.service.ts

[DEV-3634] CoinTracking Queue

---

src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3628] fix networkStartFee in TxDetail calculation

---

src/shared/models/active.ts
src/shared/models/asset/dto/asset-dto.mapper.ts
src/shared/models/fiat/dto/fiat-dto.mapper.ts
src/shared/utils/util.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/history/mappers/transaction-dto.mapper.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts
src/subdomains/supporting/pricing/domain/entities/price.ts

[DEV-3656] Rounding fix

---

src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/history/mappers/transaction-dto.mapper.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-job.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts
src/subdomains/supporting/payment/services/transaction.service.ts

[DEV-3647] Added more transaction states

---

migration/1740043761421-ChangeBuyFiatBankTx.js
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-job.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/generic/gs/gs.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/bank-tx/bank-tx/entities/bank-tx.entity.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts

[DEV-3644] buyFiat completion

---

src/subdomains/core/buy-crypto/routes/buy/dto/buy-payment-info.dto.ts
src/subdomains/core/buy-crypto/routes/swap/dto/swap-payment-info.dto.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/history/mappers/transaction-dto.mapper.ts
src/subdomains/core/sell-crypto/route/dto/sell-payment-info.dto.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts
src/subdomains/supporting/payment/services/transaction.service.ts
src/subdomains/supporting/support-issue/dto/create-support-issue.dto.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts

[DEV-3663] public transaction endpoint

---

src/shared/services/process.service.ts
src/subdomains/supporting/bank-tx/bank-tx-return/bank-tx-return.entity.ts
src/subdomains/supporting/bank-tx/bank-tx-return/bank-tx-return.service.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts

[DEV-3665] bankTxReturn update job

---

migration/1739880957294-AddOrganizationTable.js
migration/1740043761421-ChangeBuyFiatBankTx.js
src/shared/auth/ip-country.guard.ts
src/shared/services/process.service.ts
src/subdomains/core/buy-crypto/routes/buy/dto/buy-payment-info.dto.ts
src/subdomains/core/buy-crypto/routes/swap/dto/swap-payment-info.dto.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/history/mappers/transaction-dto.mapper.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-job.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/core/sell-crypto/route/dto/sell-payment-info.dto.ts
src/subdomains/generic/gs/gs.service.ts
src/subdomains/generic/user/models/organization/dto/organization.dto.ts
src/subdomains/generic/user/models/organization/organization.entity.ts
src/subdomains/generic/user/models/organization/organization.repository.ts
src/subdomains/generic/user/models/organization/organization.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/generic/user/user.module.ts
src/subdomains/supporting/bank-tx/bank-tx-return/bank-tx-return.entity.ts
src/subdomains/supporting/bank-tx/bank-tx-return/bank-tx-return.service.ts
src/subdomains/supporting/bank-tx/bank-tx/entities/bank-tx.entity.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts
src/subdomains/supporting/payment/services/transaction.service.ts
src/subdomains/supporting/support-issue/dto/create-support-issue.dto.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts

[DEV-3647]&[NOTASK]&[DEV-2144] transaction states, minor fixes, organization

---

migration/1740137995169-AddBankTxSenderChargeAmount.js
src/subdomains/supporting/bank-tx/bank-tx/entities/bank-tx.entity.ts
src/subdomains/supporting/bank-tx/bank-tx/services/sepa-parser.service.ts

[DEV-3626] bankTx senderChargeAmount

---

src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts

[DEV-3636] Download images from sumsub

---

src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts

[NOTASK]&[DEV-3636] refund fix, download sumsub images

---

src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/entities/kyc-file.entity.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts

[NOTASK] userData relation, kyc video ident improvement

---

src/subdomains/generic/kyc/entities/kyc-file.entity.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/supporting/payin/entities/crypto-input.entity.ts
src/subdomains/supporting/payin/services/payin.service.ts
src/subdomains/supporting/payin/strategies/send/impl/base/bitcoin-based.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/base/evm.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/lightning.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/monero.strategy.ts

[DEV-2505] Fixed forward fee verification

---

migration/1739907449972-AddAmountChf.js
src/integration/exchange/entities/exchange-tx.entity.ts
src/integration/exchange/services/exchange-tx.service.ts
src/shared/repositories/repository.factory.ts
src/subdomains/core/monitoring/monitoring.module.ts
src/subdomains/core/monitoring/observers/exchange.observer.ts

[DEV-3524] Add exchange observer

---

src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
src/subdomains/core/buy-crypto/routes/swap/swap.service.ts
src/subdomains/core/sell-crypto/route/sell.service.ts

[NO-TASK] add not found exceptions

---

src/subdomains/core/monitoring/observers/exchange.observer.ts
src/subdomains/supporting/payin/strategies/send/impl/base/send.strategy.ts

[DEV-3524]&[NOTASK] fixed observer, fixed fee check

---

src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts

[NOTASK] fix buyFiat complete

---

src/config/config.ts
src/subdomains/generic/user/models/auth/auth-alby.service.ts
src/subdomains/generic/user/models/auth/auth.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

Fixed redirect URL check

---

src/subdomains/core/custody/controllers/custody.controller.ts

[NO-TASK] Fix for custody creation

---

src/subdomains/core/custody/controllers/custody.controller.ts

[NO-TASK] Fix for custody creation (#2004)

---

migration/1740864893515-RemoveUserDataRiskState.js
src/subdomains/generic/user/models/user-data/user-data.entity.ts

[DEV-3698] remove userData riskState

---

migration/1740864893515-RemoveUserDataRiskState.js
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user/dto/user-dto.mapper.ts
src/subdomains/generic/user/models/user/dto/user-v2.dto.ts

[DEV-3698] remove userData riskState [DEV-3705] Added isCustody to user address

---

src/subdomains/generic/kyc/dto/ident-result.dto.ts
src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[NO-TASK] Fixed ident retry

---

src/shared/services/process.service.ts
src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-notification.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/generic/kyc/dto/ident-result.dto.ts
src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user/user.service.ts
src/subdomains/supporting/bank-tx/bank-tx-return/bank-tx-return.service.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/fiat-output/fiat-output.service.ts
src/subdomains/supporting/fiat-payin/services/fiat-payin-sync.service.ts
src/subdomains/supporting/payment/entities/transaction.entity.ts
src/subdomains/supporting/payment/services/transaction-notification.service.ts
src/subdomains/supporting/payment/services/transaction.service.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts

[NOTASK] uniqueIds 6 to 16 digits, fiatOutput fill refactoring

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-webhook.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/generic/user/services/webhook/webhook.service.ts

[NOTASK] fix webhook userData relation

---

infrastructure/bicep/dfx-api.bicep
infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
src/config/config.ts
src/subdomains/core/payment-link/entities/payment-quote.entity.ts
src/subdomains/core/payment-link/enums/index.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts

[DEV-3599] special transaction for payment bot

---

infrastructure/bicep/dfx-api.bicep
infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
src/config/config.ts
src/subdomains/core/payment-link/entities/payment-quote.entity.ts
src/subdomains/core/payment-link/enums/index.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/supporting/payin/strategies/send/impl/base/send.strategy.ts

[NO-TASK] Fixed fee estimation 2

---

src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/generic/kyc/controllers/kyc-admin.controller.ts

[NOTASK] fix missing refund relation

---

src/subdomains/generic/kyc/controllers/kyc.controller.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/enums/kyc-step-name.enum.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3700] stockRegister renaming

---

src/subdomains/core/aml/services/aml.service.ts
src/subdomains/generic/kyc/controllers/kyc.controller.ts
src/subdomains/generic/kyc/dto/input/kyc-data.dto.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/enums/kyc-step-name.enum.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/kyc/services/name-check.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/generic/user/models/user-data-relation/dto/create-user-data-relation.dto.ts
src/subdomains/generic/user/models/user-data-relation/dto/update-user-data-relation.dto.ts
src/subdomains/generic/user/models/user-data-relation/user-data-relation.service.ts
src/subdomains/generic/user/models/user-data/dto/create-user-data.dto.ts
src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
src/subdomains/generic/user/user.module.ts

[DEV-3699] kycStep beneficialOwner

---

src/config/config.ts
src/subdomains/generic/kyc/dto/kyc-error.enum.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3553] manual sumSub block

---

src/config/config.ts
src/subdomains/generic/kyc/dto/kyc-error.enum.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/organization/dto/organization.dto.ts
src/subdomains/generic/user/models/organization/organization.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[NOTASK] fix organization country update bug

---

src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts

[DEV-3667] buyCrypto update logic

---

src/subdomains/core/aml/services/aml.service.ts

[DEV-3675] transaction amlCheck update logic

---

src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/__tests__/buy-fiat.service.spec.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/payin/strategies/send/impl/base/bitcoin-based.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/base/evm.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/base/send.strategy.ts
src/subdomains/supporting/payment/services/transaction-helper.ts
src/subdomains/supporting/support-issue/dto/create-support-message.dto.ts

[DEV-3667]&[DEV-3675] buyCrypto, transaction update logic

---

src/subdomains/generic/user/models/user-data/user-data.service.ts

[NOTASK] Reactoring merge relations

---

src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/payin/services/payin.service.ts

[NOTASK] add refund relation

---

src/shared/models/asset/asset.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3736] add assetType Presale

---

src/shared/utils/util.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[NOTASK] log memory

---

infrastructure/bicep/dfx-api.bicep
infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
src/config/config.ts
src/integration/blockchain/ain/node/btc-client.ts
src/integration/blockchain/ain/node/node-client.ts
src/integration/blockchain/monero/services/monero.service.ts
src/integration/blockchain/shared/enums/blockchain.enum.ts
src/integration/blockchain/shared/services/crypto.service.ts
src/shared/utils/util.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/payment-link/entities/payment-quote.entity.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/generic/user/user.module.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payment/services/fee.service.ts
src/subdomains/supporting/payment/services/transaction.service.ts
src/subdomains/supporting/payout/payout.module.ts
src/subdomains/supporting/payout/services/payout-bitcoin.service.ts
src/subdomains/supporting/payout/services/payout-monero.service.ts

[DEV-3736] Refactoring

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-job.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts

[DEV-3673] buyCryptoReturn update logic

---

src/subdomains/generic/kyc/controllers/kyc.controller.ts
src/subdomains/generic/kyc/dto/input/kyc-data.dto.ts
src/subdomains/generic/kyc/dto/output/kyc-info.dto.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/enums/kyc-step-name.enum.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts

[DEV-3730]&[DEV-3731]&[DEV-3732] kycStep operational activity

---

src/shared/services/process.service.ts
src/shared/utils/util.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-job.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/transaction/transaction-util.service.ts
src/subdomains/generic/kyc/controllers/kyc.controller.ts
src/subdomains/generic/kyc/dto/input/kyc-data.dto.ts
src/subdomains/generic/kyc/dto/output/kyc-info.dto.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/enums/kyc-step-name.enum.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/bank-tx/bank-tx-return/bank-tx-return.service.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/bank/bank-account/bank-account.service.ts
src/subdomains/supporting/log/dto/create-log.dto.ts
src/subdomains/supporting/log/log.repository.ts
src/subdomains/supporting/log/log.service.ts
src/subdomains/supporting/support-issue/dto/support-issue-dto.mapper.ts

[NOTASK]&[DEV-3744] update return type, supportIssue mapper fix, skip refund ibanCountry check

---

src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[NOTASK] cancel step when retrigger personalData

---

src/subdomains/supporting/log/log-job.service.ts

[NOTASK] financeLog add assetLog error log

---

src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/log/log.service.ts

[NOTASK] financeLog hotfix

---

src/shared/services/dfx-cron.service.ts

[NO-TASK] add context to cron job for logging

---

src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3751] fix ident bug

---

src/subdomains/core/monitoring/observers/user.observer.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/supporting/fiat-output/fiat-output.service.ts

[NOTASK]&[DEV-3751] remove riskState in observer, fix ident bug, fix fiatOutput date bug

---

src/integration/blockchain/ain/node/node.service.ts
src/integration/blockchain/monero/services/monero.service.ts
src/integration/blockchain/shared/services/crypto.service.ts
src/shared/utils/util.ts
src/subdomains/core/payment-link/entities/payment-quote.entity.ts
src/subdomains/core/payment-link/services/payment-link.service.ts

[DEV-3753] display transfer amounts

---

src/subdomains/supporting/pricing/domain/entities/price-rule.entity.ts
src/subdomains/supporting/pricing/pricing.module.ts
src/subdomains/supporting/pricing/services/integration/pricing-deuro.service.ts
src/subdomains/supporting/pricing/services/pricing.service.ts

[DEV-3761] DEPS pricing service

---

migration/1742927582173-AddBuyCryptoLiqPipeline.js
src/config/config.ts
src/subdomains/core/buy-crypto/process/entities/__tests__/buy-crypto.entity.spec.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/liquidity-management/adapters/actions/base/frankencoin-based.adapter.ts
src/subdomains/core/liquidity-management/adapters/actions/deuro.adapter.ts
src/subdomains/core/liquidity-management/adapters/actions/frankencoin.adapter.ts
src/subdomains/core/liquidity-management/adapters/actions/liquidity-pipeline.adapter.ts
src/subdomains/core/liquidity-management/controllers/pipeline.controller.ts
src/subdomains/core/liquidity-management/entities/liquidity-management-order.entity.ts
src/subdomains/core/liquidity-management/entities/liquidity-management-pipeline.entity.ts
src/subdomains/core/liquidity-management/services/liquidity-management.service.ts

[DEV-3541] add liqManagementPipeline in buyCrypto

---

src/integration/blockchain/deuro/deuro.service.ts
src/integration/blockchain/frankencoin/frankencoin.service.ts
src/integration/blockchain/shared/dto/frankencoin-based.dto.ts
src/integration/blockchain/shared/frankencoin/frankencoin-based.service.ts

[DEV-3765] dEURO TVL WFPS price

---

src/integration/blockchain/deuro/deuro.service.ts
src/integration/blockchain/frankencoin/frankencoin.service.ts
src/integration/blockchain/shared/dto/frankencoin-based.dto.ts
src/integration/blockchain/shared/frankencoin/frankencoin-based.service.ts
src/subdomains/supporting/pricing/services/integration/pricing-deuro.service.ts

[DEV-3765] dEURO TVL WFPS price, DEPS - USDT price

---

migration/1742992597290-LmOrderOutputAmount.js
src/subdomains/core/liquidity-management/adapters/actions/base/frankencoin-based.adapter.ts
src/subdomains/core/liquidity-management/adapters/actions/deuro.adapter.ts
src/subdomains/core/liquidity-management/adapters/actions/frankencoin.adapter.ts
src/subdomains/core/liquidity-management/entities/liquidity-management-order.entity.ts
src/subdomains/core/trading/services/trading.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts

[NOTASK] fix user update bug

---

src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/liquidity-management/adapters/actions/deuro.adapter.ts
src/subdomains/core/liquidity-management/enums/index.ts

[NOTASK] deactivate step filter

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts

[NOTASK] fix batch bug

---

src/shared/services/process.service.ts
src/subdomains/core/liquidity-management/services/liquidity-management.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/generic/user/models/organization/dto/organization.dto.ts
src/subdomains/generic/user/models/organization/organization.entity.ts
src/subdomains/generic/user/models/organization/organization.service.ts
src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
src/subdomains/generic/user/models/user-data/user-data-job.service.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/generic/user/models/user/user-job.service.ts
src/subdomains/generic/user/user.module.ts
src/subdomains/supporting/payment/entities/transaction.entity.ts
src/subdomains/supporting/payment/services/transaction-notification.service.ts

[NOTASK] fix userData update bug

---

src/integration/blockchain/monero/monero-client.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts
src/subdomains/supporting/payout/services/payout-monero.service.ts

[DEV-3769] Optional monero payment parameter

---

src/integration/blockchain/monero/monero-client.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts
src/subdomains/supporting/payout/services/payout-monero.service.ts

* [DEV-3769] Optional monero payment parameter
* [DEV-3769] changes after review
- Login/logout
- KYC page
[DEV-3769]: https://dfxswiss.atlassian.net/browse/DEV-3769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3769]: https://dfxswiss.atlassian.net/browse/DEV-3769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-3769] Optional monero payment parameter (#2051)

---

src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts

[DEV-3774] Cancel multi payments

---

infrastructure/bicep/dfx-api.bicep
infrastructure/bicep/parameters/dev.json
infrastructure/bicep/parameters/loc.json
infrastructure/bicep/parameters/prd.json
src/config/config.ts
src/integration/blockchain/deuro/deuro-client.ts
src/integration/blockchain/deuro/deuro.service.ts
src/integration/blockchain/deuro/dto/deuro.dto.ts
src/integration/blockchain/shared/evm/evm-client.ts

[DEV-3777] additional dEURO log info

---

src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3796] aml bug

---

src/subdomains/generic/kyc/services/integration/dilisense.service.ts
src/subdomains/generic/kyc/services/name-check.service.ts

[DEV-3638] dilisense upload nameCheck pdf

---

src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts

[DEV-3666] bankTx update job

---

src/integration/blockchain/deuro/deuro-client.ts
src/integration/blockchain/deuro/deuro.service.ts
src/integration/blockchain/deuro/dto/deuro.dto.ts
src/integration/blockchain/shared/frankencoin/frankencoin-based.service.ts

[DEV-3798] add stablecoin bridges to tvl fpr log

---

src/subdomains/core/aml/services/aml-helper.service.ts

Update aml-helper.service.ts set AML Rule 8 to 1'000 CHF

---

migration/1744028086488-AddFeeExcludedUserDatas.js
src/subdomains/supporting/payment/entities/fee.entity.ts

[DEV-3804] add fee excludedUserDatas

---

migration/1744028086488-AddFeeExcludedUserDatas.js
src/integration/blockchain/deuro/deuro-client.ts
src/integration/blockchain/deuro/deuro.service.ts
src/integration/blockchain/deuro/dto/deuro.dto.ts
src/integration/blockchain/shared/frankencoin/frankencoin-based.service.ts
src/shared/repositories/repository.factory.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-job.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
src/subdomains/core/history/dto/refund-internal.dto.ts
src/subdomains/core/liquidity-management/services/liquidity-management.service.ts
src/subdomains/core/monitoring/monitoring.module.ts
src/subdomains/core/monitoring/observers/liquidity.observer.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-job.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/core/trading/services/trading.service.ts
src/subdomains/generic/kyc/services/integration/dilisense.service.ts
src/subdomains/generic/kyc/services/name-check.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.controller.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/payment/entities/fee.entity.ts

[NOTASK]&[DEV-3671]&[DEV-3638] hex param check, chargeback logic, dilisense pdf nameCheck

---

src/shared/models/country/dto/country-dto.mapper.ts
src/shared/models/country/dto/country.dto.ts

[NOTASK] add country ibanAllowed

---

package-lock.json
package.json
src/config/config.ts
src/integration/blockchain/deuro/deuro-client.ts
src/integration/blockchain/deuro/deuro.service.ts
src/integration/blockchain/frankencoin/frankencoin-client.ts
src/integration/blockchain/frankencoin/frankencoin.service.ts
src/integration/blockchain/shared/frankencoin/frankencoin-based.service.ts
src/subdomains/core/liquidity-management/adapters/actions/base/frankencoin-based.adapter.ts
src/subdomains/core/liquidity-management/adapters/actions/deuro.adapter.ts

[DEV-3801] nDEPS to DEPS Wrapper

---

package-lock.json
package.json
src/config/config.ts
src/integration/blockchain/ain/node/node.service.ts
src/integration/blockchain/deuro/deuro-client.ts
src/integration/blockchain/deuro/deuro.service.ts
src/integration/blockchain/frankencoin/frankencoin-client.ts
src/integration/blockchain/frankencoin/frankencoin.service.ts
src/integration/blockchain/monero/services/monero.service.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/integration/blockchain/shared/frankencoin/frankencoin-based.service.ts
src/subdomains/core/liquidity-management/adapters/actions/base/frankencoin-based.adapter.ts
src/subdomains/core/liquidity-management/adapters/actions/deuro.adapter.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/core/trading/services/trading-order.service.ts

[DEV-3801] & [DEV-3802] & rollback payment request amount format

---

src/integration/blockchain/ain/node/node.service.ts
src/integration/blockchain/monero/services/monero.service.ts
src/shared/i18n/de/kyc.json
src/shared/i18n/en/kyc.json
src/shared/i18n/es/kyc.json
src/shared/i18n/fr/kyc.json
src/shared/i18n/it/kyc.json
src/shared/i18n/pt/kyc.json
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/generic/kyc/config/financial-questions.ts
src/subdomains/generic/kyc/services/integration/financial.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3305] & revert rollback payment request amount format

---

src/subdomains/generic/kyc/config/financial-questions.ts
src/subdomains/generic/kyc/services/integration/financial.service.ts

[DEV-3183] Add conditions logic

---

src/shared/i18n/de/kyc.json
src/shared/i18n/en/kyc.json
src/shared/i18n/es/kyc.json
src/shared/i18n/fr/kyc.json
src/shared/i18n/it/kyc.json
src/shared/i18n/pt/kyc.json
src/subdomains/generic/kyc/config/financial-questions.ts
src/subdomains/generic/kyc/services/integration/financial.service.ts

[DEV-3183] KYC conditions improvements

---

src/subdomains/core/payment-link/entities/payment-quote.entity.ts

[NO-TASK] Payment query parameters lowercase

---

migration/1744382196177-AddKycLogSynced.js
src/shared/services/process.service.ts
src/subdomains/generic/kyc/entities/kyc-file.entity.ts
src/subdomains/generic/kyc/entities/kyc-log.entity.ts
src/subdomains/generic/kyc/services/name-check.service.ts

[DEV-3806] sync nameCheck pdf

---

src/subdomains/generic/kyc/config/financial-questions.ts

[DEV-3183] Add employed_description to employed_management

---

infrastructure/bicep/container-apps/initial/modules/frontdoorWafPolicies.bicep
src/subdomains/supporting/pricing/services/integration/pricing-deuro.service.ts

[DEV-3805] Deactivate WAF rule 931130 [DEV-3833] USDC/DEPS price

---

src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts

[NOTASK] fix buyCrypto bug

---

src/subdomains/supporting/log/dto/create-log.dto.ts
src/subdomains/supporting/log/log.repository.ts
src/subdomains/supporting/log/log.service.ts

[NO-TASK] Delete all logs

---

src/subdomains/generic/kyc/services/kyc.service.ts

[NOTASK] fix doc view

---

migration/1740757860019-AddCustodyOrderStep.js
src/integration/blockchain/shared/evm/evm-client.ts
src/shared/i18n/de/kyc.json
src/shared/i18n/en/kyc.json
src/shared/i18n/es/kyc.json
src/shared/i18n/fr/kyc.json
src/shared/i18n/it/kyc.json
src/shared/i18n/pt/kyc.json
src/shared/services/process.service.ts
src/shared/utils/util.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
src/subdomains/core/buy-crypto/routes/swap/swap.service.ts
src/subdomains/core/custody/adapter/dfx-order-step.adapter.ts
src/subdomains/core/custody/config/order-config.ts
src/subdomains/core/custody/custody.module.ts
src/subdomains/core/custody/dto/input/create-custody-order.dto.ts
src/subdomains/core/custody/dto/output/create-custody-order-output.dto.ts
src/subdomains/core/custody/entities/custody-order-step.entity.ts
src/subdomains/core/custody/entities/custody-order.entity.ts
src/subdomains/core/custody/enums/custody.ts
src/subdomains/core/custody/repositories/custody-order.-step.repository.ts
src/subdomains/core/custody/services/custody-service.ts
src/subdomains/core/liquidity-management/adapters/actions/base/evm-l2-bridge.adapter.ts
src/subdomains/generic/kyc/config/financial-questions.ts
src/subdomains/generic/kyc/services/integration/dilisense.service.ts
src/subdomains/generic/kyc/services/integration/financial.service.ts
src/subdomains/generic/kyc/services/name-check.service.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts

[NOTASK]&[DEV-3842]&[DEV-3704] Custody logic, financialData key refactoring, nameCheck business refactoring

---

src/shared/repositories/repository.factory.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/monitoring/observers/payment.observer.ts

[NOTASK] fix payment observer, fix amlCheck users relation

---

src/integration/exchange/services/exchange.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts

[NOTASK] remove relation

---

src/integration/exchange/controllers/exchange.controller.ts
src/integration/exchange/services/exchange.service.ts
src/shared/utils/util.ts
src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
src/subdomains/core/custody/entities/custody-order.entity.ts
src/subdomains/core/custody/services/custody-order.service.ts
src/subdomains/core/history/services/history.service.ts
src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
src/subdomains/core/liquidity-management/adapters/balances/exchange.adapter.ts
src/subdomains/generic/user/models/account-merge/account-merge.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[NOTASK] Fixes & Refactoring 2

---

src/integration/blockchain/shared/services/crypto.service.ts
src/subdomains/core/referral/reward/services/ref-reward.service.ts
src/subdomains/supporting/fiat-payin/services/fiat-payin-sync.service.ts

[NOTASK]&[DEV-3874] fix cko sync, change ref reward evm asset

---

src/config/config.ts
src/integration/blockchain/deuro/deuro.service.ts
src/integration/blockchain/shared/frankencoin/frankencoin-based.service.ts

[DEV-3882] Fetch nDEPS price for DEPS

---

migration/1746166295428-AddAssetPrices.js
src/shared/models/asset/asset.entity.ts
src/subdomains/supporting/pricing/domain/entities/asset-price.entity.ts
src/subdomains/supporting/pricing/pricing.module.ts
src/subdomains/supporting/pricing/repositories/asset-price.repository.ts
src/subdomains/supporting/pricing/services/asset-prices.service.ts

[DEV-3873] Add AssetPrices for historical prices for assets

---

src/shared/i18n/de/invoice.json
src/shared/i18n/en/invoice.json
src/shared/i18n/fr/invoice.json
src/shared/i18n/it/invoice.json
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/supporting/payment/services/swiss-qr.service.ts

[DEV-3885] Invoice improvements

---

src/subdomains/supporting/pricing/services/asset-prices.service.ts

[DEV-3837] Round mean price and refactoring

---

src/subdomains/core/custody/controllers/custody.controller.ts
src/subdomains/core/custody/services/custody-order.service.ts
src/subdomains/core/custody/services/custody.service.ts

[NOTASK] Refactoring custodyBalance update

---

src/config/config.ts
src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/entities/payment-quote.entity.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/supporting/payin/services/payin.service.ts

[DEV-3880] Retry EVM tx failed payments

---

src/shared/utils/util.ts
src/subdomains/core/custody/controllers/custody.controller.ts
src/subdomains/core/custody/dto/output/custody-balance.dto.ts
src/subdomains/core/custody/services/custody.service.ts
src/subdomains/supporting/pricing/pricing.module.ts
src/subdomains/supporting/pricing/services/asset-prices.service.ts

[DEV-3873] Add custody history

---

src/config/config.ts
src/shared/utils/util.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/custody/controllers/custody.controller.ts
src/subdomains/core/custody/dto/output/custody-balance.dto.ts
src/subdomains/core/custody/services/custody-order.service.ts
src/subdomains/core/custody/services/custody.service.ts
src/subdomains/core/history/__tests__/transaction-helper.spec.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/dto/payment-request.mapper.ts
src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/entities/payment-quote.entity.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/supporting/bank-tx/bank-tx/__mocks__/bank-tx.entity.mock.ts
src/subdomains/supporting/bank-tx/bank-tx/entities/bank-tx.entity.ts
src/subdomains/supporting/payin/services/payin.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts
src/subdomains/supporting/pricing/pricing.module.ts
src/subdomains/supporting/pricing/services/asset-prices.service.ts
src/subdomains/supporting/support-issue/entities/limit-request.entity.ts
src/subdomains/supporting/support-issue/services/limit-request.service.ts

[NOTASK] LimitRequest Refactoring

---

src/shared/i18n/de/invoice.json
src/shared/i18n/en/invoice.json
src/shared/i18n/fr/invoice.json
src/shared/i18n/it/invoice.json
src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
src/subdomains/core/buy-crypto/routes/buy/dto/invoice.dto.ts
src/subdomains/core/buy-crypto/routes/buy/dto/pdf.dto.ts
src/subdomains/core/buy-crypto/routes/buy/dto/receipt.dto.ts
src/subdomains/core/history/__tests__/transaction-helper.spec.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/supporting/payment/dto/transaction-helper/tx-statement-details.dto.ts
src/subdomains/supporting/payment/entities/transaction.entity.ts
src/subdomains/supporting/payment/services/swiss-qr.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3884] Transaction receipt endpoint

---

src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/services/payment-link.service.ts

[DEV-3899] move id & exteranalId to PaymentLinkRequestDto

---

src/shared/utils/util.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/payment-link/enums/index.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/bank-tx/bank-tx-repeat/bank-tx-repeat.service.ts
src/subdomains/supporting/bank-tx/bank-tx-return/bank-tx-return.service.ts
src/subdomains/supporting/bank-tx/bank-tx/services/bank-tx.service.ts
src/subdomains/supporting/fiat-payin/services/fiat-payin-sync.service.ts
src/subdomains/supporting/notification/factories/mail.factory.ts
src/subdomains/supporting/support-issue/services/limit-request.service.ts

[DEV-3875] Fix redundant data storage

---

src/subdomains/supporting/notification/factories/mail.factory.ts

[DEV-3875] Array fix

---

src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3920] dfxApproval refactoring

---

migration/1746783044276-RemoveKycLogSync.js
src/shared/services/process.service.ts
src/subdomains/generic/kyc/entities/kyc-log.entity.ts
src/subdomains/generic/kyc/services/name-check.service.ts

[DEV-3918] remove nameCheck pdf sync

---

migration/1746739483764-AddUserDataModerator.js
migration/1746783044276-RemoveKycLogSync.js
src/config/config.ts
src/shared/services/process.service.ts
src/subdomains/core/custody/dto/input/create-custody-account.dto.ts
src/subdomains/core/custody/services/custody.service.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/generic/kyc/entities/kyc-log.entity.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/kyc/services/name-check.service.ts
src/subdomains/generic/user/models/auth/auth.service.ts
src/subdomains/generic/user/models/auth/dto/auth-credentials.dto.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/generic/user/models/user/user.service.ts

* [DEV-3920] dfxApproval refactoring
* [DEV-3920] Refactoring
- Login/logout
- KYC page
[DEV-3920]: https://dfxswiss.atlassian.net/browse/DEV-3920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3920]: https://dfxswiss.atlassian.net/browse/DEV-3920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-3920] dfxApproval refactoring (#2111)

---

src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.controller.ts

[NOTASK] end steps with dfxApproval

---

migration/1747037678344-AddKycFileSubType.js
src/shared/services/process.service.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/kyc/entities/kyc-file.entity.ts
src/subdomains/generic/kyc/services/integration/kyc-document.service.ts
src/subdomains/generic/kyc/services/kyc-file.service.ts
src/subdomains/generic/user/models/user-data/dto/upload-file.dto.ts
src/subdomains/generic/user/models/user-data/user-data.controller.ts

[DEV-3965] kycFile subType
- Login/logout
- KYC page

[DEV-3935] kycFile subType

---

src/config/config.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3902] Dilisense PDF

---

src/config/config.ts
src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/kyc/services/kyc-file.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3902]&[NOTASK] dilisense pdf, subFileType DfxNameCheck

---

src/subdomains/generic/kyc/services/kyc-file.service.ts

[NOTASK] fix sync

---

src/subdomains/generic/user/models/user-data/dto/upload-file.dto.ts

[NOTASK] fix doc upload

---

src/integration/exchange/services/exchange.service.ts
src/shared/utils/util.ts
src/subdomains/core/history/mappers/transaction-dto.mapper.ts
src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
src/subdomains/core/liquidity-management/adapters/actions/base/frankencoin-based.adapter.ts
src/subdomains/core/liquidity-management/adapters/balances/exchange.adapter.ts
src/subdomains/generic/kyc/dto/ident.dto.ts
src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts
src/subdomains/generic/kyc/services/kyc-file.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/kyc/services/name-check.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/supporting/payin/strategies/send/impl/base/evm-coin.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/base/evm.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/base/evm.token.strategy.ts
src/subdomains/supporting/payment/services/transaction-request.service.ts
src/subdomains/supporting/payment/services/transaction.service.ts
src/subdomains/supporting/support-issue/services/support-issue.service.ts

[NOTASK] add fileSubType in NameCheck

---

src/integration/blockchain/shared/evm/evm-client.ts
src/integration/blockchain/shared/evm/evm.util.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts

[DEV-3826] EVM payment hex fee check

---

src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/payment-recipient-mapper.ts
src/subdomains/core/payment-link/dto/payment-recipient.dto.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/core/route/route.controller.ts
src/subdomains/core/sell-crypto/route/sell.controller.ts
src/subdomains/core/sell-crypto/route/sell.service.ts

[DEV-3847] add payment route endpoint

---

src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/entities/payment-quote.entity.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts

[NO-TASK] Fixed EVM TX payments

---

src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts

[NO-TASK] Improved TX ID payments

---

src/shared/models/asset/asset.entity.ts
src/shared/models/asset/asset.service.ts
src/subdomains/core/custody/controllers/custody.controller.ts
src/subdomains/core/custody/dto/input/create-custody-order.dto.ts
src/subdomains/core/custody/dto/input/get-custody-info.dto.ts
src/subdomains/core/custody/dto/output/custody-balance.dto.ts
src/subdomains/core/custody/dto/output/custody-order-response.dto.ts
src/subdomains/core/custody/dto/output/custody-order.dto.ts
src/subdomains/core/custody/mappers/custody-asset-balance-dto.mapper.ts
src/subdomains/core/custody/mappers/custody-order-response-dto.mapper.ts
src/subdomains/core/custody/mappers/get-custody-order-dto.mapper.ts
src/subdomains/core/custody/services/custody-order.service.ts
src/subdomains/core/custody/services/custody.service.ts

* [DEV-3841] dfx safe step 2
* [DEV-3841] Add balance in all possible currencies
* [DEV-3841] remove unused code
* [DEV-3841] Refactoring
* [DEV-3841] Merge develop conflicts
* [DEV-3841] Refactoring 2
* [DEV-3841] Refactoring 3
* [DEV-3841] Refactoring 4
- Login/logout
- KYC page
[DEV-3841]: https://dfxswiss.atlassian.net/browse/DEV-3841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3841]: https://dfxswiss.atlassian.net/browse/DEV-3841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-3841]: …

[DEV-3841] dfx safe step 2

---

src/shared/models/asset/dto/update-asset.dto.ts

[DEV-3964] gs update asset buyable, sellable

---

src/config/config.ts

add Taproot Asset on Bitcoin OnChain

---

src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
src/subdomains/generic/user/models/bank-data/bank-data.repository.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/supporting/bank/bank-account/bank-account.controller.ts
src/subdomains/supporting/bank/bank-account/dto/bank-account.dto.ts
src/subdomains/supporting/bank/bank-account/dto/update-bank-account.dto.ts

[DEV-3384] add default column to BankData

---

src/integration/blockchain/shared/dto/blockchain-token-balance.dto.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/subdomains/supporting/log/dto/log.dto.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-3966] financeLog custom address balances

---

migration/1747660336767-AddBankDataDefault.js
src/integration/blockchain/shared/dto/blockchain-token-balance.dto.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/integration/exchange/services/exchange.service.ts
src/shared/models/asset/dto/update-asset.dto.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/core/trading/services/trading.service.ts
src/subdomains/generic/kyc/dto/kyc-file.dto.ts
src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
src/subdomains/generic/user/models/bank-data/bank-data.repository.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/supporting/bank/bank-account/bank-account.controller.ts
src/subdomains/supporting/bank/bank-account/dto/bank-account.dto.ts
src/subdomains/supporting/bank/bank-account/dto/update-bank-account.dto.ts
src/subdomains/supporting/log/dto/log.dto.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-3847]&[DEV-3384]&[DEV-3954]&[DEV-3970]&[NOTASK] taproot Asset, Improvements, bankData default col

---

src/subdomains/supporting/log/log-job.service.ts

[NOTASK] fix financeLog bug

---

src/shared/services/process.service.ts
src/subdomains/core/monitoring/observers/liquidity.observer.ts
src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/bank-tx/bank-tx/entities/bank-tx.entity.ts
src/subdomains/supporting/payment/entities/special-external-account.entity.ts
src/subdomains/supporting/payment/services/special-external-account.service.ts

[NOTASK] MultiAccount improvement

---

src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3949] fix organization bug

---

src/subdomains/core/trading/services/trading-order.service.ts
src/subdomains/supporting/bank-tx/bank-tx/entities/bank-tx.entity.ts

[NOTASK] fix, trading mail refactoring

---

src/subdomains/core/payment-link/dto/update-payment-link.dto.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data-job.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/log/log-job.service.ts

[NOTASK] DfxApprovalCheck with ident complete

---

migration/1748259486840-AddCountryAmlRule.js
src/shared/models/country/country.entity.ts
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/enums/aml-rule.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-3994] country amlRule

---

src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[NOTASK] fix amlRule bug 1

---

migration/1748340316200-AddPaymentLinkStoreInfoCols.js
src/subdomains/core/payment-link/dto/update-payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts

[DEV-4002] add paymentLink storeInfo cols

---

src/integration/sift/dto/sift.dto.ts
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/aml/enums/aml-reason.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[DEV-4004] amlReason BankTxNeeded

---

src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-3938] Get video during resync

---

src/config/config.ts
src/subdomains/supporting/payin/services/payin-solana.service.ts
src/subdomains/supporting/payin/strategies/send/impl/base/solana.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/solana-coin.strategy.ts
src/subdomains/supporting/payin/strategies/send/impl/solana-token.strategy.ts

[DEV-3716] Solana fixes

---

rest-client/dfx-api.http
src/integration/c2b-payment-link/services/binance-pay.service.ts
src/subdomains/supporting/notification/templates/user-v2.hbs

[NOTASK] Improve new userMail

---

src/integration/c2b-payment-link/dto/binance.dto.ts
src/integration/c2b-payment-link/services/binance-pay.service.ts

[NO-TASK]: Fix terminal type

---

src/integration/c2b-payment-link/services/binance-pay.service.ts

[NO-TASK]: Fix Binance signature verification

---

src/integration/blockchain/solana/solana-client.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/supporting/payin/strategies/register/impl/solana.strategy.ts

Added log for invalid min deficits / adapt creation of solana coin tx / address filter for webhook handling

---

migration/1749049390753-PaymentNote.js
src/integration/tatum/controllers/tatum.controller.ts
src/integration/tatum/dto/tatum-webhook-payload.mapper.ts
src/shared/services/payment-info.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/buy-crypto/routes/swap/swap.entity.ts
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/create-invoice-payment.dto.ts
src/subdomains/core/payment-link/dto/create-payment-link-payment.dto.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-link-payment.entity.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/notification/templates/user-v2.hbs
src/subdomains/supporting/payin/strategies/register/impl/solana.strategy.ts

[DEV-3716] Solana webhook counter addresses [DEV-3169] Fixed min deficit 2 [DEV-4048] Create separate ChangesLog

---

src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/core/sell-crypto/route/sell.service.ts

[DEV-4025] extend stickers endpoint to support payment link ids

---

src/integration/alchemy/services/alchemy-webhook.service.ts

[NO-TASK] Change alchemy webhook setup

---

src/integration/c2b-payment-link/services/binance-pay.service.ts

[NO-TASK]: Look for merchant id in all configs available

---

src/subdomains/core/payment-link/controllers/payment-link.controller.ts

[NO-TASK]: Restore types

---

src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts

[NO-TASK]: Clean secrets from DTOs

---

migration/1750087655189-AddLimitRequestAcceptedLimit.js
src/subdomains/supporting/support-issue/dto/update-limit-request.dto.ts
src/subdomains/supporting/support-issue/entities/limit-request.entity.ts

[DEV-4072] limitRequest acceptedLimit

---

src/integration/lightning/services/lightning.service.ts

[NO-TASK] Caching the Lightning node pub keys

---

migration/1750404224308-LiquidityLimit.js
src/shared/models/asset/asset.entity.ts
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/liquidity-management/entities/liquidity-management-rule.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/core/trading/services/trading-order.service.ts

[DEV-4075] Liquidity limit

---

src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/notification/services/notification-job.service.ts

[NOTASK] deactivate assetLog monitoring in financeLog

---

src/subdomains/supporting/log/log-job.service.ts

[DEV-4093] fix financeLog negative value bug

---

src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/services/payment-link.service.ts

[NO-TASK]: Simplified support for PoS Payment Link

---

src/integration/c2b-payment-link/dto/binance.dto.ts
src/integration/c2b-payment-link/services/binance-pay.service.ts
src/integration/c2b-payment-link/share/PaymentStatus.ts
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts

* [NO-TASK]: Binance pay native integration
* Update DTO
- Login/logout
- KYC page

[NO-TASK]: Binance pay native integration (#2219)

---

src/subdomains/supporting/fiat-output/fiat-output-job.service.ts

[NOTASK] fiatOutput improvement

---

src/config/config.ts
src/integration/exchange/services/exchange.service.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/generic/kyc/dto/kyc-error.enum.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc-file.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[DEV-3998]&[NOTASK] remove subType sync code, move prefix in config, fix kyc process deactivated userData

---

src/subdomains/core/custody/services/custody-job.service.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts

[DEV-4109] kyc step order and relation fix dfx safe

---

src/subdomains/core/custody/services/custody-job.service.ts
src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/supporting/payin/strategies/send/impl/base/evm-coin.strategy.ts

[DEV-4109] kyc step order & pay in fix & swap fix dfx safe

---

src/subdomains/supporting/bank-tx/bank-tx/entities/bank-tx.entity.ts
src/subdomains/supporting/payment/__mocks__/internal-fee.dto.mock.ts
src/subdomains/supporting/payment/dto/fee.dto.ts
src/subdomains/supporting/payment/entities/fee.entity.ts
src/subdomains/supporting/payment/services/fee.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-4111] bank refund fee

---

src/subdomains/core/custody/services/custody-order.service.ts

[DEV-4101] Remove order completion

---

src/config/config.ts
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/liquidity-management/entities/liquidity-management-rule.entity.ts
src/subdomains/core/liquidity-management/liquidity-management.module.ts
src/subdomains/core/liquidity-management/services/liquidity-management.service.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts

[NOTASK]&[DEV-4124] fix search onHold steps, weekly limit, LM transmission min, kycRestart bug, change aml failed to GS

---

src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/history/mappers/transaction-dto.mapper.ts
src/subdomains/supporting/payment/services/transaction.service.ts

[DEV-4107] show refunded unassigned tx

---

src/integration/binance-pay/dto/binance.dto.ts
src/integration/binance-pay/services/binance-pay.service.ts

[NO-TASK]: Expiration time for order based on quote

---

src/subdomains/core/payment-link/services/payment-cron.service.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts

[DEV-4130] Expiration timers

---

src/integration/binance-pay/services/binance-pay.service.ts
src/shared/services/process.service.ts

[DEV-4149]: Improve BinancePay certificates cache

---

src/integration/exchange/enums/exchange.enum.ts
src/subdomains/core/liquidity-management/factories/liquidity-balance-integration.factory.ts

[NO-TASK] Fixed balance adapter

---

src/subdomains/core/payment-link/services/payment-link-payment.service.ts

[NO-TASK]: More performant DB usage for Single PL

---

src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts

[DEV-4157] remove bankData Pass comment

---

rest-client/dfx-api.http
src/integration/binance-pay/services/binance-pay.service.ts
src/shared/utils/util.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/fiat-output/fiat-output-job.service.ts
src/subdomains/supporting/fiat-output/fiat-output.entity.ts

[DEV-4136]&[NOTASK] Solana payment fix, improvements, fiatOutput batchAmount round

---

src/subdomains/generic/gs/gs.service.ts

[DEV-4158] gs endpoint improvement

---

src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts

[DEV-4013] Added scan timout

---

src/integration/blockchain/tron/services/tron.service.ts
src/integration/blockchain/tron/tron-client.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-4056] Tron fixes

---

src/integration/blockchain/tron/tron-client.ts
src/subdomains/core/aml/enums/aml-rule.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/payment-link/controllers/c2b-payment-link.controller.ts
src/subdomains/supporting/log/log-job.service.ts
src/subdomains/supporting/log/log.entity.ts
src/subdomains/supporting/log/log.service.ts

[DEV-4190]: Return error code on webhook errors (#2297)

---

infrastructure/bicep/dfx-api.bicep
package-lock.json
package.json
src/config/config.ts
src/integration/blockchain/bitcoin/services/__tests__/crypto.service.spec.ts
src/integration/blockchain/blockchain.module.ts
src/integration/blockchain/shared/enums/blockchain.enum.ts
src/integration/blockchain/shared/services/crypto.service.ts
src/integration/blockchain/shared/util/blockchain.util.ts
src/integration/blockchain/zano/services/zano.service.ts
src/integration/blockchain/zano/zano-client.ts
src/integration/blockchain/zano/zano.module.ts
src/integration/exchange/services/__tests__/exchange.test.ts
src/integration/exchange/services/binance.service.ts
src/integration/exchange/services/bitstamp.service.ts
src/integration/exchange/services/kraken.service.ts
src/integration/exchange/services/kucoin.service.ts
src/integration/exchange/services/mexc.service.ts
src/integration/exchange/services/xt.service.ts
src/subdomains/core/referral/reward/services/ref-reward.service.ts
src/subdomains/generic/user/models/user/user.entity.ts

[DEV-4176] Login with Zano

---

src/subdomains/core/payment-link/controllers/c2b-payment-link.controller.ts

[NO-TASK]: Kucoin webhook url amend

---

src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/referral/reward/dto/create-ref-reward.dto.ts
src/subdomains/core/referral/reward/ref-reward.controller.ts
src/subdomains/core/referral/reward/services/ref-reward.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
src/subdomains/supporting/payment/entities/transaction.entity.ts
src/subdomains/supporting/payment/services/transaction.service.ts
src/subdomains/supporting/pricing/services/fiat-prices.service.ts

[DEV-4184] manual ref payout

---

migration/1752912757559-AddFiatIbanCountryConfig.js
src/shared/models/fiat/dto/fiat-dto.mapper.ts
src/shared/models/fiat/dto/fiat.dto.ts
src/shared/models/fiat/fiat.controller.ts
src/shared/models/fiat/fiat.entity.ts
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/supporting/payment/dto/transaction-helper/quote-error.enum.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-4160] fiat ibanCountryConfig

---

src/config/config.ts

add Ark to DFX

---

src/subdomains/core/payment-link/dto/payment-request.mapper.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts

implementate method=ark

---

src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts

Remove pos completion

---

src/subdomains/generic/kyc/controllers/kyc-admin.controller.ts
src/subdomains/generic/user/models/user-data/user-data.controller.ts

[DEV-4227] support block userData kycStatus

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
src/subdomains/core/sell-crypto/process/__mocks__/buy-fiat.entity.mock.ts
src/subdomains/supporting/fiat-output/fiat-output-job.service.ts
src/subdomains/supporting/fiat-output/fiat-output.entity.ts

[DEV-4217] emergency payout stop

---

migration/1754311749671-PaymentLinkConfigImprovement.js
src/integration/binance-pay/dto/binance.dto.ts
src/integration/binance-pay/services/binance-pay.service.ts
src/shared/services/process.service.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/services/payment-cron.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/generic/kyc/dto/input/kyc-data.dto.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-4121] Added BPay info to payment KYC step

---

migration/1754407172145-ChangePaymentLinkComment.js
src/subdomains/core/payment-link/entities/payment-link.entity.ts

[DEV-4266] paymentLink comment length

---

src/integration/exchange/services/exchange.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/generic/kyc/dto/input/kyc-data.dto.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-4271] PL public name

---

src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/assign-payment-link.dto.ts
src/subdomains/core/payment-link/enums/index.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/core/sell-crypto/route/sell.service.ts

[DEV-4273] Added PL assign logic

---

src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
src/subdomains/core/buy-crypto/routes/swap/swap.service.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/generic/gs/dto/support-data.dto.ts
src/subdomains/generic/gs/gs.service.ts

[DEV-4213] supportTool buy

---

migration/1754646380762-KycFileValid.js
src/subdomains/generic/kyc/entities/kyc-file.entity.ts
src/subdomains/generic/kyc/services/integration/kyc-document.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/kyc/services/name-check.service.ts
src/subdomains/generic/user/models/kyc/kyc.service.ts

[DEV-4263] KYC file valid

---

migration/1754646380762-KycFileValid.js
src/integration/exchange/services/exchange.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
src/subdomains/core/buy-crypto/routes/swap/swap.service.ts
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/dto/payment-link-recipient.dto.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/core/sell-crypto/route/sell.service.ts
src/subdomains/generic/gs/dto/support-data.dto.ts
src/subdomains/generic/gs/gs.service.ts
src/subdomains/generic/kyc/dto/input/kyc-data.dto.ts
src/subdomains/generic/kyc/entities/kyc-file.entity.ts
src/subdomains/generic/kyc/services/integration/kyc-document.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/generic/kyc/services/name-check.service.ts
src/subdomains/generic/user/models/kyc/kyc.service.ts

[DEV-4213] supportTool buy [DEV-4263] KYC file valid

---

src/integration/exchange/services/mexc.service.ts
src/subdomains/core/liquidity-management/adapters/actions/mexc.adapter.ts
src/subdomains/core/liquidity-management/enums/index.ts
src/subdomains/core/liquidity-management/factories/liquidity-action-integration.factory.ts
src/subdomains/core/liquidity-management/liquidity-management.module.ts

[DEV-4286] LM MEXC Adapter

---

src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/generic/user/models/user-data/user-data-notification.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/notification/enums/index.ts
src/subdomains/supporting/notification/factories/mail.factory.ts

[DEV-4210] deactivation mail

---

migration/1755011369141-PriceAssetDisplayNames.js
src/subdomains/supporting/pricing/domain/entities/price-rule.entity.ts
src/subdomains/supporting/pricing/services/integration/pricing-constant.service.ts
src/subdomains/supporting/pricing/services/integration/pricing-dex.service.ts
src/subdomains/supporting/pricing/services/integration/pricing-provider.ts

[NO-TASK] Improved price asset naming

---

migration/1754924055973-AddWalletExceptAmlRules.js
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/generic/user/models/wallet/wallet.entity.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-4275] wallet exceptAmlRules

---

src/subdomains/core/liquidity-management/adapters/actions/xt.adapter.ts
src/subdomains/core/liquidity-management/enums/index.ts
src/subdomains/core/liquidity-management/factories/liquidity-action-integration.factory.ts

[DEV-4296] xt adapter

---

src/integration/blockchain/shared/services/crypto.service.ts
src/integration/blockchain/tron/services/tron.service.ts
src/subdomains/core/payment-link/dto/payment-request.mapper.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-link-fee.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/supporting/payin/strategies/send/impl/base/tron.strategy.ts

[DEV-4193] Tron payments

---

src/integration/blockchain/shared/enums/blockchain.enum.ts
src/integration/blockchain/shared/services/crypto.service.ts
src/integration/blockchain/tron/services/tron.service.ts
src/subdomains/core/aml/services/aml.service.ts
src/subdomains/core/payment-link/dto/payment-request.mapper.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-link-fee.service.ts
src/subdomains/core/payment-link/services/payment-quote.service.ts
src/subdomains/supporting/payin/strategies/send/impl/base/tron.strategy.ts

[NOTASK] Refactoring bicCountryCheck

---

src/integration/kucoin-pay/kucoin-pay.service.ts

[NO-TASK]: Fix supported Kucoin order types

---

src/subdomains/core/aml/enums/aml-rule.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-4324] amlRule skip amlCheck for dev

---

src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/supporting/payment/dto/transaction-helper/quote-error.enum.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[DEV-4297] new transaction error

---

src/integration/blockchain/shared/evm/evm-client.ts
src/integration/exchange/services/exchange.service.ts
src/subdomains/core/liquidity-management/adapters/actions/dfx-dex.adapter.ts
src/subdomains/supporting/notification/services/notification-job.service.ts

[NO-TASK] Fixed gas limit for coin TX

---

src/config/bank-holiday.config.ts
src/integration/exchange/services/exchange.service.ts
src/subdomains/core/monitoring/observers/payment.observer.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/supporting/fiat-output/fiat-output-job.service.ts
src/subdomains/supporting/fiat-output/fiat-output.entity.ts

[DEV-4284]&[DEV-4332]&[DEV-4331]&[NOTASK] bank holidays, daily output stop, fix fiatOutput bug, Improvements

---

README.md
src/subdomains/core/payment-link/controllers/payment-link.controller.ts
src/subdomains/core/payment-link/dto/payment-link-config.dto.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/dto/payment-link.dto.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/supporting/fiat-output/fiat-output.entity.ts

[NOTASK] Fix, Improvements

---

src/integration/blockchain/shared/enums/blockchain.enum.ts
src/integration/blockchain/shared/evm/evm-decimals.service.ts
src/integration/blockchain/shared/services/crypto.service.ts
src/integration/blockchain/shared/util/blockchain.util.ts
src/subdomains/core/payment-link/dto/payment-link-config.dto.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/services/payment-link-fee.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/supporting/address-pool/deposit/deposit.service.ts

Hide test chains on PRD

---

src/integration/kucoin-pay/kucoin-pay.service.ts

- Login/logout
- KYC page
Depends on: https://github.com/DFXswiss/services/pull/703

[NO-TASK]: Kucoin return urls

---

src/integration/sift/dto/sift.dto.ts
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/shared/utils/util.ts
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/enums/aml-reason.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-notification.service.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[DEV-4346] manual check phone

---

src/config/bank-holiday.config.ts
src/integration/alchemy/services/alchemy-webhook.service.ts
src/integration/blockchain/shared/exceptions/signature.exception.ts
src/integration/blockchain/shared/services/crypto.service.ts
src/integration/kucoin-pay/kucoin-pay.service.ts
src/integration/sift/dto/sift.dto.ts
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/shared/models/setting/dto/info-banner.dto.ts
src/shared/models/setting/setting.controller.ts
src/shared/utils/util.ts
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/enums/aml-reason.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-notification.service.ts
src/subdomains/supporting/bank-tx/bank-tx-return/bank-tx-return.service.ts
src/subdomains/supporting/payin/strategies/send/impl/base/evm-coin.strategy.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[NOTASK]&[DEV-4341] Improvements, fixes, bank holiday banner

---

infrastructure/bicep/container-groups/README.md
infrastructure/bicep/container-groups/deploy.sh
infrastructure/bicep/container-groups/main.bicep
infrastructure/bicep/container-groups/modules/containerGroup.bicep
infrastructure/bicep/container-groups/modules/storage.bicep
infrastructure/bicep/container-groups/parameters/dev-hb-deps-btc.json
infrastructure/bicep/container-groups/parameters/dev-hb-deps-usdt.json
infrastructure/bicep/container-groups/parameters/dev-hb-deuro-btc.json
infrastructure/bicep/container-groups/parameters/dev-hb-deuro-usdt.json

[DEV-4208] Hummingbot Azure configuration

---

src/subdomains/core/aml/services/aml-helper.service.ts

Remove entity.userData.status !== UserDataStatus.ACTIVE &&

---

infrastructure/bicep/container-groups/parameters/dev-hb-deps-btc.json
infrastructure/bicep/container-groups/parameters/dev-hb-deps-usdt.json
infrastructure/bicep/container-groups/parameters/dev-hb-deuro-btc.json
infrastructure/bicep/container-groups/parameters/dev-hb-deuro-usdt.json
src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-notification.service.ts

[DEV-4208]&[NOTASK] Bot conf change, fix pending mail

---

src/config/config.ts
src/integration/blockchain/base/base-client.ts
src/integration/blockchain/citrea-testnet/citrea-testnet-client.ts
src/integration/blockchain/optimism/optimism-client.ts
src/integration/blockchain/shared/evm/evm-client.ts
src/integration/blockchain/solana/services/solana.service.ts
src/integration/blockchain/solana/solana-client.ts
src/integration/blockchain/tron/services/tron.service.ts
src/integration/blockchain/tron/tron-client.ts
src/shared/services/process.service.ts
src/subdomains/core/payment-link/payment-link-payment.module.ts
src/subdomains/core/payment-link/services/payment-activation.service.ts
src/subdomains/core/payment-link/services/payment-balance.service.ts
src/subdomains/core/payment-link/services/payment-cron.service.ts
src/subdomains/core/transaction/transaction-util.service.ts
src/subdomains/generic/gs/gs-evm.service.ts
src/subdomains/supporting/address-pool/deposit/deposit.service.ts
src/subdomains/supporting/dex/services/base/dex-evm.service.ts
src/subdomains/supporting/log/__tests__/log-job.service.spec.ts
src/subdomains/supporting/log/log-job.module.ts
src/subdomains/supporting/log/log-job.service.ts

[DEV-4327] Payment deposit forwarding

---

migration/1756201286863-Recalls.js
src/subdomains/supporting/recall/recall.controller.ts
src/subdomains/supporting/recall/recall.dto.ts
src/subdomains/supporting/recall/recall.entity.ts
src/subdomains/supporting/recall/recall.module.ts
src/subdomains/supporting/recall/recall.repository.ts
src/subdomains/supporting/recall/recall.service.ts
src/subdomains/supporting/supporting.module.ts

[DEV-4235] Recalls

---

src/subdomains/core/payment-link/services/payment-link.service.ts
src/subdomains/generic/forwarding/controllers/lnurlp-forward.controller.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts

[NO-TASK]: Public link activation endpoint

---

src/shared/services/process.service.ts
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts

[DEV-4351] recheck amlReasons

---

src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/supporting/log/log-job.service.ts

[NOTASK] fix nationality missing manual approve bug

---

src/integration/sift/dto/sift.dto.ts
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/enums/aml-reason.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/generic/user/models/account-merge/account-merge.service.ts
src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
src/subdomains/generic/user/models/bank-data/bank-data.service.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[DEV-4359] bankData mergeExpired

---

src/subdomains/generic/kyc/enums/kyc.enum.ts
src/subdomains/generic/kyc/services/kyc-admin.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-4338] fix residencePermit bug

---

src/subdomains/generic/kyc/controllers/kyc.controller.ts
src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-4362] Improved SumSub webhook handling

---

src/integration/exchange/services/mexc.service.ts
src/shared/auth/jwt-payload.interface.ts
src/shared/auth/user-active.guard.ts
src/subdomains/core/liquidity-management/adapters/balances/bank.adapter.ts
src/subdomains/core/liquidity-management/adapters/balances/blockchain.adapter.ts
src/subdomains/core/liquidity-management/adapters/balances/exchange.adapter.ts
src/subdomains/core/liquidity-management/interfaces/index.ts
src/subdomains/core/liquidity-management/services/liquidity-management-balance.service.ts
src/subdomains/core/liquidity-management/services/liquidity-management.service.ts
src/subdomains/generic/user/models/auth/auth.service.ts
src/subdomains/supporting/dex/services/dex.service.ts
src/subdomains/supporting/fiat-output/fiat-output-job.service.ts

[DEV-4365] MEXC XMR [DEV-4343] add riskStatus to ActiveGuard

---

migration/1757436051757-AddBankTxBankReleaseDate.js
src/integration/sift/dto/sift.dto.ts
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/enums/aml-reason.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/supporting/bank-tx/bank-tx/dto/update-bank-tx.dto.ts
src/subdomains/supporting/bank-tx/bank-tx/entities/bank-tx.entity.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[DEV-4368] bankReleaseDate

---

migration/1757436051757-AddBankTxBankReleaseDate.js
src/integration/sift/dto/sift.dto.ts
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/enums/aml-reason.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
src/subdomains/core/history/controllers/transaction.controller.ts
src/subdomains/core/sell-crypto/process/services/buy-fiat-registration.service.ts
src/subdomains/supporting/bank-tx/bank-tx/dto/update-bank-tx.dto.ts
src/subdomains/supporting/bank-tx/bank-tx/entities/bank-tx.entity.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts
src/subdomains/supporting/payment/services/transaction-helper.ts

[NOTASK] add refund log

---

src/subdomains/core/custody/config/order-config.ts
src/subdomains/core/custody/dto/input/get-custody-info.dto.ts
src/subdomains/core/custody/mappers/get-custody-order-dto.mapper.ts
src/subdomains/core/custody/services/custody-order.service.ts

[DEV-4370] Add send function to dfx safe

---

src/subdomains/supporting/payment/services/transaction-request.service.ts

[NO-TASK] Add relation user from custody order

---

infrastructure/bicep/container-apps/apps/parameters/prd-n8n.json
src/subdomains/generic/kyc/dto/ident-result-data.dto.ts
src/subdomains/generic/kyc/dto/input/kyc-data.dto.ts
src/subdomains/generic/kyc/dto/manual-ident-result.dto.ts
src/subdomains/generic/kyc/dto/sum-sub.dto.ts
src/subdomains/generic/kyc/entities/kyc-step.entity.ts
src/subdomains/generic/kyc/services/integration/sum-sub.service.ts
src/subdomains/generic/kyc/services/kyc.service.ts

[DEV-4391] Fixed ident document type

---

migration/1758115917470-AddUserDataIpRiskPhoneIpCheckData.js
src/integration/sift/dto/sift.dto.ts
src/shared/i18n/de/mail.json
src/shared/i18n/en/mail.json
src/shared/i18n/es/mail.json
src/shared/i18n/fr/mail.json
src/shared/i18n/it/mail.json
src/shared/i18n/pt/mail.json
src/shared/models/ip-log/ip-log.service.ts
src/shared/models/setting/dto/ip-blacklist.dto.ts
src/shared/models/setting/setting.controller.ts
src/shared/models/setting/setting.repository.ts
src/shared/models/setting/setting.service.ts
src/subdomains/core/aml/enums/aml-error.enum.ts
src/subdomains/core/aml/enums/aml-reason.enum.ts
src/subdomains/core/aml/services/aml-helper.service.ts
src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
src/subdomains/generic/kyc/controllers/kyc-admin.controller.ts
src/subdomains/generic/user/models/auth/auth.service.ts
src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
src/subdomains/generic/user/models/user-data/user-data.entity.ts
src/subdomains/generic/user/models/user-data/user-data.service.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[DEV-4389] ip block phone call amlReason

---

src/shared/models/ip-log/ip-log.service.ts
src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
src/subdomains/core/liquidity-management/services/liquidity-management-balance.service.ts
src/subdomains/generic/user/models/auth/auth.service.ts

[NOTASK] Refactoring IP block

---

src/subdomains/supporting/recall/dto/create-recall.dto.ts
src/subdomains/supporting/recall/dto/update-recall.dto.ts
src/subdomains/supporting/recall/recall.controller.ts
src/subdomains/supporting/recall/recall.module.ts
src/subdomains/supporting/recall/recall.service.ts

[DEV-4398] recall update endpoint

---

src/subdomains/core/payment-link/dto/payment-link-config.dto.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/core/payment-link/services/payment-link-payment.service.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts

[DEV-3593] Payment cancellable

---

src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/history/mappers/transaction-dto.mapper.ts
src/subdomains/supporting/payin/entities/crypto-input.entity.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[DEV-4408] transactionReason cryptoInputNotConfirmed

---

infrastructure/bicep/container-apps/apps/parameters/dev-jsw.json
infrastructure/bicep/container-apps/apps/parameters/prd-jsp.json
infrastructure/bicep/container-apps/apps/parameters/prd-jsw.json
src/shared/models/country/country.entity.ts
src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
src/subdomains/core/history/mappers/transaction-dto.mapper.ts
src/subdomains/core/liquidity-management/adapters/actions/liquidity-pipeline.adapter.ts
src/subdomains/core/payment-link/dto/payment-link-config.dto.ts
src/subdomains/core/payment-link/dto/payment-link-dto.mapper.ts
src/subdomains/core/payment-link/entities/payment-link.config.ts
src/subdomains/core/payment-link/entities/payment-link.entity.ts
src/subdomains/generic/forwarding/services/lnurl-forward.service.ts
src/subdomains/generic/kyc/dto/ident-result-data.dto.ts
src/subdomains/generic/kyc/services/kyc.service.ts
src/subdomains/supporting/fiat-output/fiat-output-job.service.ts
src/subdomains/supporting/payin/entities/crypto-input.entity.ts
src/subdomains/supporting/payin/services/payin.service.ts
src/subdomains/supporting/payment/dto/transaction.dto.ts

[DEV-3593]&[NOTASK]&[DEV-4408] Improvements for Payment, block fiatOutput, transactionReason, payIn logging

---

infrastructure/bicep/container-apps/apps/parameters/dev-jsw.json
infrastructure/bicep/container-apps/apps/parameters/prd-jsw.json

- Add CITREA_RPC_URL to dev-jsw.json with dev node URL
- Add CITREA_RPC_URL to prd-jsw.json with production node URL
- Enables environment-specific Citrea RPC configuration
- Login/logout
- KYC page

Add CITREA_RPC_URL environment variable to JuiceSwap API
