DFXswiss/api

- src/log/log.service.ts
- src/services/kyc.service.ts
- src/userData/userData.service.ts
Changed method getManyCheckStatus (Check without bankdata)
> Removed unnecessary date

- src/shared/services/mail.service.ts
- src/user/models/user/user.service.ts
Add user not found exception to getUser
> Remove kyc file reference from failed mail

- src/payment/services/exchange.service.ts
- Partial orders
- New order after 60s if not filled
- Withdraw functionality
> Implement different order strategy

- src/shared/i18n/fr/mail.json
Mails translation in French is done.
> FR language ready

- src/shared/i18n/it/mail.json
> mail translated in IT version

- src/payment/models/crypto-input/crypto-input.service.ts
> Crypto-Input Try-Catch

- src/payment/models/crypto-input/crypto-input.service.ts
> Off-Ramp Fix

- infrastructure/bicep/dfx-api.bicep
- src/config/config.ts
- src/payment/models/crypto-input/crypto-input.service.spec.ts
- src/user/models/userData/userData.controller.ts
- src/user/models/userData/userData.service.ts
- src/user/services/kyc/kyc.service.ts
> Minor Fixes

- src/user/services/kyc/kyc-scheduler.service.ts
> Deactivated KYC error mails

- src/user/services/kyc/kyc-scheduler.service.ts
> Fix for user without spider data

- src/user/services/kyc/kyc-scheduler.service.ts
> Fixed XML Ident Results

- src/user/services/kyc/kyc-scheduler.service.ts
> Fixed non-nullable URL

- src/payment/models/masternode/masternode.service.ts
- src/payment/models/ref-reward/ref-reward.service.ts
- src/payment/models/staking-reward/staking-reward.service.ts
- src/payment/models/staking/staking.service.ts
- src/statistic/statistic.service.ts
- src/user/models/user/user.service.ts
> Removed temporary code & change reward calculation for statistic route

- src/user/models/user/user.service.ts
> fix volume to paid ref volume

- src/user/models/user-data/user-data.entity.ts
- src/user/services/kyc/kyc.service.ts
> KYC Status Check

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/admin/admin.controller.ts
- src/user/models/kyc/kyc-process.service.ts
- src/user/models/referral/ref.service.ts
> Minor Improvements

- src/user/models/user-data/user-data.service.ts
- src/user/models/user/user.service.ts
> Fixed user registration

- migration/1648038234783-UserDataNotNull.js
- migration/1648158906542-StakingTable.js
- src/payment/models/crypto-input/crypto-input.service.ts
- src/payment/models/crypto-staking/crypto-staking.controller.ts
- src/payment/models/crypto-staking/crypto-staking.entity.ts
- src/payment/models/crypto-staking/crypto-staking.service.spec.ts
- src/shared/services/dfi-tax.service.ts
- src/user/models/auth/auth.service.ts
- src/user/models/kyc/kyc.service.ts
- src/user/models/user-data/user-data.service.ts
- src/user/models/user/user.entity.ts
- src/user/models/user/user.service.ts
> Refactoring admin upload and add crypto staking table

- src/payment/models/crypto-staking/crypto-staking.controller.ts
- src/payment/models/staking-reward/staking-reward.service.ts
- src/payment/models/staking/dto/staking.dto.ts
- src/payment/models/staking/staking.service.ts
> Remove temp code and add new calc of APR/APY from staking table

- src/payment/models/staking/staking.service.ts
> Fixed paybackType bug

- src/payment/models/crypto-staking/crypto-staking.service.ts
> New Staking Batch System

- src/payment/models/crypto-staking/crypto-staking.service.ts
- src/statistic/statistic.service.ts
> Staking Payout Fixes

- migration/1648589636157-AddedPaybackDeposit.js
- src/payment/models/crypto-staking/crypto-staking.entity.ts
- src/payment/models/crypto-staking/crypto-staking.service.ts
- src/payment/models/staking-reward/staking-reward.service.ts
> Staking Payback Fixes

- src/payment/models/staking-reward/staking-reward.service.ts
- src/shared/util.ts
> Change to period APY

- infrastructure/docker/defi-node-dev.yml
- infrastructure/docker/defi-node-loc.yml
- src/payment/models/crypto-staking/crypto-staking.service.ts
- src/payment/models/exchange/exchange.service.ts
- src/user/models/user-data/user-data.service.ts
- src/user/services/spider/spider.service.ts
> Chatbot Prefil / Bug Fixes

- src/admin/admin.controller.ts
- src/payment/models/bank-tx/bank-tx.controller.ts
- src/payment/models/bank-tx/bank-tx.service.ts
- src/payment/models/buy/buy.service.ts
- src/payment/models/crypto-input/crypto-input.controller.ts
- src/payment/models/crypto-input/crypto-input.service.ts
- src/payment/payment.module.ts
> Refactoring typed routes

- src/admin/admin.controller.ts
> Commented bankTx type on admin route

- src/admin/admin.controller.ts
> activate admin bankTx type

- src/admin/admin.controller.ts
- src/payment/models/bank-tx/bank-tx.controller.ts
- src/payment/models/bank-tx/bank-tx.entity.ts
- src/payment/models/bank-tx/bank-tx.service.ts
- src/payment/models/crypto-input/crypto-input.controller.ts
- src/payment/models/crypto-input/crypto-input.entity.ts
- src/payment/models/crypto-input/crypto-input.service.ts
- src/payment/models/crypto-staking/crypto-staking.service.ts
- src/shared/services/conversion.service.ts
- src/shared/util.ts
- src/statistic/assets/cfp-results.json
> cryptoInput type Update

- src/payment/models/crypto-staking/crypto-staking.service.ts
> Rounding batch amount

- src/payment/models/crypto-sell/crypto-sell.service.ts
> Fix bankTx newTime for cryptoSell

- src/app.controller.ts
- src/dto/advertisement.dto.ts
- src/payment/models/crypto-input/crypto-input.service.ts
- src/payment/models/crypto-staking/crypto-staking.service.ts
- src/user/models/user-data/user-data.service.ts
> History Withdrawal fix

- migration/1650105288039-AddSpiderExport.js
- src/payment/models/crypto-staking/crypto-staking.service.ts
- src/user/models/kyc/kyc-process.service.ts
- src/user/models/spider-data/spider-data.entity.ts
- src/user/models/user-data/user-data.service.ts
- src/user/services/spider/dto/spider.dto.ts
- src/user/services/spider/spider.service.ts
> Ad Languages

- src/user/models/bank-data/bank-data.service.ts
- src/user/models/user-data/user-data.repository.ts
> userData Update time fix

- infrastructure/bicep/dfx-api.bicep
- src/payment/models/crypto-staking/crypto-staking.service.ts
> Payback Output Date Rearrangement

- src/payment/models/crypto-sell/crypto-sell.service.ts
> Fixed AML check bug

- src/payment/models/bank-tx/bank-tx.service.ts
> Fixed null reference bug

- package-lock.json
- package.json
- src/shared/auth/jwt.strategy.ts
- src/shared/shared.module.ts
> Auth Problem Fix

- infrastructure/Readme.md
- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- infrastructure/scripts/check-node-state.sh
- infrastructure/scripts/swap-nodes.sh
- infrastructure/scripts/update-nodes.sh
- package-lock.json
- package.json
- src/admin/admin.controller.ts
- src/ain/node/node.service.ts
- src/config/config.ts
- src/payment/models/buy-crypto/buy-crypto.service.ts
- src/payment/models/crypto-sell/crypto-sell.service.ts
- src/payment/models/ref-reward/ref-reward.service.ts
- src/payment/models/staking-reward/staking-reward.service.ts
- src/shared/auth/jwt.strategy.ts
- src/shared/shared.module.ts
- src/user/models/kyc/kyc.service.ts
- src/user/models/user/user.service.ts
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
> REF-Node / Minor Fixes

- src/config/config.ts
- src/payment/models/crypto-input/crypto-input.service.ts
- src/payment/models/crypto-staking/crypto-staking.service.ts
- src/payment/models/history/history.service.ts
- src/payment/models/staking/staking.service.ts
- src/user/models/user-data/user-data.entity.ts
- src/user/models/user/user.service.ts
> Add monitoring data (Kyc Status & Bank Tx without type)

- src/user/models/user-data/user-data.service.ts
> Add IsNull() to kycStatusChangeDate

- infrastructure/docker/defi-node-dev.yml
- infrastructure/docker/defi-node-loc.yml
- infrastructure/docker/defi-node-prd.yml
- src/ain/node/node-client.ts
- src/payment/models/crypto-staking/crypto-staking.service.ts
- src/user/models/user-data/user-data.service.ts
- src/user/models/user/user.service.ts
> Recalculate UserData Volume on Merge

- infrastructure/docker/defi-node-dev.yml
- infrastructure/docker/defi-node-loc.yml
- infrastructure/docker/defi-node-prd.yml
- migration/1654250762961-AllowIdleMasternodes.js
- migration/1654346660483-IpEnable.js
- package-lock.json
- package.json
- src/admin/admin.controller.ts
- src/ain/node/node-client.ts
- src/payment/models/crypto-input/crypto-input.service.ts
- src/payment/models/crypto-staking/crypto-staking.service.ts
- src/payment/models/masternode/masternode.entity.ts
- src/payment/models/masternode/masternode.service.ts
- src/payment/models/sell/sell.entity.ts
- src/payment/models/staking-ref-reward/staking-ref-reward.service.ts
- src/shared/auth/jwt.strategy.ts
- src/shared/models/country/country.entity.ts
- src/shared/models/country/country.service.ts
- src/shared/shared.module.ts
- src/user/models/user-data/user-data.service.ts
- src/user/models/user/dto/volume-query.dto.ts
- src/user/models/user/user.controller.ts
- src/user/models/user/user.service.spec.ts
- src/user/models/user/user.service.ts
- thunder-tests/thunderclient.json
> Add monitoring data, open operators to masternode table and ignoring liquidity pools

- src/payment/models/crypto-input/crypto-input.service.ts
> Saving crypto inputs sequentially

- src/payment/models/crypto-input/crypto-input.service.spec.ts
> Followup PR for fixing CryptoInput tests

- src/admin/admin.controller.ts
> Fixed bank TX extended for empty types

- src/payment/models/staking/staking.controller.ts
- src/payment/models/staking/staking.service.ts
> Switch to staking volume

- src/config/config.ts
- src/monitoring/monitoring.controller.ts
- src/monitoring/monitoring.service.ts
- src/payment/models/crypto-staking/crypto-staking.service.ts
- src/payment/models/deposit/deposit.service.ts
- src/payment/payment.module.ts
- src/user/models/user-data/user-data.service.ts
- src/user/models/user/user.service.ts
- thunder-tests/thunderclient.json
Add unmatchedStaking
Add free deposits
- Login/logout
- Registration
> Add JWT Expired, unmatchedStaking and free deposits

- src/monitoring/monitoring.controller.ts
- src/monitoring/monitoring.module.ts
- src/monitoring/monitoring.service.ts
- src/user/models/user-data/user-data.controller.ts
- src/user/models/user-data/user-data.entity.ts
- src/user/models/user-data/user-data.service.ts
- src/user/services/spider/spider-sync.service.ts
- src/user/services/spider/spider.service.ts
Add kycFileId to userData
- Login/logout
- Registration
> Add spiderData to monitoring

- src/monitoring/monitoring.service.ts
- src/user/models/user-data/user-data.entity.ts
- src/user/services/spider/spider-sync.service.ts
> Add manual identPdf & monitoring data

- src/ain/node/node.service.ts
> Add retry to node healthcheck

- .githooks/pre-commit
- src/ain/node/node.service.ts
- src/config/config.ts
- src/monitoring/monitoring.service.ts
- src/payment/models/bank-tx/sepa-parser.service.ts
- src/payment/models/buy/buy.service.ts
- src/payment/models/crypto-staking/crypto-staking.service.ts
- src/payment/models/sell/sell.service.ts
- src/payment/models/staking/staking.service.ts
- src/shared/services/conversion.service.ts
- src/statistic/cfp.service.ts
- src/user/models/user-data/user-data.service.ts
- src/user/models/user/user.service.ts
- src/user/services/spider/spider-sync.service.ts
> Add decimals to config, remove temp code, fixed should staking balance

- .githooks/pre-commit
- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- infrastructure/docker/defi-node-dev.yml
- infrastructure/docker/defi-node-loc.yml
- migration/1656083888483-addBankAccount.js
- migration/1656519269231-indexNameChange.js
- src/config/config.ts
- src/payment/models/bank-account/bank-account.entity.ts
- src/payment/models/bank-account/bank-account.repository.ts
- src/payment/models/bank-account/bank-account.service.ts
- src/payment/models/buy-crypto/buy-crypto.service.ts
- src/payment/models/buy/buy.entity.ts
- src/payment/models/buy/buy.service.ts
- src/payment/models/crypto-buy/crypto-buy.service.ts
- src/payment/models/history/history.service.ts
- src/payment/models/sell/sell.entity.ts
- src/payment/models/sell/sell.service.ts
- src/payment/payment.module.ts
- src/shared/models/entity.ts
- src/shared/services/iban.service.ts
- src/shared/shared.module.ts
- src/statistic/statistic.controller.ts
- src/user/models/user/user.entity.ts
- src/user/models/user/user.service.ts
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
> BankAccount, Switch cryptoBuy -> buyCrypto

- migration/1656546677836-extendBicLength.js
- src/payment/models/bank-account/bank-account.entity.ts
- src/payment/models/buy-crypto/buy-crypto.entity.ts
- src/payment/models/buy/buy.service.ts
- src/payment/models/sell/sell.service.ts
> Refactoring + migration extendbicLength

- src/payment/models/buy-crypto/services/buy-crypto-out.service.ts
> Fixed balance mismatch check

- src/payment/models/buy-crypto/services/buy-crypto-out.service.ts
> Fixed balance mismatch check (#279)

- src/payment/models/buy-crypto/entities/buy-crypto-batch.entity.ts
- src/payment/models/buy-crypto/entities/buy-crypto.entity.ts
- src/payment/models/buy-crypto/services/buy-crypto-dex.service.ts
- src/payment/models/buy-crypto/services/buy-crypto-notification.service.ts
- src/payment/models/buy-crypto/services/buy-crypto-out.service.ts
- src/payment/models/buy-crypto/utils/buy-crypto-chain.util.ts
- src/payment/models/buy/__tests__/mock/buy.entity.mock.ts
- src/payment/models/crypto-input/crypto-input.service.ts
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
> Buy crypto patch 5

- src/admin/admin.controller.ts
- src/payment/models/buy-crypto/services/buy-crypto.service.ts
- src/user/models/user/dto/user.dto.ts
- src/user/models/user/user.service.ts
> Fix user Activation Bug

- src/monitoring/observers/node-health.observer.ts
> [DEV-173] Refactored Node Health Monitoring

- src/ain/node/btc-client.ts
- src/ain/node/defi-client.ts
- src/ain/node/node-client.ts
- src/ain/node/node.service.ts
- src/monitoring/monitoring.service.ts
- src/payment/models/buy-crypto/services/buy-crypto-dex.service.ts
- src/payment/models/buy-crypto/services/buy-crypto-out.service.ts
- src/payment/models/buy-crypto/utils/buy-crypto-chain.util.ts
- src/payment/models/crypto-input/crypto-input.service.spec.ts
- src/payment/models/crypto-input/crypto-input.service.ts
- src/payment/models/crypto-staking/crypto-staking.service.ts
- src/payment/models/deposit/deposit.service.ts
- src/payment/models/staking-ref-reward/staking-ref-reward.service.ts
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
> [DEV-167] Typed Node Clients

- src/payment/models/buy/dto/create-buy.dto.ts
> [DEV-167] removed unused object

- src/monitoring/monitoring.service.ts
> [HOTFIX] Deactivate monitoring of BTC node

- migration/1657577348235-AddedBuyFiat.js
- src/monitoring/observers/payment.observer.ts
- src/payment/models/bank-tx/bank-tx.repository.ts
- src/payment/models/buy-fiat/buy-fiat.controller.ts
- src/payment/models/buy-fiat/buy-fiat.entity.ts
- src/payment/models/buy-fiat/buy-fiat.repository.ts
- src/payment/models/buy-fiat/buy-fiat.service.ts
- src/payment/models/crypto-buy/crypto-buy.service.ts
- src/payment/models/crypto-input/crypto-input.entity.ts
- src/payment/models/crypto-input/crypto-input.repository.ts
- src/payment/models/crypto-input/crypto-input.service.ts
- src/payment/models/crypto-sell/crypto-sell.service.ts
- src/payment/models/sell/sell.entity.ts
- src/payment/payment.module.ts
- src/statistic/cfp.service.ts
> DEV-36 BuyFiat

- src/payment/models/staking-ref-reward/staking-ref-reward.service.ts
> [DEV-93] implemented filtering for confirmed rewards

- migration/1657577348235-AddedBuyFiat.js
- src/monitoring/observers/payment.observer.ts
- src/payment/models/bank-tx/bank-tx.repository.ts
- src/payment/models/buy-fiat/buy-fiat.controller.ts
- src/payment/models/buy-fiat/buy-fiat.entity.ts
- src/payment/models/buy-fiat/buy-fiat.repository.ts
- src/payment/models/buy-fiat/buy-fiat.service.ts
- src/payment/models/crypto-buy/crypto-buy.service.ts
- src/payment/models/crypto-input/crypto-input.entity.ts
- src/payment/models/crypto-input/crypto-input.repository.ts
- src/payment/models/crypto-input/crypto-input.service.spec.ts
- src/payment/models/crypto-input/crypto-input.service.ts
- src/payment/models/crypto-sell/crypto-sell.service.ts
- src/payment/models/sell/sell.entity.ts
- src/payment/models/staking-ref-reward/staking-ref-reward.service.ts
- src/payment/payment.module.ts
- src/statistic/cfp.service.ts
> DEV-36 Buy Fiat / DEV-93 Staking Ref Rewards

- migration/1657834977332-AdditionalUserDataFields.js
- src/user/models/user-data/dto/update-user-data.dto.ts
- src/user/models/user-data/user-data.entity.ts
> [DEV-349] New UserData Fields

- .vscode/settings.json
- migration/1657872324388-AddedBuyCryptoChargeback.js
- src/payment/models/buy-crypto/dto/update-buy-crypto.dto.ts
- src/payment/models/buy-crypto/entities/buy-crypto.entity.ts
- src/payment/models/buy-crypto/services/buy-crypto.service.ts
> [DEV-372] BuyCrypto Chargeback

- src/payment/models/bank-tx/bank-tx.controller.ts
- src/shared/auth/user-role.enum.ts
> DEV-190 Banking Bot User

- src/payment/models/crypto-input/crypto-input.service.ts
> [DEV-88] imperative solution to dust errors

- migration/1658047296831-buyFiatCols.js
- src/monitoring/observers/payment.observer.ts
- src/payment/models/buy-crypto/services/buy-crypto.service.ts
- src/payment/models/buy-fiat/buy-fiat.controller.ts
- src/payment/models/buy-fiat/buy-fiat.entity.ts
- src/payment/models/buy-fiat/buy-fiat.service.ts
- src/payment/models/buy-fiat/dto/update-buy-fiat.dto.ts
- src/payment/models/crypto-input/crypto-input.service.ts
- src/payment/models/crypto-route/crypto-route.service.ts
- src/payment/models/crypto-route/dto/create-crypto-route.dto.ts
- src/payment/models/crypto-sell/crypto-sell.service.ts
- src/payment/models/history/history.service.ts
- src/shared/services/dfi-tax.service.ts
- src/user/models/user/user.service.ts
- thunder-tests/thunderclient.json
> [DEV-329],[DEV-420],[DEV-167],[DEV-88],[DEV-415] buyFiat Cols

- src/payment/models/crypto-input/btc-input.service.ts
- src/payment/models/crypto-input/defi-input.service.ts
- src/payment/models/crypto-route/crypto-route.service.ts
> DEV-167 / DEV-369 - Minor Fixes

- src/payment/models/crypto-input/defi-input.service.ts
> [FIX] DUSD-USDT Swap

- src/payment/models/buy-crypto/entities/buy-crypto.entity.ts
- src/payment/models/buy-crypto/services/buy-crypto-batch.service.ts
- src/payment/models/crypto-route/crypto-route.controller.ts
- src/payment/models/crypto-route/dto/crypto-route.dto.ts
> [DEV-369] If input a crypto then use inputReferenceAmountMinusFee

- src/payment/models/buy-crypto/entities/__tests__/buy-crypto.entity.spec.ts
- src/payment/models/buy-crypto/entities/buy-crypto.entity.ts
- src/payment/models/buy-crypto/services/buy-crypto-batch.service.ts
- src/payment/models/crypto-route/crypto-route.controller.ts
- src/payment/models/crypto-route/dto/crypto-route.dto.ts
* [DEV-369] If input a crypto then use inputReferenceAmountMinusFee
* [DEV-369] Add blockchain to crypto route dto
* [DEV-369] remove unused import
* [DEV-369] Refactored output price determination
Co-authored-by: David May <david.leo.may@gmail.com>
- Login/logout
- Registration
[DEV-369]: https://dfxswiss.atlassian.net/browse/DEV-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-369]: https://dfxswiss.atlassian.net/browse/DEV-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-369]: …
> [DEV-369] If input a crypto then use inputReferenceAmountMinusFee (#318)

- src/payment/models/crypto-input/btc-input.service.ts
> [DEV-369] round feeRate with 0 decimals

- src/payment/models/crypto-input/btc-input.service.ts
* [DEV-369] round feeRate with 0 decimals
* [DEV-369] change to Math.floor()
* [DEV-369] refactoring
- Login/logout
- Registration
[DEV-369]: https://dfxswiss.atlassian.net/browse/DEV-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-369]: https://dfxswiss.atlassian.net/browse/DEV-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-369]: https://dfxswiss.atlassian.net/browse/DEV-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DEV-369] round feeRate with 0 decimals (#323)

- src/payment/models/history/history.service.ts
> [FIX] CT: change Staking txid

- migration/1658763007658-apiKeyCTUniqueIndex.js
- src/user/models/user/user.entity.ts
> [DEV-456] add Index + migration

- src/payment/models/history/history.service.ts
> [DEV-398] disable LM history

- src/config/config.ts
- src/payment/models/bank-tx/bank-tx.entity.ts
- src/payment/models/bank-tx/bank-tx.service.ts
- src/payment/models/bank-tx/olky-pay.service.ts
- src/payment/models/bank-tx/olkypay.service.ts
- src/payment/payment.module.ts
- src/shared/services/conversion.service.ts
- src/shared/util.ts
> [DEV-185]: Olkypay

- src/config/config.ts
- src/user/models/user/user.service.ts
> [FIX] add apiKeyCT Version

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/ain/node/defi-client.ts
- src/config/config.ts
- src/monitoring/observers/node-balance.observer.ts
- src/payment/models/bank-tx/bank-tx.entity.ts
- src/payment/models/bank-tx/bank-tx.service.ts
- src/payment/models/bank-tx/olkypay.service.ts
- src/payment/payment.module.ts
- src/shared/services/conversion.service.ts
- src/shared/util.ts
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
> [DEV-185 & THUNDER] Add olkypay payments and update thunderclient

- src/monitoring/monitoring.module.ts
- src/monitoring/observers/olkypay.observer.ts
- src/payment/models/bank-tx/olkypay.service.ts
- src/payment/payment.module.ts
- src/shared/filters/exception.filter.ts
> [DEV-531] & [DEV-532] Add olkypay improvements, monitoring and exception logger

- migration/1659083576871-kycHashToUUID.js
- src/shared/models/country/__tests__/mock/country.entity.mock.ts
- src/shared/models/country/country.controller.ts
- src/user/models/kyc/dto/kyc-user-data.dto.ts
- src/user/models/kyc/kyc.controller.ts
- src/user/models/kyc/kyc.service.spec.ts
- src/user/models/kyc/kyc.service.ts
- src/user/models/user-data/__tests__/mock/user-data.entity.mock.ts
- src/user/models/user-data/user-data.controller.ts
- src/user/models/user-data/user-data.entity.ts
- src/user/models/user-data/user-data.service.ts
- src/user/models/user/user.service.ts
- thunder-tests/kyc-incorp-cert/test.json
- thunder-tests/thunderCollection.json
- thunder-tests/thunderEnvironment.json
- thunder-tests/thunderclient.json
> [DEV-201] kyc code changes

- src/payment/models/dex/services/liquidity.service.ts
> [DEV-383] patch 1 fixed purchase price calculation

- src/payment/models/dex/services/liquidity.service.ts
> [DEV-383] Patch 2 fixed min price calculation for BTC

- src/payment/models/dex/services/liquidity.service.ts
> [DEV-383] Patch 2 fixed min price calculation for BTC (#341)

- src/payment/models/buy-crypto/services/buy-crypto-out.service.ts
> HOTFIX - skip DFI token check on out node

- src/payment/models/buy-crypto/services/buy-crypto-out.service.ts
> HOTFIX - skip the DFI token check on OUT node (#345)

- src/config/config.ts
- src/payment/models/crypto-route/crypto-route.controller.ts
- src/user/models/user/user.service.spec.ts
- src/user/models/user/user.service.ts
> [DEV-557] changed crypto route fee if a ref was used

- src/config/config.ts
> HOTFIX: letter service

- src/config/config.ts
> HOTFIX: letter service (#355)

- src/payment/models/buy-fiat/buy-fiat-notification.service.ts
> [FIX] mail update error

- package-lock.json
- package.json
- src/ain/services/__tests__/crypto.service.spec.ts
- src/ain/services/crypto.service.ts
- src/config/config.ts
- src/user/models/auth/auth.service.ts
- src/user/models/auth/dto/auth-credentials.dto.ts
- src/user/models/user/dto/create-user.dto.ts
> [DEV-597] other blockchain message verification

- src/ain/services/crypto.service.ts
- src/user/models/link/dto/link.dto.ts
- src/user/models/link/link.controller.ts
- src/user/models/link/link.service.ts
- src/user/models/user/user.service.spec.ts
- src/user/models/user/user.service.ts
- src/user/user.module.ts
- Login/logout
- Registration
- https://github.com/DFXswiss/api/pull/359
> [DEV-607] link address to existing user

- migration/1660657475628-link-address.js
- src/user/models/kyc/kyc.service.spec.ts
- src/user/models/kyc/kyc.service.ts
- src/user/models/link/__tests__/link-address.entity.spec.ts
- src/user/models/link/__tests__/mock/link-address.entity.mock.ts
- src/user/models/link/dto/link.dto.ts
- src/user/models/link/link-address.entity.ts
- src/user/models/link/link-address.repository.ts
- src/user/models/link/link.controller.ts
- src/user/models/link/link.service.ts
- src/user/user.module.ts
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
> [DEV-624] link changes

- src/config/config.ts
- src/payment/models/buy-crypto/services/buy-crypto-out.service.ts
- src/payment/models/buy/__tests__/buy.controller.spec.ts
- src/payment/models/buy/__tests__/buy.service.spec.ts
- src/payment/models/buy/buy.controller.ts
- src/payment/models/buy/dto/buy.dto.ts
- src/payment/models/crypto-input/btc-input.service.ts
- src/payment/models/crypto-input/defi-input.service.spec.ts
- src/payment/models/crypto-input/defi-input.service.ts
- src/payment/models/crypto-route/__tests__/crypto-route.controller.spec.ts
- src/payment/models/crypto-route/__tests__/mock/crypto-route.entity.mock.ts
- src/payment/models/crypto-route/crypto-route.controller.ts
- src/payment/models/crypto-route/dto/crypto-route.dto.ts
- src/payment/models/deposit/__tests__/mock/deposit.entity.mock.ts
- src/payment/models/deposit/dto/min-deposit.dto.ts
- src/payment/models/sell/__tests__/mock/sell.entity.mock.ts
- src/payment/models/sell/__tests__/sell.controller.spec.ts
- src/payment/models/sell/dto/sell.dto.ts
- src/payment/models/sell/sell.controller.ts
- src/payment/models/staking/__tests__/mock/staking.entity.mock.ts
- src/payment/models/staking/__tests__/staking.controller.spec.ts
- src/payment/models/staking/__tests__/staking.service.spec.ts
- src/payment/models/staking/dto/staking.dto.ts
- src/payment/models/staking/staking.service.ts
- src/shared/__tests__/util.spec.ts
- src/shared/util.ts
- https://github.com/DFXswiss/api/pull/350 due to the need of all previously written mocks
- Login/logout
- Registration
> [DEV-586] adapt deposit info

- migration/1660729279828-blockchain-info.js
- src/ain/node/node.service.ts
- src/ain/services/__tests__/crypto.service.spec.ts
- src/ain/services/crypto.service.ts
- src/payment/models/crypto-input/btc-input.service.ts
- src/payment/models/crypto-input/chainalysis.service.ts
- src/payment/models/crypto-input/defi-input.service.ts
- src/payment/models/crypto-route/dto/create-crypto-route.dto.ts
- src/payment/models/crypto-route/dto/crypto-route.dto.ts
- src/payment/models/deposit/deposit.entity.ts
- src/payment/models/deposit/deposit.service.ts
- src/payment/models/dex/services/dex.service.ts
- src/payment/models/dex/strategies/purchase-liquidity/purchase-non-poolpair-liquidity.strategy.ts
- src/payment/models/dex/strategies/purchase-liquidity/purchase-poolpair-liquidity.strategy.ts
- src/payment/models/sell/sell.service.ts
- src/payment/models/staking/staking.service.ts
- src/shared/auth/jwt-payload.interface.ts
- src/shared/models/asset/asset.controller.ts
- src/shared/models/asset/asset.entity.ts
- src/shared/models/asset/asset.service.ts
- src/statistic/cfp.service.ts
- src/user/models/auth/auth.controller.ts
- src/user/models/auth/auth.service.ts
- src/user/models/user/dto/user.dto.ts
- src/user/models/user/user.entity.ts
- src/user/models/user/user.service.ts
> [DEV-633] added blockchain info to JWT, user and asset

- .vscode/settings.json
- src/payment/models/buy-crypto/entities/buy-crypto.entity.ts
- src/payment/models/buy-crypto/services/buy-crypto-batch.service.ts
- src/payment/models/exchange/bitpanda.service.ts
- src/payment/models/exchange/dto/price.dto.ts
- src/payment/models/exchange/exchange-utility.service.ts
- src/payment/models/exchange/exchange.service.ts
- src/payment/payment.module.ts
> [DEV-671] New Reference Currencies

- src/payment/models/buy-crypto/services/buy-crypto-batch.service.ts
- src/shared/services/api-key.service.ts
> [DEV-671] Fixed reference price calculation

- src/statistic/assets/cfp-results.json
- src/statistic/cfp.service.ts
> [DEV-676] Add currentRound to cfp list and add 2206 and 2207 to cfp results

- src/payment/models/bank-tx/frick.service.ts
> [DEV-596] fix return []

- src/payment/models/exchange/exchange.service.ts
> [DEV-695] Trading Bot Fix

- src/payment/models/exchange/exchange-utility.service.ts
> [DEV-696] Price Mismatch Error Mail

- migration/1661805067683-AddAba.js
- src/monitoring/observers/bank.observer.ts
- src/payment/models/bank-tx/bank-tx.entity.ts
- src/payment/models/bank-tx/frick.service.ts
> [DEV-596] Add foreign information

- src/payment/models/exchange/exchange.service.ts
- src/user/models/kyc/kyc.service.ts
> [DEV-658] KYC Bugs

- src/config/config.ts
- src/user/models/kyc/kyc-process.service.ts
- src/user/services/spider/spider-sync.service.ts
> [DEV-713] Change kyc mail link to kyc hash

- src/user/models/auth/auth.controller.ts
- src/user/models/auth/auth.service.ts
- src/user/models/user/dto/linked-user.dto.ts
- src/user/models/user/dto/user.dto.ts
- src/user/models/user/user.controller.ts
- src/user/models/user/user.service.ts
- thunder-tests/thunderclient.json
> [DEV-634] change user

- src/config/config.ts
- src/payment/models/masternode/masternode.service.ts
- src/user/models/kyc/kyc-process.service.ts
- src/user/services/spider/spider-sync.service.ts
> [DEV-365] Sync operators

- migration/1662077975490-renameAccountNumber.js
- src/payment/models/bank-account/bank-account.entity.ts
- src/payment/models/bank-account/bank-account.service.ts
> [DEV-698] add cron-Job, rename bankAccount

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- infrastructure/docker/defi-node-dev.yml
- infrastructure/docker/defi-node-loc.yml
- infrastructure/docker/defi-node-prd.yml
- migration/1662077975490-renameAccountNumber.js
- src/config/config.ts
- src/payment/models/bank-account/bank-account.entity.ts
- src/payment/models/bank-account/bank-account.service.ts
- src/payment/models/crypto-input/btc-input.service.ts
- src/payment/models/masternode/masternode.service.ts
- src/shared/services/api-key.service.ts
- src/user/models/kyc/kyc-process.service.ts
- src/user/services/spider/spider-sync.service.ts
> [DEV-365] & [DEV-713] & [DEV-698] Masternode sync automation & change kyc link to kyc hash

- migration/1660729279828-blockchain-info.js
- migration/1662544933802-remove-asset-name-unique.js
- src/shared/models/asset/asset.entity.ts
- src/user/models/user/user.service.ts
> [DEV-716] correctly add blockchains to out dto

- src/user/models/auth/auth.service.ts
- src/user/models/kyc/kyc.service.spec.ts
- src/user/models/kyc/kyc.service.ts
- src/user/models/link/link.service.ts
- src/user/models/user/user.repository.ts
- src/user/models/user/user.service.ts
> [DEV-593] moved link creation to link service

- src/statistic/assets/cfp-results.json
> [MAIN] Add 2208 results

- src/statistic/cfp.service.spec.ts
> [DEV-667] fixed the failing cfp-service test

- src/blockchain/ain/services/crypto.service.ts
- src/user/models/auth/auth.service.ts
> [DEV-566] use new sign message for defichain

- src/payment/models/exchange/dto/trade-response.dto.ts
- src/payment/models/exchange/services/exchange.service.spec.ts
- src/payment/models/exchange/services/exchange.service.ts
> [DEV-695] Trading Fix

- src/payment/models/buy-crypto/services/buy-crypto-batch.service.ts
- src/payment/models/buy-crypto/services/buy-crypto-out.service.ts
> Hotfix - changed buy to target in buy-crypto process

- src/payment/models/buy-crypto/services/buy-crypto-batch.service.ts
- src/payment/models/buy-crypto/services/buy-crypto-out.service.ts
> Hotfix - changed buy to target in buy-crypto (#414)

- src/user/models/user/dto/user.dto.ts
- src/user/models/user/user.service.ts
> [DEV-256] add volume information for all route types

- src/payment/models/payout/services/payout-defichain.service.ts
- src/payment/models/payout/strategies/payout/payout-defichain-token.strategy.ts
> [DEV-441] UTXO minimal top-up only for user addresses

- src/user/services/spider/spider.service.ts
> [DEV-565] Add condition for authorisesConversationPartner

- migration/1663942486233-addLimitRequestCols.js
- src/user/models/limit-request/dto/update-limit-request.dto.ts
- src/user/models/limit-request/limit-request.controller.ts
- src/user/models/limit-request/limit-request.entity.ts
- src/user/models/limit-request/limit-request.service.ts
- src/user/user.module.ts
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
> [DEV-800] add LimitRequest cols, migration, update method

- migration/1664363339859-addFiatBuyableSellableCols.js
- src/shared/models/fiat/fiat.entity.ts
> [DEV-824] add buyable, sellable + migration

- migration/1664656167454-addBankTxReturnTable.js
- src/payment/models/bank-tx-return/bank-tx-return.entity.ts
- src/payment/models/bank-tx-return/bank-tx-return.repository.ts
- src/payment/models/bank-tx-return/bank-tx-return.service.ts
- src/payment/models/bank-tx/bank-tx.service.ts
- src/payment/payment.module.ts
> [DEV-832] add bankTxReturn + migration

- migration/1664968683394-addBankTxRepeatTable.js
- src/payment/models/bank-tx-repeat/bank-tx-repeat.entity.ts
- src/payment/models/bank-tx-repeat/bank-tx-repeat.repository.ts
- src/payment/models/bank-tx-repeat/bank-tx-repeat.service.ts
- src/payment/models/bank-tx/bank-tx.service.ts
- src/payment/payment.module.ts
> [DEV-839] add bankTxRepeat Tabel + migration

- src/config/config.ts
- src/payment/models/crypto-route/crypto-route.controller.ts
- src/payment/models/sell/sell.controller.ts
- src/shared/util.ts
> [DEV-801] & [DEV-802]: min Deposit

- migration/1665483618683-addBankTxReturnCols.js
- src/payment/models/bank-tx-return/bank-tx-return.entity.ts
- src/payment/models/bank-tx-return/bank-tx-return.service.ts
- src/payment/models/bank-tx/bank-tx.service.ts
- src/payment/models/bank-tx/dto/update-bank-tx.dto.ts
- thunder-tests/thunderclient.json
> [DEV-860] add BankTxReturn Cols + migration

- src/payment/models/dex/services/dex-defichain.service.ts
- src/payment/models/dex/strategies/purchase-liquidity/base/purchase-liquidity-defichain-non-poolpair.strategy.ts
- src/user/services/spider/spider-sync.service.ts
> Improved Logging

- src/payment/models/bank-tx-return/bank-tx-return.controller.ts
- src/payment/models/bank-tx-return/bank-tx-return.service.ts
- src/payment/models/bank-tx-return/dto/update-bank-tx-return.dto.ts
- src/payment/models/bank-tx/bank-tx.service.ts
- src/payment/models/bank-tx/dto/update-bank-tx.dto.ts
- src/payment/payment.module.ts
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
> [DEV-862] bankTxReturn update method

- src/payment/models/bank-tx-return/bank-tx-return.controller.ts
- src/payment/models/bank-tx-return/bank-tx-return.service.ts
- src/payment/models/bank-tx-return/dto/update-bank-tx-return.dto.ts
- src/payment/models/bank-tx/bank-tx.service.ts
- src/payment/models/bank-tx/dto/update-bank-tx.dto.ts
- src/payment/models/dex/services/dex-defichain.service.ts
- src/payment/models/dex/strategies/purchase-liquidity/base/purchase-liquidity-defichain-non-poolpair.strategy.ts
- src/payment/payment.module.ts
- src/user/services/spider/spider-sync.service.ts
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
> [DEV-862] bankTxReturn update, Improved logging

- migration/1665740859063-amountInColsBankTxReturn.js
- src/payment/models/bank-tx-return/bank-tx-return.entity.ts
- src/payment/models/bank-tx-return/dto/update-bank-tx-return.dto.ts
- thunder-tests/thunderclient.json
> [DEV-885] amountIn Cols bankTxReturn

- src/blockchain/shared/evm/evm-client.ts
> [DEV-833] EVM Token input decimal calculation

- src/admin/admin.controller.ts
- src/admin/dto/db-query.dto.ts
> [DEV-868] add custom col parameter

- src/payment/models/payout/services/payout-bitcoin.service.ts
> [DEV-622] Payout confirmation fix for BTC

- src/payment/models/payout/services/payout-bitcoin.service.ts
> [DEV-622] Payout confirmation fix for BTC (#459)

- src/user/services/spider/spider-sync.service.ts
> [DEV-864] Add part to completed requirement and also to fallback

- src/user/services/spider/spider.service.ts
> [DEV-808] Add contribution '0' to business account

- src/statistic/statistic.service.ts
> [DEV-759] Round statistic values to 2 decimals

- src/payment/models/buy-crypto/services/buy-crypto-notification.service.ts
- src/payment/models/buy-fiat/buy-fiat-notification.service.ts
- src/payment/models/buy-fiat/buy-fiat.entity.ts
> [DEV-902] add buyFiat Pending Mail

- src/payment/models/buy-crypto/enums/aml-reason.enum.ts
- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
> [DEV-946] add amlReason

- src/payment/models/crypto-input/btc-input.service.ts
- src/payment/models/sell/dto/create-sell.dto.ts
- src/payment/models/sell/dto/get-sell-payment-info.dto.ts
- src/payment/models/sell/dto/sell-payment-info.dto.ts
- src/payment/models/sell/dto/sell.dto.ts
- src/payment/models/sell/sell.controller.ts
- src/payment/models/sell/sell.service.ts
> [DEV-909] Add blockchain to CreateSellDto and add buyFiat to btc-input

- src/app.controller.ts
- src/main.ts
- src/payment/models/crypto-input/btc-input.service.ts
- src/payment/models/sell/dto/create-sell.dto.ts
- src/payment/models/sell/dto/get-sell-payment-info.dto.ts
- src/payment/models/sell/dto/sell-payment-info.dto.ts
- src/payment/models/sell/dto/sell.dto.ts
- src/payment/models/sell/sell.controller.ts
- src/payment/models/sell/sell.service.ts
- src/shared/services/dfi-tax.service.ts
- src/user/models/user-data/user-data.service.ts
> BTC Off-Ramp

- src/payment/models/crypto-input/btc-input.service.ts
> [DEV-909] Fix get deposit route for sell routes

- migration/1666347510059-DepositLimitDefaultNull.js
- src/config/config.ts
- src/user/models/kyc/kyc.service.ts
- src/user/models/user-data/user-data.entity.ts
- src/user/models/user/dto/user.dto.ts
- src/user/models/user/user.controller.ts
- src/user/models/user/user.service.ts
> [DEV-835] New Deposit Limit

- migration/1666347510059-DepositLimitDefaultNull.js
- migration/1666880270785-AddNullableForwardFeeAmount.js
- src/blockchain/ain/node/btc-client.ts
- src/blockchain/ain/node/defi-client.ts
- src/config/config.ts
- src/payment/models/crypto-input/btc-input.service.ts
- src/payment/models/crypto-input/crypto-input.entity.ts
- src/payment/models/crypto-input/defi-input.service.ts
- src/user/models/kyc/kyc.service.spec.ts
- src/user/models/kyc/kyc.service.ts
- src/user/models/user-data/__mocks__/user-data.entity.mock.ts
- src/user/models/user-data/user-data.entity.ts
- src/user/models/user/dto/user.dto.ts
- src/user/models/user/user.controller.ts
- src/user/models/user/user.service.ts
> [DEV-909], [DEV-835] & [DEV-615] Fix get deposit route for sell routes, New deposit limits and btc fee to crypto input

- src/admin/admin.controller.ts
> [FIX] add missing cols

- src/admin/admin.controller.ts
- src/blockchain/ain/node/defi-client.ts
> [HOTXFIX] DeFiChain Inputs

- src/payment/models/history/history.service.ts
> [DEV-963] fix CT duplicate txid

- src/user/models/user/user.service.ts
> [DEV-991] filter kyc addresses from linked addresses

- src/payment/models/crypto-input/defi-input.service.ts
> Improved DeFiChain Inputs

- src/payment/models/payout/strategies/payout/impl/base/jellyfish.strategy.ts
> [DEV-728] implemented proper payout fee distribution between orders

- src/payment/models/crypto-staking/crypto-staking.controller.ts
- src/payment/models/crypto-staking/crypto-staking.service.ts
- src/payment/models/crypto-staking/dto/update-output-date.dto.ts
> [DEV-992] add manual payout

- src/admin/admin.controller.ts
- src/shared/auth/role.guard.ts
- src/shared/auth/user-role.enum.ts
> [DEV-682] add Support Role

- src/payment/models/history/history.service.ts
> [DEV-728] Optional check for outputAsset in history

- src/admin/admin.controller.ts
- src/admin/dto/send-mail.dto.ts
> [FIX] fix admin mail route

- src/payment/models/buy/buy.controller.ts
- src/payment/models/sell/dto/get-sell-payment-info.dto.ts
- src/payment/models/sell/sell.controller.ts
> [DEV-1013] set fee 0 for crypto asset

- src/payment/models/buy-crypto/services/buy-crypto-batch.service.ts
- src/payment/models/dex/services/dex-defichain.service.ts
- src/payment/models/dex/strategies/check-liquidity/__tests__/check-liquidity.facade.spec.ts
- src/payment/models/dex/strategies/check-liquidity/impl/defichain-poolpair.strategy.ts
- src/payment/models/dex/strategies/check-liquidity/utils/check-liquidity.util.ts
> [DEV-728] Max purchasable liquidity reference check for pool pairs

- src/subdomains/supporting/dex/services/dex.service.ts
- src/subdomains/supporting/dex/strategies/check-liquidity/impl/base/check-liquidity.strategy.ts
- src/subdomains/supporting/dex/strategies/purchase-liquidity/impl/base/purchase-liquidity.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/base/payout.strategy.ts
- src/subdomains/supporting/payout/strategies/prepare/impl/base/prepare.strategy.ts
> Fixed access modifier for feeAsset, didn't work for pool pair at runtime

- src/subdomains/generic/user/services/spider/spider-sync.service.ts
> [FIX] deactivate external reminder kyc mail

- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.repository.ts
- src/subdomains/generic/user/models/user/user.service.ts
> [DEV-845] activate users when merging

- src/subdomains/supporting/pricing/utils/price-step.ts
> [CHANGE] Change math threshold of mathing price from 0.5% to 1%

- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.repository.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/pricing/utils/price-step.ts
> [DEV-845] & [CHANGE] Activate user & change default threshold for pricing

- migration/1668150169114-AddKycType.js
- src/subdomains/generic/user/models/kyc/kyc-process.service.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
> [DEV-1034] Add kycType column and set it at kyc start

- migration/1668435876824-removeUnusedBankDataCols.js
- src/subdomains/generic/admin/admin.controller.ts
- src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
- src/subdomains/generic/user/models/bank-data/dto/bank-data.dto.ts
> [DEV-153] remove unused bankData cols + migration

- src/subdomains/core/statistic/assets/cfp-results.json
- src/subdomains/core/statistic/cfp.service.spec.ts
> [UPDATE] Add new mn snapshot

- migration/1668437287846-removeUnusedBuyCryptoCols.js
- migration/1668517587302-removeUnusedBuyCryptoCols.js
- src/mix/models/crypto-route/crypto-route.entity.ts
- src/subdomains/generic/admin/admin.controller.ts
> [DEV-1044] remove unuesed buyCrypto Cols + migration

- migration/1668519616316-addCustomKyc.js
- src/config/config.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
- src/subdomains/generic/user/models/wallet/wallet.entity.ts
> [DEV-1050] add customKyc Col + migration

- .github/workflows/api-pr.yaml
- migration/1668150169114-AddKycType.js
- migration/1668435876824-removeUnusedBankDataCols.js
- migration/1668517587302-removeUnusedBuyCryptoCols.js
- migration/1668519616316-addCustomKyc.js
- src/config/config.ts
- src/mix/models/crypto-input/defi-input.service.ts
- src/mix/models/crypto-route/crypto-route.entity.ts
- src/subdomains/core/statistic/assets/cfp-results.json
- src/subdomains/core/statistic/cfp.service.spec.ts
- src/subdomains/generic/admin/admin.controller.ts
- src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
- src/subdomains/generic/user/models/bank-data/dto/bank-data.dto.ts
- src/subdomains/generic/user/models/kyc/kyc-process.service.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
- src/subdomains/generic/user/models/user-data/__mocks__/user-data.entity.mock.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/wallet/wallet.entity.ts
> [DEV-1034] & [DEV-1044] & [DEV-153] add kycType, bankData/buyCrypto Refactoring

- migration/1668509150637-statusInBuyCrypto.js
- src/subdomains/core/buy-crypto/process/entities/buy-crypto-batch.entity.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/exceptions/fee-limit-exceeded.exception.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/supporting/dex/strategies/check-liquidity/impl/defichain-poolpair.strategy.ts
- src/subdomains/supporting/dex/strategies/purchase-liquidity/impl/defichain-poolpair.strategy.ts
- src/subdomains/supporting/dex/strategies/purchase-liquidity/impl/defichain-stock.strategy.ts
- src/subdomains/supporting/dex/utils/dex.util.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
- src/subdomains/supporting/pricing/utils/price-step.ts
- src/subdomains/supporting/pricing/utils/pricing.util.ts
> [DEV-1015], [DEV-1033], [DEV-1048] Poolpair liquidity check adjustments and other improvements

- src/subdomains/generic/user/models/kyc/kyc-webhook.service.ts
- src/subdomains/generic/user/models/limit-request/limit-request.entity.ts
- src/subdomains/generic/user/models/limit-request/limit-request.service.ts
> [DEV-1035] add tradingLimit in Webhook

- migration/1668509150637-statusInBuyCrypto.js
- src/subdomains/core/buy-crypto/process/entities/buy-crypto-batch.entity.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/exceptions/fee-limit-exceeded.exception.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/generic/user/models/kyc/kyc-webhook.service.ts
- src/subdomains/generic/user/models/limit-request/limit-request.entity.ts
- src/subdomains/generic/user/models/limit-request/limit-request.service.ts
- src/subdomains/supporting/bank/bank-tx/bank-tx.entity.ts
- src/subdomains/supporting/dex/strategies/check-liquidity/impl/defichain-poolpair.strategy.ts
- src/subdomains/supporting/dex/strategies/purchase-liquidity/impl/defichain-poolpair.strategy.ts
- src/subdomains/supporting/dex/strategies/purchase-liquidity/impl/defichain-stock.strategy.ts
- src/subdomains/supporting/dex/utils/dex.util.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
- src/subdomains/supporting/pricing/utils/price-step.ts
- src/subdomains/supporting/pricing/utils/pricing.util.ts
> [DEV-1015], [DEV-1033], [DEV-1048], [DEV-1079], [DEV-1080] poolpair liquidity adjustment

- migration/1668788080022-newBankTxRepeatCols.js
- src/subdomains/supporting/bank/bank-tx-repeat/bank-tx-repeat.controller.ts
- src/subdomains/supporting/bank/bank-tx-repeat/bank-tx-repeat.entity.ts
- src/subdomains/supporting/bank/bank-tx-repeat/bank-tx-repeat.service.ts
- src/subdomains/supporting/bank/bank-tx-repeat/dto/update-bank-tx-repeat.dto.ts
> [DEV-1077] add new bankTxRepeat cols

- migration/1668697486667-newCountryEnableCol.js
- src/shared/models/country/__mocks__/country.entity.mock.ts
- src/shared/models/country/country.entity.ts
- src/shared/models/country/country.service.ts
- src/subdomains/generic/user/models/kyc/kyc.controller.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
- src/subdomains/generic/user/models/user-data/__mocks__/user-data.entity.mock.ts
> [DEV-1067]&[DEV-995] add adaptive country list

- src/subdomains/generic/user/models/kyc/kyc-process.service.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/generic/user/services/spider/spider-sync.service.ts
> [DEV-1066] improve kyc

- src/subdomains/generic/admin/admin.controller.ts
- src/subdomains/generic/admin/admin.module.ts
- src/subdomains/supporting/bank/bank-tx-repeat/bank-tx-repeat.service.ts
- src/subdomains/supporting/bank/bank.module.ts
> [DEV-1081] extend support route

- src/shared/models/country/country.controller.ts
- src/shared/models/country/country.dto.ts
> Country Enable

- src/subdomains/core/statistic/assets/cfp-results.json
> [UPDATE] Add votes 2211

- src/subdomains/supporting/dex/strategies/sell-liquidity/impl/base/sell-liquidity.strategy.ts
> [DEV-384] Re-throwing sell liquidity error

- src/subdomains/supporting/dex/strategies/sell-liquidity/impl/defichain-coin.strategy.ts
- src/subdomains/supporting/dex/strategies/sell-liquidity/impl/defichain-token.strategy.ts
> [DEV-384] Awaiting on error handling

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/config/config.ts
- src/integration/blockchain/ain/node/node.service.ts
- src/integration/infrastructure/azure-service.ts
- src/integration/integration.module.ts
- src/shared/utils/util.ts
- src/subdomains/core/monitoring/monitoring.module.ts
- src/subdomains/core/monitoring/observers/node-health.observer.ts
> [DEV-993] Node Restart

- src/integration/blockchain/ain/node/node-client.ts
- src/shared/utils/queue-handler.ts
- src/subdomains/core/monitoring/observers/staking-balance.observer.ts
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
> Queue Handler Fix

- migration/1669303590842-addLogTable.js
- src/subdomains/subdomains.module.ts
- src/subdomains/supporting/log/dto/create-log.dto.ts
- src/subdomains/supporting/log/log.controller.ts
- src/subdomains/supporting/log/log.entity.ts
- src/subdomains/supporting/log/log.module.ts
- src/subdomains/supporting/log/log.repository.ts
- src/subdomains/supporting/log/log.service.ts
> [DEV-373] add log table + migration

- src/subdomains/generic/user/models/limit-request/limit-request.service.ts
- src/subdomains/supporting/notification/enums/index.ts
- src/subdomains/supporting/notification/factories/mail.factory.ts
> [DEV-1109] LimitRequest internal mails

- src/subdomains/supporting/dex/strategies/purchase-liquidity/impl/defichain-poolpair.strategy.ts
> Hotfix - pool pair parent order failure handling

- migration/1669303590842-addLogTable.js
- src/shared/auth/optional.guard.ts
- src/shared/models/asset/asset.controller.ts
- src/shared/models/asset/asset.service.ts
- src/subdomains/core/liquidity-management/adapters/balances/blockchain.adapter.ts
- src/subdomains/core/liquidity-management/dto/input/liquidity-management-rule-creation.dto.ts
- src/subdomains/core/liquidity-management/entities/liquidity-management-rule.entity.ts
- src/subdomains/core/liquidity-management/services/liquidity-management-balance.service.ts
- src/subdomains/core/liquidity-management/specifications/liquidity-management-rule-init.specification.ts
- src/subdomains/generic/user/models/limit-request/limit-request.service.ts
- src/subdomains/subdomains.module.ts
- src/subdomains/supporting/dex/strategies/purchase-liquidity/impl/defichain-poolpair.strategy.ts
- src/subdomains/supporting/log/dto/create-log.dto.ts
- src/subdomains/supporting/log/log.controller.ts
- src/subdomains/supporting/log/log.entity.ts
- src/subdomains/supporting/log/log.module.ts
- src/subdomains/supporting/log/log.repository.ts
- src/subdomains/supporting/log/log.service.ts
- src/subdomains/supporting/notification/enums/index.ts
- src/subdomains/supporting/notification/factories/mail.factory.ts
- thunder-tests/thunderclient.json
> [DEV-373], [DEV-1109], [DEV-1106] logs, mail, api and liquidity management improvements

- migration/1669832431098-AddFeeTier.js
- src/app.controller.ts
- src/config/config.ts
- src/shared/models/asset/asset.entity.ts
- src/subdomains/core/buy-crypto/route/buy.controller.ts
- src/subdomains/core/buy-crypto/route/dto/buy-payment-info.dto.ts
- src/subdomains/core/buy-crypto/route/dto/buy.dto.ts
- src/subdomains/core/sell-crypto/sell/sell.controller.ts
- src/subdomains/generic/user/models/user/dto/update-user.dto.ts
- src/subdomains/generic/user/models/user/user.entity.ts
- src/subdomains/generic/user/models/user/user.service.spec.ts
- src/subdomains/generic/user/models/user/user.service.ts
> [DEV-1116] New fees and ref

- src/subdomains/generic/user/models/kyc/dto/kyc-webhook-trigger.dto.ts
- src/subdomains/generic/user/models/kyc/kyc.controller.ts
- src/subdomains/generic/user/models/kyc/kyc.service.spec.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
> KYC Webhook Trigger

- migration/1669716170239-addBuyFiatRefCols.js
- src/subdomains/core/buy-crypto/buy-crypto.module.ts
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/buy-fiat/__tests__/buy-fiat.service.spec.ts
- src/subdomains/core/sell-crypto/buy-fiat/buy-fiat.controller.ts
- src/subdomains/core/sell-crypto/buy-fiat/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/buy-fiat/buy-fiat.service.ts
- src/subdomains/core/sell-crypto/buy-fiat/dto/update-buy-fiat.dto.ts
- src/subdomains/core/sell-crypto/sell-crypto.module.ts
> [DEV-1118] add buyFiat ref cols + new fee calculation

- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
> [FIX] fix outputAsset name in mails

- src/subdomains/core/liquidity-management/adapters/balances/blockchain.adapter.ts
- src/subdomains/core/liquidity-management/services/liquidity-management-balance.service.ts
> [NOTASK] improved promise rejection on getting balances for LM

- src/config/config.ts
- src/subdomains/core/buy-crypto/route/buy.controller.ts
- src/subdomains/core/sell-crypto/sell/sell.controller.ts
- thunder-tests/thunderclient.json
> [DEV-1127] minDeposit Refactoring + minDeposit btc

- src/config/config.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/buy-crypto/route/buy.controller.ts
- src/subdomains/core/sell-crypto/sell/sell.controller.ts
- src/subdomains/generic/user/models/kyc/kyc.controller.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
- thunder-tests/thunderclient.json
> [NOTASK]&[DEV-1127] Liquidity management cache error handing

- src/subdomains/generic/generic.module.ts
- src/subdomains/generic/gs/dto/db-query.dto.ts
- src/subdomains/generic/gs/dto/support-return-data.dto.ts
- src/subdomains/generic/gs/gs.controller.ts
- src/subdomains/generic/gs/gs.module.ts
- src/subdomains/generic/gs/gs.service.ts
> [DEV-1087] add GS route

- src/shared/services/http.service.ts
- src/subdomains/generic/user/models/kyc/kyc-webhook.service.ts
> [DEV-1130] webhook retry

- src/shared/services/http.service.ts
- src/subdomains/core/sell-crypto/sell/dto/get-sell-payment-info.dto.ts
- src/subdomains/generic/generic.module.ts
- src/subdomains/generic/gs/dto/db-query.dto.ts
- src/subdomains/generic/gs/dto/support-return-data.dto.ts
- src/subdomains/generic/gs/gs.controller.ts
- src/subdomains/generic/gs/gs.module.ts
- src/subdomains/generic/gs/gs.service.ts
- src/subdomains/generic/user/models/kyc/kyc-webhook.service.ts
- src/subdomains/supporting/bank/fiat-output/fiat-output.service.ts
- thunder-tests/thunderclient.json
> [DEV-1087],[DEV-1130],[FIX] GS route, webhook retry, fix fiat output

- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
> [FIX] buyCrypto history fix

- src/subdomains/generic/user/models/user/dto/update-user.dto.ts
- src/subdomains/generic/user/models/user/dto/user.dto.ts
- src/subdomains/generic/user/models/user/user.service.ts
> [DEV-1150] Remove update of used ref

- src/subdomains/generic/user/models/kyc/kyc-process.service.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
> [DEV-1161] remove kycStatus manual

- src/subdomains/core/buy-crypto/route/buy.service.ts
- src/subdomains/core/sell-crypto/sell/sell.service.ts
- src/subdomains/generic/gs/dto/support-data.dto.ts
- src/subdomains/generic/gs/gs.controller.ts
- src/subdomains/generic/gs/gs.module.ts
- src/subdomains/generic/gs/gs.service.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/bank/bank-account/bank-account.service.ts
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
> [DEV-1110] advanced support route

- src/subdomains/core/buy-crypto/route/buy.service.ts
- src/subdomains/core/sell-crypto/sell/sell.service.ts
- src/subdomains/generic/gs/dto/support-data.dto.ts
- src/subdomains/generic/gs/gs.controller.ts
- src/subdomains/generic/gs/gs.module.ts
- src/subdomains/generic/gs/gs.service.ts
- src/subdomains/generic/user/models/kyc/kyc-process.service.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user/dto/update-user.dto.ts
- src/subdomains/generic/user/models/user/dto/user.dto.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/bank/bank-account/bank-account.service.ts
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
> [DEV-1150] & [DEV-1161] Remove update of used ref & kycStatus manual

- src/app.controller.ts
- src/main.ts
- src/subdomains/core/referral/process/ref.repository.ts
- src/subdomains/core/referral/process/ref.service.ts
- thunder-tests/thunderclient.json
> [DEV-1149] New Ref Links

- migration/1671067435892-addBankSctInst.js
- src/subdomains/core/buy-crypto/route/buy.controller.ts
- src/subdomains/core/buy-crypto/route/dto/buy-payment-info.dto.ts
- src/subdomains/supporting/bank/bank/bank.entity.ts
> [DEV-1196] add sepaInstant to paymentInfos

- src/integration/exchange/services/exchange.service.ts
> [DEV-1188] Exchange Pricing

- src/shared/utils/util.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/buy-crypto/route/buy.service.ts
- src/subdomains/core/buy-crypto/route/dto/create-buy.dto.ts
- src/subdomains/core/buy-crypto/route/dto/get-buy-payment-info.dto.ts
- src/subdomains/core/sell-crypto/buy-fiat/buy-fiat-notification.service.ts
- src/subdomains/core/sell-crypto/sell/dto/create-sell.dto.ts
- src/subdomains/core/sell-crypto/sell/dto/get-sell-payment-info.dto.ts
- src/subdomains/core/sell-crypto/sell/sell.service.ts
- src/subdomains/generic/user/models/bank-data/dto/bank-data.dto.ts
- src/subdomains/supporting/bank/bank-account/bank-account.service.ts
- src/subdomains/supporting/bank/bank-account/dto/create-bank-account.dto.ts
> [DEV-1201] fixes issue with double creation

- migration/1671119109834-ExpandFiatOutputTable.js
- src/subdomains/supporting/bank/bank-tx/frick.service.ts
- src/subdomains/supporting/bank/fiat-output/dto/update-fiat-output.dto.ts
- src/subdomains/supporting/bank/fiat-output/fiat-output.controller.ts
- src/subdomains/supporting/bank/fiat-output/fiat-output.entity.ts
- src/subdomains/supporting/bank/fiat-output/fiat-output.service.ts
> [DEV-694] Expand fiatOutput table

- migration/1671210355232-MovedBankAccountsToUserData.js
- src/subdomains/generic/gs/gs.service.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user/user.entity.ts
- src/subdomains/supporting/bank/bank-account/__mocks__/bank-account.entity.mock.ts
- src/subdomains/supporting/bank/bank-account/bank-account.entity.ts
- src/subdomains/supporting/bank/bank-account/bank-account.service.ts
- src/subdomains/supporting/bank/bank.module.ts
> [DEV-1203] Bank Accounts on User Data

- src/subdomains/core/history/history.controller.ts
- src/subdomains/generic/user/models/kyc/kyc.service.spec.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
- src/subdomains/generic/user/models/link/link.service.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.controller.ts
- src/subdomains/generic/user/models/user/user.service.ts
> [DEV-1217] Send address link mail on email update

- src/integration/exchange/exchange.controller.ts
- src/integration/exchange/services/exchange.service.spec.ts
- src/integration/exchange/services/exchange.service.ts
- thunder-tests/thunderclient.json
> [DEV-1216] Trade API

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-pricing.service.ts
- src/subdomains/supporting/pricing/services/dfi-pricing-dex.service.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
> [NOTASK] DFI EVM pricing fix

- src/subdomains/supporting/bank/bank-account/bank-account.service.ts
> [FIX] Select Preferred Currency

- package-lock.json
- package.json
- src/mix/models/crypto-input/crypto-input.entity.ts
- src/mix/models/crypto-input/defi-input.service.spec.ts
- src/mix/models/crypto-input/defi-input.service.ts
- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
> [DEV-1152] updated package, return staking deposits

- src/subdomains/generic/gs/dto/support-data.dto.ts
- src/subdomains/generic/gs/gs.service.ts
> [FIX] add userData in support route

- migration/1672501910578-fiatOutputAmountType.js
- src/subdomains/supporting/bank/fiat-output/fiat-output.entity.ts
> [DEV-1236] change fiatOutput amount type

- migration/1672501910578-fiatOutputAmountType.js
- src/subdomains/supporting/bank/fiat-output/fiat-output.entity.ts
> [DEV-1236] change fiatOutput amount type (#584)

- migration/1672830459527-bankTxNewFeeCols.js
- src/subdomains/supporting/bank/bank-tx/bank-tx.entity.ts
- src/subdomains/supporting/bank/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/bank/bank-tx/dto/update-bank-tx.dto.ts
> [DEV-1238] add bankTx Fee col

- migration/1672830459527-bankTxNewFeeCols.js
- src/subdomains/supporting/bank/bank-tx/bank-tx.entity.ts
- src/subdomains/supporting/bank/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/bank/bank-tx/dto/update-bank-tx.dto.ts
* [DEV-1238] add bankTx Fee col
* [DEV-1238] Refactoring
* [DEV-1238] allow updating
* [DEV-1238] remove unused import
- Login/logout
- Registration
[DEV-1238]: https://dfxswiss.atlassian.net/browse/DEV-1238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1238]: https://dfxswiss.atlassian.net/browse/DEV-1238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1238]: https://dfxswiss.atlassian.net/browse/DEV-1238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> [DEV-1238] add bankTx Fee col (#586)

- migration/1673260380636-unique-asset-name.js
- src/shared/models/asset/asset.entity.ts
- src/subdomains/core/buy-crypto/route/buy.service.ts
> [DEV-1190] added unique name, description and comingSoon flag to asset

- migration/1673260380636-unique-asset-name.js
- src/config/config.ts
- src/integration/blockchain/shared/enums/blockchain.enum.ts
- src/integration/blockchain/shared/evm/evm-client.ts
- src/shared/models/asset/asset.entity.ts
- src/subdomains/core/buy-crypto/route/buy.service.ts
- src/subdomains/core/sell-crypto/buy-fiat/buy-fiat.entity.ts
- src/subdomains/generic/gs/gs.service.ts
> [DEV-1234]&[FIX] bankTx extended fix, mail fix

- src/integration/blockchain/ain/node/node.service.ts
- src/subdomains/core/monitoring/observers/node-health.observer.ts
> [NOTASK] Re-implemented node-health observer email fix, same as in Lock

- src/shared/auth/role.guard.ts
- src/shared/auth/user-role.enum.ts
> [DEV-1258] add compliance role

- migration/1673605795897-CryptoInputTxType.js
- src/mix/models/crypto-input/crypto-input.entity.ts
- src/mix/models/crypto-input/defi-input.service.ts
> [FIX] Removed balance check, added block reward delay

- src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/buy-fiat/buy-fiat.service.ts
- src/subdomains/generic/user/services/webhook/webhook.service.ts
> [DEV-1256] payment webhook only for specific user

- src/subdomains/generic/admin/admin.controller.ts
- src/subdomains/generic/user/services/spider/dto/spider.dto.ts
- src/subdomains/generic/user/services/spider/spider-api.service.ts
- src/subdomains/generic/user/services/spider/spider.service.ts
- thunder-tests/thunderclient.json
> [NO-TASK] Document info API

- migration/1673962395406-bankTxNewFeeChfCols.js
- src/subdomains/supporting/bank/bank-tx/bank-tx.entity.ts
- src/subdomains/supporting/bank/bank-tx/dto/update-bank-tx.dto.ts
> [DEV-1277] add bankTx chf fee col

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/config/config.ts
- Login/logout
- Registration
- Add ApiKey to env
> [DEV-1261] add talium apiKey

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- migration/1673907649562-AddIsCompleteFiatOutput.js
- migration/1673941417695-bank-account-active.js
- migration/1673962395406-bankTxNewFeeChfCols.js
- src/config/config.ts
- src/integration/blockchain/ain/services/crypto.service.ts
- src/mix/models/crypto-input/btc-input.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/buy-fiat/buy-fiat.service.ts
- src/subdomains/generic/admin/admin.controller.ts
- src/subdomains/generic/user/models/auth/auth.controller.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/services/spider/dto/spider.dto.ts
- src/subdomains/generic/user/services/spider/spider-api.service.ts
- src/subdomains/generic/user/services/spider/spider.service.ts
- src/subdomains/generic/user/services/webhook/webhook.service.ts
- src/subdomains/supporting/bank/bank-account/bank-account.controller.ts
- src/subdomains/supporting/bank/bank-account/bank-account.entity.ts
- src/subdomains/supporting/bank/bank-account/bank-account.service.ts
- src/subdomains/supporting/bank/bank-account/dto/bank-account.dto.ts
- src/subdomains/supporting/bank/bank-account/dto/update-bank-account.dto.ts
- src/subdomains/supporting/bank/bank-tx/bank-tx.entity.ts
- src/subdomains/supporting/bank/bank-tx/dto/update-bank-tx.dto.ts
- src/subdomains/supporting/bank/fiat-output/dto/update-fiat-output.dto.ts
- src/subdomains/supporting/bank/fiat-output/fiat-output.entity.ts
- thunder-tests/thunderclient.json
- Login/logout
- Registration
- add apiKey to env
> [DEV-1256 & DEV-1271] Bank accounts, payment webhooks fix + various improvements

- src/integration/blockchain/ain/node/defi-client.ts
- src/integration/blockchain/ain/utils/defichain.util.ts
- src/mix/models/crypto-input/defi-input.service.spec.ts
- src/mix/models/crypto-input/defi-input.service.ts
> [FIX] Fixed blockReward inputs

- README.md
- src/integration/blockchain/ain/node/defi-client.ts
- src/integration/blockchain/ain/utils/defichain.util.ts
- src/mix/models/crypto-input/defi-input.service.spec.ts
- src/mix/models/crypto-input/defi-input.service.ts
- src/subdomains/core/history/history.service.ts
> [FIX] Fixed blockReward inputs (#606)

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/config/config.ts
- src/mix/models/crypto-input/btc-input.service.ts
…lletAddress
- Login/logout
- Registration
> [DEV-1276] Remove btcCollectorAddress and send BTC inputs to btcOutWallet

- src/subdomains/supporting/pricing/enums/index.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
- src/subdomains/supporting/pricing/utils/pricing.util.ts
> [NO-TASK] Added BTCB to pricing service

- .github/workflows/api-dev.yaml
- .github/workflows/api-pr.yaml
- .github/workflows/api-prd.yaml
- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/config/config.ts
- src/mix/models/crypto-input/btc-input.service.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/supporting/pricing/enums/index.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
- src/subdomains/supporting/pricing/utils/pricing.util.ts
> [DEV-1276] BTC collector + BTCB pricing

- src/subdomains/supporting/bank/bank-tx/frick.service.ts
- src/subdomains/supporting/bank/bank-tx/olkypay.service.ts
> [FIX] read transaction bank frick if aba is undefined

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/supporting/bank/bank-tx/frick.service.ts
- src/subdomains/supporting/bank/bank-tx/olkypay.service.ts
> [FIX] ETH as reference asset on BSC

- src/subdomains/generic/user/services/spider/spider-api.service.ts
> [FIX] Fixed spider document URL

- src/subdomains/core/statistic/assets/cfp-results.json
> [DEV-1255] Add dfiAmount to CFP 2211-15

- src/subdomains/supporting/pricing/services/pricing.service.ts
- src/subdomains/supporting/pricing/specifications/__tests__/price-step-init.specification.spec.ts
- src/subdomains/supporting/pricing/specifications/price-step-init.specification.ts
- src/subdomains/supporting/pricing/utils/__mocks__/price-step.mock.ts
- src/subdomains/supporting/pricing/utils/price-step.ts
> [DEV-1284] Extended price path options

- src/subdomains/supporting/bank/bank-tx/frick.service.ts
> [FIX] Fix parsing bank frick transactions

- src/subdomains/supporting/bank/bank-tx/bank-tx.service.ts
> [FIX] Use seperated settingKeys for the different banks

- src/subdomains/core/statistic/assets/cfp-results.json
- src/subdomains/supporting/bank/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/bank/bank-tx/frick.service.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
- src/subdomains/supporting/pricing/specifications/__tests__/price-step-init.specification.spec.ts
- src/subdomains/supporting/pricing/specifications/price-step-init.specification.ts
- src/subdomains/supporting/pricing/utils/__mocks__/price-step.mock.ts
- src/subdomains/supporting/pricing/utils/price-step.ts
> Various Fixes

- src/subdomains/supporting/bank/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/bank/bank-tx/frick.service.ts
> [FIX] Bank import fix for bank frick

- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/supporting/dex/services/dex-defichain.service.ts
> [NO-TASK] More debug logs

- package-lock.json
- package.json
- src/subdomains/core/buy-crypto/route/dto/create-buy.dto.ts
- src/subdomains/core/buy-crypto/route/dto/get-buy-payment-info.dto.ts
- src/subdomains/core/sell-crypto/sell/dto/create-sell.dto.ts
- src/subdomains/core/sell-crypto/sell/dto/get-sell-payment-info.dto.ts
- src/subdomains/generic/user/models/bank-data/dto/bank-data.dto.ts
- src/subdomains/supporting/bank/bank-account/bank-account.service.ts
- src/subdomains/supporting/bank/bank-account/dto/create-bank-account.dto.ts
- src/subdomains/supporting/bank/bank-account/is-dfx-iban.validator.ts
> [DEV-803] add ibanValidator, validate iban country

- src/subdomains/core/sell-crypto/sell/__tests__/sell.controller.spec.ts
- src/subdomains/core/sell-crypto/sell/sell.controller.ts
- src/subdomains/supporting/bank/bank-tx/olkypay.service.ts
> BTC min. deposit

- migration/1674646766576-fiatOutputBankTxChange.js
- src/subdomains/core/history/history.service.ts
- src/subdomains/core/sell-crypto/buy-fiat/__tests__/buy-fiat.service.spec.ts
- src/subdomains/core/sell-crypto/buy-fiat/buy-fiat-notification.service.ts
- src/subdomains/core/sell-crypto/buy-fiat/buy-fiat.service.ts
- src/subdomains/supporting/bank/fiat-output/__mocks__/fiat-output.entity.mock.ts
- src/subdomains/supporting/bank/fiat-output/fiat-output.entity.ts
- src/subdomains/supporting/bank/fiat-output/fiat-output.service.ts
> [DEV-1275] fix buyFiat Mails + history

- src/subdomains/core/sell-crypto/buy-fiat/buy-fiat-notification.service.ts
> [FIX] fix buyFiat Mail bug

- src/mix/models/crypto-route/dto/__mocks__/crypto-history.dto.mock.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/buy-crypto/route/dto/__mocks__/buy-history.dto.mock.ts
- src/subdomains/core/history/dto/history.dto.ts
- src/subdomains/core/sell-crypto/buy-fiat/__tests__/buy-fiat.service.spec.ts
- src/subdomains/core/sell-crypto/buy-fiat/buy-fiat.service.ts
- src/subdomains/core/sell-crypto/sell/dto/__mocks__/sell-history.dto.mock.ts
> [NO-TASK] Add txUrl to HistoryDto

- src/subdomains/core/statistic/cfp.service.ts
- src/subdomains/core/statistic/dto/cfp.dto.ts
* [DEV-1295] Change cfp api to on chain
* [NO-TASK] Change daily limit to 990
* [DEV-1295] Fix currentResult
* [DEV-1295] Refactoring
* [DEV-1295] add creationHeight
* [DEV-1295] add creationHeight
---------
Co-authored-by: Kolibri <daniel@dfx.swiss>
- Login/logout
- Registration
[DEV-1295]: https://dfxswiss.atlassian.net/browse/DEV-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1295]: https://dfxswiss.atlassian.net/browse/DEV-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1295]: …
> [DEV-1295] cfp api (#639)

- src/integration/exchange/services/binance.service.ts
- src/integration/exchange/services/bitpanda.service.ts
- src/integration/exchange/services/bitstamp.service.ts
- src/integration/exchange/services/exchange.service.spec.ts
- src/integration/exchange/services/exchange.service.ts
- src/integration/exchange/services/ftx.service.ts
- src/integration/exchange/services/kraken.service.ts
> [DEV-1294] Added queue to exchange service

- src/app.controller.ts
- src/config/config.ts
- src/subdomains/generic/user/models/auth/dto/auth-credentials.dto.ts
- src/subdomains/generic/user/models/user/dto/create-user.dto.ts
- src/subdomains/generic/user/models/user/dto/linked-user.dto.ts
> [NO-TASK] Fixed ref codes for store API

- src/app.controller.ts
- src/config/config.ts
- src/integration/exchange/services/binance.service.ts
- src/integration/exchange/services/bitpanda.service.ts
- src/integration/exchange/services/bitstamp.service.ts
- src/integration/exchange/services/exchange.service.spec.ts
- src/integration/exchange/services/exchange.service.ts
- src/integration/exchange/services/ftx.service.ts
- src/integration/exchange/services/kraken.service.ts
- src/subdomains/generic/user/models/auth/dto/auth-credentials.dto.ts
- src/subdomains/generic/user/models/user/dto/create-user.dto.ts
- src/subdomains/generic/user/models/user/dto/linked-user.dto.ts
> [DEV-1294] Exchange queue + ref code fix

- src/subdomains/supporting/pricing/services/pricing.service.ts
> [NO-TASK] Removed Bitpanda from Fiat/BTC pricing

- package-lock.json
- package.json
- src/integration/blockchain/optimism/optimism-client.ts
- src/integration/blockchain/shared/evm/evm-client.ts
- src/subdomains/supporting/payout/services/payout-evm.service.ts
- src/subdomains/supporting/payout/services/payout-optimism.service.ts
- src/subdomains/supporting/payout/strategies/payout/impl/base/evm.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/optimism-coin.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/optimism-token.strategy.ts
> [DEV-1270] Optimism payout fee

- src/subdomains/supporting/bank/fiat-output/dto/create-fiat-output.dto.ts
> [DEV-1320] extend fiatOutput create dto

- migration/1676019359879-payInPurposeNullable.js
- src/config/__tests__/config.spec.ts
- src/config/config.ts
- src/subdomains/core/buy-crypto/process/specifications/buy-crypto-init.specification.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-registration.service.ts
- src/subdomains/core/sell-crypto/process/specifications/buy-fiat-init.specification.ts
- src/subdomains/core/staking/services/staking-return.service.ts
- src/subdomains/supporting/payin/entities/crypto-input.entity.ts
- src/subdomains/supporting/payin/services/payin-defichain.service.ts
- src/subdomains/supporting/payin/services/payin.service.ts
- src/subdomains/supporting/payin/specifications/crypto-input-init.specification.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/register.strategy.ts
> [DEV-616] Various improvements to pay-in process

- src/subdomains/core/buy-crypto/process/specifications/buy-crypto-init.specification.ts
- src/subdomains/core/sell-crypto/process/specifications/buy-fiat-init.specification.ts
> [DEV-616] Additional check for DFI min amount

- src/subdomains/supporting/payin/entities/crypto-input.entity.ts
- src/subdomains/supporting/payin/factories/payin.factory.ts
- src/subdomains/supporting/payin/interfaces/index.ts
- src/subdomains/supporting/payin/strategies/register/impl/arbitrum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bitcoin.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/ethereum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/optimism.strategy.ts
> [DEV-616] Bitcoin txSequence

- src/integration/blockchain/ain/node/node-client.ts
- src/subdomains/supporting/payin/strategies/register/impl/bitcoin.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/defichain.strategy.ts
> [DEV-616] Fixed DeFiChain inputs

- src/subdomains/supporting/payin/services/payin-defichain.service.ts
- src/subdomains/supporting/payin/strategies/send/impl/defichain-token.strategy.ts
> [DEV-616] Token forward refactoring

- src/subdomains/core/sell-crypto/process/buy-fiat-registration.service.ts
> [FIX] fix buyFiat automatic amlCheck bug

- src/subdomains/supporting/payin/services/payin-defichain.service.ts
- src/subdomains/supporting/payin/strategies/send/impl/defichain-token.strategy.ts
…ration step for utxo
- Login/logout
- Registration
> [DEV-616] UTXO preparations for DeFiChain send strategy 

- src/subdomains/supporting/payin/strategies/send/impl/defichain-token.strategy.ts
> [DEV-616] Allowing process to continue for already prepared inputs

- src/subdomains/supporting/payin/strategies/send/impl/defichain-token.strategy.ts
> [DEV-616] Properly fetching utxo for token forwarding

- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
> [FIX] add fiatOutput bankTx relation

- migration/1676898596389-cleanupWallet.js
- src/subdomains/generic/user/models/wallet/wallet.entity.ts
> [DEV-1286] wallet cleanup

- migration/1677015014694-add-ip-logger.js
- package-lock.json
- package.json
- src/app.controller.ts
- src/config/config.ts
- src/shared/auth/ip.guard.ts
- src/shared/models/asset/__mocks__/asset.entity.mock.ts
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto-batch.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/core/monitoring/metric.observer.ts
- src/subdomains/core/monitoring/monitoring.service.ts
- src/subdomains/core/monitoring/observers/banking-bot.observer.ts
- src/subdomains/core/monitoring/observers/node-health.observer.ts
- src/subdomains/generic/user/models/auth/auth.controller.ts
- src/subdomains/generic/user/models/ip-log/ip-log.entity.ts
- src/subdomains/generic/user/models/ip-log/ip-log.repository.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/generic/user/user.module.ts
- src/subdomains/supporting/bank/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/payin/entities/crypto-input.entity.ts
> [DEV-169] IP block & various improvements

- src/config/config.ts
> [NO-TASK] change btc fee to 0 temp

- src/config/config.ts
- src/subdomains/generic/user/models/user/user.service.spec.ts
- src/subdomains/generic/user/models/user/user.service.ts
> [NO-TASK] btc fee temp 0

- src/config/config.ts
- src/subdomains/generic/user/models/user/user.service.spec.ts
- src/subdomains/generic/user/models/user/user.service.ts
> [NO-TASK] change btc fee to 0 temp (#669)

- src/integration/blockchain/ain/node/defi-client.ts
- src/subdomains/core/statistic/cfp.service.ts
> [NO-TASK] Fix proposal type to CommunityFundProposal

- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
- src/subdomains/core/statistic/statistic.controller.ts
> [NO-TASK] improve transaction route

- src/subdomains/generic/user/models/kyc/kyc-process.service.ts
> DEV-1204 No error on ident retry fail

- migration/1677621943796-RemovedFiatEnable.js
- src/shared/models/fiat/__mocks__/fiat.entity.mock.ts
- src/shared/models/fiat/fiat.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
- src/subdomains/core/statistic/statistic.controller.ts
- src/subdomains/generic/user/models/kyc/kyc-process.service.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
- src/subdomains/supporting/dex/services/dex-defichain.service.ts
- src/subdomains/supporting/payin/services/payin-defichain.service.ts
> [NO-TASK] Use dfi-dusd pool and improve transaction endpoint

- migration/1677706598544-ip-log-address-remove.js
- src/shared/auth/ip.guard.ts
- src/shared/auth/rate-limit.guard.ts
- src/shared/models/ip-log/ip-log.entity.ts
- src/subdomains/core/statistic/statistic.controller.ts
- src/subdomains/generic/user/models/auth/auth.controller.ts
> [DEV-1362] Add rate limit guard

- src/subdomains/generic/user/models/user/dto/update-user-admin.dto.ts
- src/subdomains/generic/user/models/user/user.service.ts
…ed to active
- Login/logout
- Registration
> [NO-TASK] Add comment to update dto and activate user if status change

- migration/1678184308215-user-ref-index.js
- src/integration/blockchain/ain/node/defi-client.ts
- src/subdomains/core/statistic/cfp.service.ts
- src/subdomains/core/statistic/dto/cfp.dto.ts
- src/subdomains/generic/user/models/user/user.entity.ts
> [NO-TASK] Add special dfip, fix unique constraint at user table

- src/subdomains/core/statistic/cfp.service.ts
> [NO-TASK] Add optional options

- src/subdomains/core/statistic/cfp.service.ts
- src/subdomains/core/statistic/dto/cfp.dto.ts
> [NO-TASK] add optional tags 

- src/integration/blockchain/arbitrum/arbitrum-client.ts
- src/integration/blockchain/optimism/optimism-client.ts
- src/integration/blockchain/shared/evm/dto/evm-token-bridge-approval.dto.ts
- src/integration/blockchain/shared/evm/evm-registry.service.ts
- src/integration/blockchain/shared/evm/interfaces/index.ts
- src/subdomains/generic/gs/gs-evm.controller.ts
- src/subdomains/generic/gs/gs-evm.service.ts
> [DEV-1242] Manual bridge approval

- src/integration/blockchain/arbitrum/arbitrum-client.ts
- src/integration/blockchain/shared/evm/evm-client.ts
- src/subdomains/generic/admin/admin.controller.ts
- src/subdomains/generic/admin/admin.module.ts
- src/subdomains/generic/admin/admin.service.ts
- src/subdomains/generic/admin/dto/payout-request.dto.ts
- src/subdomains/supporting/dex/entities/liquidity-order.entity.ts
- src/subdomains/supporting/dex/services/dex.service.ts
- src/subdomains/supporting/payout/entities/payout-order.entity.ts
- src/subdomains/supporting/payout/services/payout-defichain.service.ts
- thunder-tests/thunderclient.json
> [DEV-1336 & DEV-1242] Payout API & Arbitrum fix

- src/shared/utils/util.ts
- src/subdomains/core/statistic/cfp.service.ts
- src/subdomains/generic/admin/admin.service.ts
- src/subdomains/supporting/dex/services/dex.service.ts
> [NO-TASK] Proposal endDate fix

- src/shared/utils/__tests__/lock.spec.ts
- src/shared/utils/lock.ts
- src/shared/utils/queue-handler.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/liquidity-management/services/liquidity-management-pipeline.service.ts
- src/subdomains/core/liquidity-management/services/liquidity-management.service.ts
- src/subdomains/core/monitoring/observers/node-health.observer.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-notification.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
- src/subdomains/core/staking/services/staking.service.ts
- src/subdomains/generic/user/models/limit-request/limit-request-notification.service.ts
- src/subdomains/generic/user/services/spider/spider-sync.service.ts
- src/subdomains/supporting/dex/services/dex.service.ts
- src/subdomains/supporting/dex/strategies/purchase-liquidity/impl/defichain-poolpair.strategy.ts
- src/subdomains/supporting/payin/services/payin-defichain.service.ts
- src/subdomains/supporting/payin/services/payin.service.ts
- src/subdomains/supporting/payin/strategies/register/impl/arbitrum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bitcoin.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/defichain.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/ethereum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/optimism.strategy.ts
- src/subdomains/supporting/payout/services/payout.service.ts
> [NO-TASK] Added lock decorator

- src/integration/blockchain/ain/node/node-client.ts
- src/integration/blockchain/ain/node/node.service.ts
- src/shared/utils/__tests__/lock.spec.ts
- src/shared/utils/lock.ts
- src/shared/utils/queue-handler.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/liquidity-management/services/liquidity-management-pipeline.service.ts
- src/subdomains/core/liquidity-management/services/liquidity-management.service.ts
- src/subdomains/core/monitoring/observers/node-health.observer.ts
- src/subdomains/core/monitoring/observers/payment.observer.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-notification.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
- src/subdomains/core/staking/services/staking.service.ts
- src/subdomains/generic/user/models/limit-request/limit-request-notification.service.ts
- src/subdomains/generic/user/services/spider/spider-sync.service.ts
- src/subdomains/supporting/bank/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/dex/services/dex.service.ts
- src/subdomains/supporting/dex/strategies/purchase-liquidity/impl/defichain-poolpair.strategy.ts
- src/subdomains/supporting/payin/entities/crypto-input.entity.ts
- src/subdomains/supporting/payin/services/payin-defichain.service.ts
- src/subdomains/supporting/payin/services/payin.service.ts
- src/subdomains/supporting/payin/strategies/register/impl/arbitrum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bitcoin.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/defichain.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/ethereum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/optimism.strategy.ts
- src/subdomains/supporting/payin/strategies/send/impl/defichain-token.strategy.ts
- src/subdomains/supporting/payout/services/payout.service.ts
> [NO-TASK] Minor fixes & lock refactoring

- src/shared/models/country/dto/country-dto.mapper.ts
- src/shared/models/country/dto/country.dto.ts
- src/subdomains/generic/user/models/kyc/kyc.controller.ts
> [DEV-1392] return dto kyc country route

- src/subdomains/core/liquidity-management/adapters/actions/arbitrum-l2-bridge.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/base/evm-l2-bridge.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/base/liquidity-management.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/dfx-dex.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/optimism-l2-bridge.adapter.ts
- src/subdomains/core/liquidity-management/entities/liquidity-management-order.entity.ts
- src/subdomains/core/liquidity-management/entities/liquidity-management-pipeline.entity.ts
- src/subdomains/core/liquidity-management/enums/index.ts
- src/subdomains/core/liquidity-management/exceptions/order-failed.exception.ts
- src/subdomains/core/liquidity-management/exceptions/order-not-processable.exception.ts
- src/subdomains/core/liquidity-management/services/liquidity-management-pipeline.service.ts
> [NO-TASK] Implemented LM order failure differentiation

- src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/base/evm-l2-bridge.adapter.ts
> [NO-TASK] Fixed exchange withdrawal completion check

- src/integration/exchange/exchange.controller.ts
- src/integration/exchange/services/exchange.service.ts
- src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
> [NO-TASK] Fixed withdraw completion check

- src/shared/models/asset/dto/asset-dto.mapper.ts
- src/shared/models/asset/dto/asset.dto.ts
> [NO-TASK] Added sort order to asset DTO

- migration/1679009222552-addBlackSquadMail.js
- src/config/config.ts
- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-notification.service.ts
- src/subdomains/generic/user/models/limit-request/limit-request-notification.service.ts
- src/subdomains/generic/user/models/user-data/user-data-notification.service.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/generic/user/user.module.ts
- Login/logout
- Registration
- deactivate blackSquad Mails
- Update Env
> [DEV-1388] add blackSquad Mails

- src/shared/auth/ip.guard.ts
- src/shared/models/ip-log/ip-log.service.ts
- src/subdomains/generic/user/models/user/user.service.ts
> [DEV-1393] IP Guard changes

- src/integration/blockchain/ain/node/node-client.ts
- src/integration/blockchain/arbitrum/arbitrum-client.ts
- src/integration/blockchain/optimism/optimism-client.ts
- src/integration/exchange/services/exchange.service.ts
- src/shared/models/ip-log/ip-log.service.ts
- src/shared/utils/queue-handler.ts
- src/shared/utils/util.ts
- src/subdomains/generic/user/models/user/user.service.ts
> [DEV-1393] IP guard changes & fixed queue handler timeout (no-task)

- src/subdomains/generic/user/models/user/user.service.ts
> [DEV-1290] Fixed linked user API

- src/shared/models/ip-log/ip-log.service.ts
> [NO-TASK] fix user check at country check

- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
> [DEV-1403] deactivate merged userData

- src/shared/models/ip-log/ip-log.service.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
> [NO-TASK] fix user check at country check (#711)

- migration/1679407981278-addUserDataCols.js
- src/subdomains/generic/user/models/link/link.service.ts
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.controller.ts
- src/subdomains/generic/user/models/user/user.service.ts
> [DEV-1415] passiveUser ref route, block multiple linkAddresses

- src/config/config.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.service.ts
- src/subdomains/core/statistic/statistic.controller.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.service.spec.ts
> [NO-TASK] statistic clean up and not look for blocked users by mail

- src/integration/exchange/services/exchange-tx.service.ts
> [DEV-1399] Sort exchange transactions

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/integration/blockchain/ain/node/btc-client.ts
- src/integration/blockchain/ain/node/defi-client.ts
- src/integration/blockchain/ain/node/node-client.ts
- src/integration/blockchain/ain/node/node.service.ts
- src/integration/exchange/controllers/exchange.controller.ts
- src/integration/exchange/dto/trade-response.dto.ts
- src/integration/exchange/services/binance.service.ts
- src/integration/exchange/services/bitpanda.service.ts
- src/integration/exchange/services/bitstamp.service.ts
- src/integration/exchange/services/exchange.service.spec.ts
- src/integration/exchange/services/exchange.service.ts
- src/integration/exchange/services/kraken.service.ts
- src/integration/exchange/services/kucoin.service.ts
- src/shared/utils/__tests__/lock.spec.ts
- src/shared/utils/queue-handler.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/supporting/dex/services/dex-defichain.service.ts
- src/subdomains/supporting/pricing/enums/index.ts
> [NO-TASK] Various fixes

- src/config/config.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.service.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/crypto-payment-info.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/crypto-route.dto.ts
- src/subdomains/core/sell-crypto/route/dto/sell-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/dto/sell.dto.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/generic/user/models/user/user.service.spec.ts
- src/subdomains/generic/user/models/user/user.service.ts
…controllers
- Login/logout
- Registration
> [DEV-1398] remove refBonus, change crypto crypto fee, clean up routes

- src/subdomains/generic/user/models/user-data/user-data.service.ts
> [NO-TASK] Removed deprecated method call

- src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/register.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bitcoin.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/defichain.strategy.ts
> [NO-TASK] Save pay ins in transaction

- migration/1681301794263-OptionalBankAccountOnBuy.js
- src/shared/services/payment-info.service.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.entity.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/buy-payment-info.dto.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/buy.dto.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/create-buy.dto.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/get-buy-payment-info.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.service.ts
- src/subdomains/core/monitoring/observers/banking-bot.observer.ts
- src/subdomains/core/sell-crypto/route/dto/create-sell.dto.ts
- src/subdomains/core/sell-crypto/route/dto/sell.dto.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/core/sell-crypto/route/sell.service.ts
- src/subdomains/generic/user/models/user/dto/ref-info-query.dto.ts
- src/subdomains/supporting/bank/bank-account/is-dfx-iban.validator.ts
- src/subdomains/supporting/bank/bank-tx/dto/update-bank-tx.dto.ts
- src/subdomains/supporting/bank/bank/bank.service.ts
> [DEV-1431] change iban optional in buy

- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.service.ts
- src/subdomains/supporting/payin/services/payin-defichain.service.ts
> [NO-TASK] Fixed crypto route creation

- src/subdomains/core/buy-crypto/buy-crypto.module.ts
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto-batch.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/core/liquidity-management/controllers/pipeline.controller.ts
- src/subdomains/core/liquidity-management/dto/input/liquidity-management-request.dto.ts
- src/subdomains/core/liquidity-management/entities/liquidity-balance.entity.ts
- src/subdomains/core/liquidity-management/entities/liquidity-management-rule.entity.ts
- src/subdomains/core/liquidity-management/liquidity-management.module.ts
- src/subdomains/core/liquidity-management/services/liquidity-management-balance.service.ts
- src/subdomains/core/liquidity-management/services/liquidity-management-pipeline.service.ts
- src/subdomains/core/liquidity-management/services/liquidity-management.service.ts
- thunder-tests/thunderclient.json
> [DEV-1445] Using LM API from buy crypto, added debouncing

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/subdomains/core/liquidity-management/adapters/actions/dfx-dex.adapter.ts
- src/subdomains/core/liquidity-management/entities/liquidity-balance.entity.ts
- src/subdomains/supporting/dex/strategies/purchase-liquidity/impl/base/defichain-non-poolpair.strategy.ts
- src/subdomains/supporting/pricing/services/integration/coin-gecko.service.ts
- src/subdomains/supporting/pricing/services/integration/currency.service.ts
- src/subdomains/supporting/pricing/services/integration/price-provider-defichain.service.ts
- src/subdomains/supporting/pricing/services/price-provider.service.ts
> [NO-TASK] Minor fixes

- src/subdomains/core/buy-crypto/process/entities/buy-crypto-batch.entity.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto-fees.entity.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto-batch.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-dex.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-pricing.service.ts
> [DEV-1223] Abort on fee conversion error (#739)

- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-notification.service.ts
> [NO-TASK] Add () to minFee display in mails

- src/subdomains/supporting/pricing/services/integration/price-provider-defichain.service.ts
> [DEV-1223] Implemented pool prices, added caching

- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/buy-payment-info.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.service.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/crypto-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/dto/sell-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/core/sell-crypto/route/sell.service.ts
> [DEV-1484] Add buy, sell and crypto route and routeId to paymentInfos

- src/subdomains/generic/user/models/user-data/user-data.service.ts
> [NO-TASK] mail & phone not changeable after kyc

- README.md
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/buy-payment-info.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.service.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/crypto-payment-info.dto.ts
- src/subdomains/core/liquidity-management/services/liquidity-management-pipeline.service.ts
- src/subdomains/core/liquidity-management/services/liquidity-management.service.ts
- src/subdomains/core/sell-crypto/route/dto/sell-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/core/sell-crypto/route/sell.service.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/supporting/notification/entities/mail/error-monitoring-mail.ts
- src/subdomains/supporting/payin/strategies/send/impl/base/jellyfish.strategy.ts
- src/subdomains/supporting/payin/strategies/send/impl/bitcoin.strategy.ts
- src/subdomains/supporting/payin/strategies/send/impl/defichain-coin.strategy.ts
- src/subdomains/supporting/payin/strategies/send/impl/defichain-token.strategy.ts
> [DEV-1484] Add buy, sell and crypto route and improved docu

- src/subdomains/core/buy-crypto/process/specifications/buy-crypto-init.specification.ts
> [NO-TASK] Take cryptoRoute instead of buy in minVolume check

- src/subdomains/core/buy-crypto/process/specifications/buy-crypto-init.specification.ts
> [NO-TASK] Take cryptoRoute instead of buy in minVolume check (#750)

- src/shared/payment/exceptions/pay-in-ignored.exception.ts
- src/shared/payment/services/transaction-helper.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-registration.service.ts
- src/subdomains/core/buy-crypto/process/specifications/buy-crypto-init.specification.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-registration.service.ts
- src/subdomains/core/sell-crypto/process/specifications/buy-fiat-init.specification.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/register.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bitcoin.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/defichain.strategy.ts
> [DEV-1319] Ignore unsellable pay ins, refactoring

- src/subdomains/generic/admin/admin.service.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
- src/subdomains/supporting/bank/bank-tx/bank-tx.controller.ts
- src/subdomains/supporting/bank/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/bank/bank-tx/dto/sepa-file.dto.ts
- src/subdomains/supporting/bank/bank-tx/sepa-parser.service.ts
> [NO-TASK] Fixed SEPA parsing

- src/subdomains/supporting/bank/bank-tx/dto/sepa.dto.ts
- src/subdomains/supporting/bank/bank-tx/sepa-parser.service.ts
> [NO-TASK] Fixed member ID

- src/integration/blockchain/shared/enums/blockchain.enum.ts
- src/integration/blockchain/shared/util/blockchain.util.ts
- src/integration/exchange/controllers/exchange.controller.ts
- src/integration/exchange/dto/trade-result.dto.ts
- src/integration/exchange/services/exchange-tx.service.ts
- src/integration/exchange/services/exchange.service.ts
- src/shared/models/asset/dto/asset-dto.mapper.ts
- src/shared/models/asset/dto/asset.dto.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-notification.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
- src/subdomains/core/staking/services/staking.service.ts
- src/subdomains/supporting/payin/strategies/register/impl/arbitrum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/ethereum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/optimism.strategy.ts
> [DEV-1466]&[FIX]&[NOTASK] 

- src/config/config.ts
- src/integration/blockchain/ain/node/btc-client.ts
- src/integration/blockchain/ain/utils/defichain.util.ts
- src/subdomains/core/liquidity-management/adapters/balances/blockchain.adapter.ts
- src/subdomains/supporting/dex/services/dex-defichain.service.ts
- src/subdomains/supporting/dex/strategies/supplementary/impl/defichain.strategy.ts
- src/subdomains/supporting/payin/services/payin-defichain.service.ts
- src/subdomains/supporting/payin/strategies/send/impl/bitcoin.strategy.ts
- src/subdomains/supporting/payin/strategies/send/impl/defichain-coin.strategy.ts
- src/subdomains/supporting/payin/strategies/send/impl/defichain-token.strategy.ts
- src/subdomains/supporting/payout/services/payout-defichain.service.ts
> [DEV-1373] Payout directly from DEX wallet

- src/shared/utils/util.ts
- src/subdomains/core/liquidity-management/adapters/balances/bank.adapter.ts
- src/subdomains/core/liquidity-management/adapters/balances/blockchain.adapter.ts
- src/subdomains/core/liquidity-management/exceptions/balance-not-certain.exception.ts
- src/subdomains/core/liquidity-management/factories/liquidity-balance-integration.factory.ts
- src/subdomains/core/liquidity-management/interfaces/index.ts
- src/subdomains/core/liquidity-management/services/liquidity-management-balance.service.ts
> [DEV-1507] Implemented balance caching for LM

- src/config/config.ts
- src/integration/blockchain/ain/node/btc-client.ts
- src/integration/blockchain/ain/utils/defichain.util.ts
- src/integration/exchange/services/exchange.service.ts
- src/shared/utils/util.ts
- src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
- src/subdomains/core/liquidity-management/adapters/balances/bank.adapter.ts
- src/subdomains/core/liquidity-management/adapters/balances/blockchain.adapter.ts
- src/subdomains/core/liquidity-management/exceptions/balance-not-certain.exception.ts
- src/subdomains/core/liquidity-management/factories/liquidity-balance-integration.factory.ts
- src/subdomains/core/liquidity-management/interfaces/index.ts
- src/subdomains/core/liquidity-management/services/liquidity-management-balance.service.ts
- src/subdomains/core/statistic/cfp.service.ts
- src/subdomains/supporting/dex/services/dex-defichain.service.ts
- src/subdomains/supporting/dex/services/dex.service.ts
- src/subdomains/supporting/dex/strategies/supplementary/impl/defichain.strategy.ts
- src/subdomains/supporting/payin/services/payin-defichain.service.ts
- src/subdomains/supporting/payin/strategies/register/impl/arbitrum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/defichain.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/ethereum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/optimism.strategy.ts
- src/subdomains/supporting/payin/strategies/send/impl/bitcoin.strategy.ts
- src/subdomains/supporting/payin/strategies/send/impl/defichain-coin.strategy.ts
- src/subdomains/supporting/payin/strategies/send/impl/defichain-token.strategy.ts
- src/subdomains/supporting/payout/services/payout-defichain.service.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
> [DEV-1466 & DEV-1373] LM withdrawal & payout from DEX

- src/subdomains/supporting/pricing/services/pricing.service.ts
> [NO-TASK] Added BTC->USD pricing

- migration/1684743418738-AssetApproxPrice.js
- src/config/config.ts
- src/shared/models/asset/asset.entity.ts
- src/shared/models/asset/asset.service.ts
- src/subdomains/supporting/pricing/services/asset-prices.service.ts
> [DEV-1523] Added approx. asset prices

- src/integration/blockchain/ain/ain.module.ts
- src/integration/blockchain/ain/services/__tests__/crypto.service.spec.ts
- src/integration/blockchain/blockchain.module.ts
- src/integration/blockchain/shared/services/crypto.service.ts
- src/subdomains/core/referral/referral.module.ts
- src/subdomains/core/referral/reward/ref-reward.service.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/auth/dto/auth-credentials.dto.ts
- src/subdomains/generic/user/models/user/dto/create-user.dto.ts
- src/subdomains/generic/user/models/user/user.service.spec.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/generic/user/user.module.ts
> [DEV-1527]: added lightning verification

- src/shared/models/entity.ts
- src/subdomains/core/buy-crypto/process/entities/__mocks__/buy-crypto-batch.entity.mock.ts
- src/subdomains/core/buy-crypto/process/entities/__mocks__/buy-crypto-fee.entity.mock.ts
- src/subdomains/core/buy-crypto/process/entities/__tests__/buy-crypto-batch.entity.spec.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto-batch.entity.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto-fees.entity.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/repositories/buy-crypto.repository.ts
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto-batch.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/supporting/payin/strategies/send/impl/base/send.strategy.ts
- src/subdomains/supporting/payout/interfaces/index.ts
- src/subdomains/supporting/payout/services/payout.service.ts
> [NO-TASK] Fixed buy crypto fees

- src/integration/blockchain/bsc/bsc-client.ts
- src/subdomains/supporting/payin/entities/crypto-input.entity.ts
- src/subdomains/supporting/payin/services/base/payin-evm.service.ts
- src/subdomains/supporting/payin/strategies/register/impl/arbitrum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/ethereum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/optimism.strategy.ts
> [NO-TASK] EVM input fixes

- src/integration/lightning/dto/lnbits-wallet.dto.ts
- src/integration/lightning/dto/lnd-channel-balance.dto.ts
- src/integration/lightning/dto/lnd-wallet-balance.dto.ts
- src/integration/lightning/lightning-client.ts
> [DEV-1551]: LND and LNBits Balance

- migration/1686139882726-FixedAssetIndex.js
- package-lock.json
- package.json
- src/integration/blockchain/shared/evm/evm-client.ts
- src/integration/lightning/dto/lnbits-wallet.dto.ts
- src/integration/lightning/dto/lnd-channel-balance.dto.ts
- src/integration/lightning/dto/lnd-wallet-balance.dto.ts
- src/integration/lightning/lightning-client.ts
- src/shared/models/asset/asset.entity.ts
- src/subdomains/core/monitoring/observers/payment.observer.ts
- src/subdomains/generic/admin/dto/payout-request.dto.ts
- src/subdomains/supporting/dex/entities/liquidity-order.entity.ts
- src/subdomains/supporting/dex/services/dex.service.ts
- src/subdomains/supporting/payin/services/payin-bitcoin.service.ts
> Fixes & small improvements

- .vscode/settings.json
- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/config/config.ts
- src/integration/blockchain/shared/services/crypto.service.ts
- src/integration/lightning/controllers/alby.controller.ts
- src/integration/lightning/lightning-helper.ts
- src/integration/lightning/lightning.module.ts
- src/integration/lightning/services/lightning.service.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
> [DEV-1545 & DEV-1556 & DEV-1553] Alby API, login with node pub key

- migration/1686151116788-addBuyCryptoChargebackTxId.js
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
> [FIX] fix buyCrypto return mails + add chargebackCryptoTxId

- src/subdomains/core/buy-crypto/process/dto/update-buy-crypto.dto.ts
> [FIX] add new col in update dto

- .vscode/settings.json
- README.md
- src/config/config.ts
- src/shared/payment/entities/target-estimation.ts
- src/shared/payment/entities/transaction-details.ts
- src/shared/payment/services/transaction-helper.ts
- src/shared/services/payment-info.service.ts
- src/shared/utils/__tests__/lock.spec.ts
- src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.controller.spec.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/buy-quote.dto.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/get-buy-quote.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/crypto-quote.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/get-crypto-quote.dto.ts
- src/subdomains/core/sell-crypto/route/dto/get-sell-quote.dto.ts
- src/subdomains/core/sell-crypto/route/dto/sell-quote.dto.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/generic/user/models/user/user.service.spec.ts
- src/subdomains/generic/user/models/user/user.service.ts
> [DEV-1547] Quote API

- src/shared/payment/entities/transaction-details.ts
- src/shared/payment/services/transaction-helper.ts
- src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.controller.spec.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/buy-payment-info.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/crypto-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/dto/sell-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
> [DEV-1568] Tx specs in target asset

- migration/1686668014082-addUserDataIdentificationType.js
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
> [DEV-1567] add identification type

- src/integration/blockchain/shared/evm/evm-client.ts
- src/subdomains/core/liquidity-management/services/liquidity-management-pipeline.service.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/optimism.strategy.ts
> [DEV-1550] Fixed OptimismStrategy

- migration/1686836193039-addUserDataInternalAmlNote.js
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
> [DEV-1573] add internalAmlNote

- migration/1686836193039-addUserDataInternalAmlNote.js
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
> [NOTASK] allow amlListAddedDate update

- src/integration/lightning/dto/lnd.dto.ts
- src/integration/lightning/lightning-client.ts
- src/integration/lightning/lightning-helper.ts
- src/integration/lightning/services/lightning.service.ts
- src/subdomains/supporting/payout/services/payout-lightning.service.ts
> [DEV-1582]: LN prepare estimate fee

- src/integration/lightning/lightning-client.ts
- src/integration/lightning/services/lightning.service.ts
- src/subdomains/supporting/payout/services/payout-lightning.service.ts
> [NO-TASK] Lightning payout fix

- src/integration/lightning/services/lightning.service.ts
- src/subdomains/core/sell-crypto/route/__tests__/sell.controller.spec.ts
- src/subdomains/core/sell-crypto/route/dto/sell-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/core/sell-crypto/sell-crypto.module.ts
- src/subdomains/supporting/payout/services/payout-lightning.service.ts
> [DEV-1598] Added lightning invoice to sell payment infos

- .vscode/settings.json
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto-batch.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-dex.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-pricing.service.ts
- src/subdomains/supporting/payin/strategies/send/impl/base/evm.strategy.ts
- src/subdomains/supporting/payin/strategies/send/impl/base/send.strategy.ts
- src/subdomains/supporting/payin/strategies/send/impl/bitcoin.strategy.ts
- src/subdomains/supporting/payout/services/payout-lightning.service.ts
- src/subdomains/supporting/payout/services/payout.service.ts
- src/subdomains/supporting/payout/strategies/payout/impl/base/evm.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/base/payout.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/lightning.strategy.ts
> [DEV-1582] Lightning fee estimation

- src/subdomains/core/statistic/cfp.service.ts
- src/subdomains/core/statistic/dto/cfp.dto.ts
> [NO-TASK] Change cfp api from cake to bake

- src/config/config.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
- src/subdomains/supporting/bank/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/bank/bank-tx/dto/update-bank-tx.dto.ts
> [NO-TASK] Add assignTransactions method

- src/subdomains/supporting/bank/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/bank/bank-tx/dto/update-bank-tx.dto.ts
* [NO-TASK] Add assignTransactions method
* [NO-TASK] move regex to config and search matched bank usage
* [NO-TASK] decrease to every 30s at checking banktx and minor fix
* [NO-TASK] set bankTx type to GSheet when buyId is not found
* [NO-TASK] add isnotempty
* [NO-TASK] Remove IsIptional()
- Login/logout
- Registration
> [NO-TASK] set bankTx type to GSheet when buyId is not found (#822)

- migration/1688069984111-bankDataUserDataNotNullableRelation.js
- src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
> [FIX] fix bankData nullable userData relation

- migration/1688117678089-bankDataIbanIndex.js
- src/subdomains/generic/user/models/bank-data/bank-data.controller.ts
- src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
- src/subdomains/generic/user/models/bank-data/dto/create-bank-data.dto.ts
- src/subdomains/generic/user/models/bank-data/dto/update-bank-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.controller.ts
> [DEV-1605] bankData iban unique index + refactoring

- migration/1688117678089-bankDataIbanIndex.js
- src/subdomains/generic/user/models/bank-data/bank-data.controller.ts
- src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
- src/subdomains/generic/user/models/bank-data/dto/create-bank-data.dto.ts
- src/subdomains/generic/user/models/bank-data/dto/update-bank-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.controller.ts
* [DEV-1605] bankData iban unique index + refactoring
* [DEV-1605] Refactoring
- Login/logout
- Registration
[DEV-1605]: https://dfxswiss.atlassian.net/browse/DEV-1605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1605]: https://dfxswiss.atlassian.net/browse/DEV-1605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DEV-1605] bankData iban unique index + refactoring (#826)

- src/app.controller.ts
> [NO-TASK] Add lightning to ref code apps

- infrastructure/config/lightning/lnd/dev.conf
- infrastructure/config/lightning/lnd/loc.conf
- infrastructure/config/lightning/lnd/prd.conf
- src/app.controller.ts
- src/integration/blockchain/shared/evm/evm-client.ts
- src/integration/lightning/dto/lnurlp.dto.ts
- src/integration/lightning/lightning-client.ts
- src/shared/utils/util.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/create-buy.dto.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/get-buy-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/dto/create-sell.dto.ts
- src/subdomains/core/sell-crypto/route/dto/get-sell-payment-info.dto.ts
- src/subdomains/generic/user/models/bank-data/dto/create-bank-data.dto.ts
- src/subdomains/generic/user/models/kyc/dto/kyc-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/dto/update-user.dto.ts
- src/subdomains/supporting/bank/bank-account/bank-account.service.ts
- src/subdomains/supporting/bank/bank-account/dto/create-bank-account.dto.ts
- thunder-tests/thunderclient.json
> [NO-TASK] Various improvements

- src/config/config.ts
- src/main.ts
- src/shared/models/ip-log/ip-log.service.ts
- src/subdomains/core/liquidity-management/adapters/balances/blockchain.adapter.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-notification.service.ts
- src/subdomains/generic/user/models/user/user.service.ts
> [FIX] fix missing amount in buyFiat mail

- migration/1689274956333-addAssetIknaCol.js
- src/shared/models/asset/asset.entity.ts
> [DEV-1618] add ikna col

- src/shared/models/asset/dto/asset-dto.mapper.ts
> [DEV-1616] hide unused assets

- src/shared/i18n/de/translation.json
- src/shared/i18n/en/translation.json
- src/shared/i18n/es/translation.json
- src/shared/i18n/fr/translation.json
- src/shared/i18n/it/translation.json
- src/shared/i18n/pt/translation.json
- src/shared/utils/util.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-notification.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/supporting/notification/entities/mail/user-mail.ts
- src/subdomains/supporting/notification/factories/mail.factory.ts
- src/subdomains/supporting/notification/interfaces/index.ts
- src/subdomains/supporting/notification/services/notification.service.ts
- src/subdomains/supporting/notification/templates/userNew.hbs
> [DEV-1601] add user mails: pending, return mails

- src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.service.ts
- src/subdomains/core/sell-crypto/route/sell.service.ts
> [DEV-1630] just get buyable buy, crypto & sell routes 

- migration/1689879272205-addMasterKey.js
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/user/dto/create-user.dto.ts
- src/subdomains/generic/user/models/user/user.entity.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/generic/user/models/wallet/wallet.entity.ts
- src/subdomains/generic/user/models/wallet/wallet.service.ts
> [DEV-1631] masterKey signIn

- migration/1690281913933-addUserDataAmlCols.js
- src/subdomains/core/buy-crypto/process/dto/update-buy-crypto.dto.ts
- src/subdomains/core/buy-crypto/process/entities/__mocks__/buy-crypto.entity.mock.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/enums/check-status.enum.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/__mocks__/buy-history.dto.mock.ts
- src/subdomains/core/history/dto/__mocks__/history.dto.mock.ts
- src/subdomains/core/history/dto/history.dto.ts
- src/subdomains/core/history/history.service.ts
- src/subdomains/core/monitoring/observers/payment.observer.ts
- src/subdomains/core/sell-crypto/process/__mocks__/buy-fiat.entity.mock.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-notification.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
- src/subdomains/core/sell-crypto/process/dto/update-buy-fiat.dto.ts
- src/subdomains/core/sell-crypto/route/dto/__mocks__/sell-history.dto.mock.ts
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/payin/entities/__mocks__/crypto-input.entity.mock.ts
- src/subdomains/supporting/payin/entities/crypto-input.entity.ts
- src/subdomains/supporting/payin/services/payin.service.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/register.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bitcoin.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/defichain.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/lightning.strategy.ts
> [DEV-1639] additional aml user data col

- src/shared/payment/entities/transaction-details.ts
- src/shared/payment/services/transaction-helper.ts
- src/shared/validators/xor.validator.ts
- src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.controller.spec.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/buy-payment-info.dto.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/buy-quote.dto.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/get-buy-payment-info.dto.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/get-buy-quote.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/crypto-payment-info.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/crypto-quote.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/get-crypto-payment-info.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/get-crypto-quote.dto.ts
- src/subdomains/core/sell-crypto/route/dto/get-sell-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/dto/get-sell-quote.dto.ts
- src/subdomains/core/sell-crypto/route/dto/sell-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/dto/sell-quote.dto.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
> [DEV-1624] add payment amounts calculation

- src/subdomains/core/liquidity-management/services/liquidity-management.service.ts
> [NO-TASK] Decreased LM activation time for DeFiChain

- src/config/config.ts
- src/integration/lightning/controllers/lnurlp-forward.controller.ts
- src/integration/lightning/controllers/lnurlw-forward.controller.ts
- src/integration/lightning/dto/lnurlw.dto.ts
- src/integration/lightning/lightning-client.ts
- src/integration/lightning/lightning-helper.ts
- src/integration/lightning/lightning.module.ts
- src/integration/lightning/services/lightning.service.ts
- src/integration/lightning/services/lnurl-forward.service.ts
> [DEV-1637] added LNURLw handling

- src/integration/blockchain/shared/evm/dto/scan-api-response.dto.ts
- src/integration/blockchain/shared/evm/evm-client.ts
> [NO-TASK] Fix #2

- migration/1690971110553-BankDataActiveNullable.js
- src/config/__tests__/config.spec.ts
- src/config/config.ts
- src/integration/blockchain/shared/evm/evm-client.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
- src/subdomains/generic/user/models/bank-data/dto/create-bank-data.dto.ts
> Various Improvements

- src/integration/blockchain/shared/evm/evm-client.ts
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/monitoring/observers/node-balance.observer.ts
> Output asset to buy crypto update

- migration/1691142414745-AddWalletIdentMethod.js
- src/subdomains/generic/user/models/kyc/kyc-process.service.ts
- src/subdomains/generic/user/models/wallet/wallet.entity.ts
> [DEV-1653] Added custom ident method to wallet

- src/shared/payment/entities/transaction-details.ts
- src/shared/payment/services/transaction-helper.ts
- src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.controller.spec.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/buy-payment-info.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/crypto-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/dto/sell-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
> [DEV-1648] add isValid to paymentInfos

- src/config/config.ts
- src/shared/payment/entities/transaction-details.ts
- src/shared/payment/exceptions/pay-in-not-sellable-exception.ts
- src/shared/payment/exceptions/pay-in-too-small.exception.ts
- src/shared/payment/services/transaction-helper.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-registration.service.ts
- src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.controller.spec.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/buy-payment-info.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/crypto-payment-info.dto.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-registration.service.ts
- src/subdomains/core/sell-crypto/route/dto/sell-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/generic/user/models/wallet/wallet.service.ts
> [DEV-1243]&[DEV-1648] extend PaymentInfos & Improvements

- src/subdomains/core/buy-crypto/buy-crypto.module.ts
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto-batch.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-webhook.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
- src/subdomains/generic/user/services/webhook/dto/payment-webhook.dto.ts
> [DEV-1649] add paymentWebhook States

- src/subdomains/supporting/bank/bank-tx-return/bank-tx-return.entity.ts
- src/subdomains/supporting/bank/bank-tx/bank-tx.entity.ts
> [NO-TASK] Add BankTxReturn relation to BankTx table

- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
> [FIX] fix missing relation for webhook

- src/shared/i18n/de/translation.json
- src/shared/i18n/en/translation.json
- src/shared/i18n/es/translation.json
- src/shared/i18n/fr/translation.json
- src/shared/i18n/it/translation.json
- src/shared/i18n/pt/translation.json
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/referral/reward/ref-reward-notification.service.ts
- src/subdomains/core/referral/reward/ref-reward.entity.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-notification.service.ts
- src/subdomains/core/staking/services/staking.service.ts
- src/subdomains/generic/user/models/kyc/kyc-process.service.ts
- src/subdomains/generic/user/models/link/link.service.ts
- src/subdomains/generic/user/services/spider/spider-sync.service.ts
- src/subdomains/supporting/notification/entities/mail/base/mail.ts
- src/subdomains/supporting/notification/entities/mail/user-mail.ts
- src/subdomains/supporting/notification/factories/mail.factory.ts
- src/subdomains/supporting/notification/interfaces/index.ts
- src/subdomains/supporting/notification/templates/userNew.hbs
- src/subdomains/supporting/payin/services/payin-notification.service.ts
> [DEV-1728] rest user mail refactoring

- src/subdomains/supporting/bank/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/bank/bank-tx/dto/update-bank-tx.dto.ts
> [DEV-1748] bankTx editable cols

- src/integration/lightning/controllers/alby.controller.ts
- src/subdomains/generic/user/models/auth/auth-alby.service.ts
- src/subdomains/generic/user/models/auth/auth.controller.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/user/dto/alby.dto.ts
- src/subdomains/generic/user/models/user/dto/create-user.dto.ts
- src/subdomains/generic/user/user.module.ts
> [DEV-1770] Fix for getalby

- src/integration/lightning/controllers/alby.controller.ts
- src/subdomains/core/buy-crypto/process/buy-crypto.controller.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.controller.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
- src/subdomains/generic/user/models/auth/auth-alby.service.ts
- src/subdomains/generic/user/models/auth/auth.controller.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/user/dto/alby.dto.ts
- src/subdomains/generic/user/models/user/dto/create-user.dto.ts
- src/subdomains/generic/user/user.module.ts
- src/subdomains/supporting/bank/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/bank/bank-tx/dto/update-bank-tx.dto.ts
- src/subdomains/supporting/bank/fiat-output/fiat-output.service.ts
> [DEV-1748 & DEV-1645 & DEV-1770] bankTx editable cols, reset aml check, fix for getalby

- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
> [DEV-1764] fix support route failed tx

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/config/config.ts
- src/integration/ikna/controllers/ikna.controller.ts
- src/integration/ikna/dto/ikna-address-neighbor.dto.ts
- src/integration/ikna/dto/ikna-address-tag.dto.ts
- src/integration/ikna/dto/ikna-query.dto.ts
- src/integration/ikna/dto/ikna-sanction-result.dto.ts
- src/integration/ikna/ikna.module.ts
- src/integration/ikna/services/ikna.service.ts
- src/integration/integration.module.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/supporting/bank/bank-tx/dto/sepa-entry.dto.ts
- src/subdomains/supporting/bank/bank-tx/sepa-parser.service.ts
> [DEV-1764]&[DEV-1620] Fix support route, ikna bfs

- src/integration/blockchain/ain/node/node.service.ts
- src/integration/blockchain/ain/services/__tests__/crypto.service.spec.ts
- src/integration/blockchain/shared/evm/evm-registry.service.ts
- src/integration/blockchain/shared/evm/evm.service.ts
- src/integration/blockchain/shared/services/crypto.service.ts
- src/subdomains/core/buy-crypto/buy-crypto.module.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/__tests__/crypto-route.controller.spec.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/crypto-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/__tests__/sell.controller.spec.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
> [DEV-1679] add paymentRequest for other chains

- migration/1694431107346-removeUserCfpVotes.js
- src/subdomains/generic/user/models/user/user.entity.ts
> [DEV-1725] remove cfp votes

- src/shared/i18n/de/translation.json
- src/shared/i18n/en/translation.json
- src/shared/i18n/es/translation.json
- src/shared/i18n/fr/translation.json
- src/shared/i18n/it/translation.json
- src/shared/i18n/pt/translation.json
- src/subdomains/generic/user/models/limit-request/limit-request-notification.service.ts
- src/subdomains/generic/user/models/user-data/user-data-notification.service.ts
- src/subdomains/supporting/notification/entities/mail/personal-mail.ts
- src/subdomains/supporting/notification/entities/mail/user-mail.ts
- src/subdomains/supporting/notification/factories/mail.factory.ts
- src/subdomains/supporting/notification/interfaces/index.ts
- src/subdomains/supporting/notification/templates/personalNew.hbs
> [DEV-1622] personal mail refactoring

- src/subdomains/core/buy-crypto/process/buy-crypto.controller.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-webhook.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.controller.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
> [DEV-1841] manual webhook trigger endpoint

- src/integration/blockchain/ain/services/__tests__/crypto.service.spec.ts
- src/integration/blockchain/shared/services/crypto.service.ts
- src/integration/blockchain/shared/util/blockchain.util.ts
> Bitcoin Multisig, LDS Explorer

- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.controller.ts
- src/subdomains/generic/user/models/user/user.entity.ts
- src/subdomains/generic/user/models/user/user.service.ts
> [DEV-1828] user delete endpoint

- src/config/config.ts
- src/subdomains/supporting/notification/templates/generic.hbs
> [FIX] fix generic mails

- src/app.controller.ts
> [DEV-1765] Adapted app store URLs

- package-lock.json
- package.json
- src/config/config.ts
- src/subdomains/generic/user/models/auth/__tests__/lnurl-auth.spec.ts
- src/subdomains/generic/user/models/auth/auth-lnurl.controller.ts
- src/subdomains/generic/user/models/auth/auth-lnurl.service.ts
- src/subdomains/generic/user/models/auth/dto/auth-lnurl.dto.ts
- src/subdomains/generic/user/user.module.ts
> [DEV-1849] added lnurl auth

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/repositories/buy-crypto.repository.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
> [DEV-1873] amlCheck reset: remove buyCryptoFee

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
> [DEV-1890] fix amlCheck reset fee bug

- src/shared/auth/ip-country.guard.ts
- src/shared/auth/ip.guard.ts
- src/shared/auth/jwt-payload.interface.ts
- src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.controller.spec.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/generic/user/models/auth/__tests__/lnurl-auth.spec.ts
- src/subdomains/generic/user/models/auth/auth-alby.service.ts
- src/subdomains/generic/user/models/auth/auth-lnurl.controller.ts
- src/subdomains/generic/user/models/auth/auth-lnurl.service.ts
- src/subdomains/generic/user/models/auth/auth.controller.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/user/user.controller.ts
> [DEV-1874] login ip tracking, ip guard

- src/integration/blockchain/shared/services/crypto.service.ts
> [NO-TASK] Compare lower case signature at evm

- migration/1698078756376-CheckoutTxExpiresNullable.js
- src/integration/blockchain/shared/services/crypto.service.ts
- src/shared/auth/ip-country.guard.ts
- src/shared/auth/ip.guard.ts
- src/shared/auth/jwt-payload.interface.ts
- src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.controller.spec.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/generic/user/models/auth/__tests__/lnurl-auth.spec.ts
- src/subdomains/generic/user/models/auth/auth-alby.service.ts
- src/subdomains/generic/user/models/auth/auth-lnurl.controller.ts
- src/subdomains/generic/user/models/auth/auth-lnurl.service.ts
- src/subdomains/generic/user/models/auth/auth.controller.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/user/user.controller.ts
- src/subdomains/supporting/fiat-payin/entities/checkout-tx.entity.ts
- src/subdomains/supporting/fiat-payin/services/fiat-payin-sync.service.ts
> [DEV-1874]&[NO-TASK] ip login tracking, checkout tx expires

- src/subdomains/generic/user/models/kyc/kyc.service.ts
- src/subdomains/generic/user/models/user-data/is-dfx-phone.validator.ts
- src/subdomains/supporting/bank/bank-account/is-dfx-iban.validator.ts
> [DEV-1899] kyc complete wo housenumber

- src/subdomains/supporting/payment/services/fee.service.ts
> [FIX] allow custom fees with discountCode

- src/shared/auth/ip.guard.ts
> [NO-TASK] Disabled IP blocking

- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
- src/subdomains/core/sell-crypto/route/sell.service.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/bank/bank-account/bank-account.service.ts
- src/subdomains/supporting/fiat-output/fiat-output.service.ts
> [DEV-1914] fix supportRoute

- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
- src/subdomains/core/sell-crypto/route/sell.service.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/bank/bank-account/bank-account.service.ts
- src/subdomains/supporting/fiat-output/fiat-output.service.ts
- src/subdomains/supporting/pricing/__tests__/pricing.integration.spec.ts
- src/subdomains/supporting/pricing/domain/enums/index.ts
- src/subdomains/supporting/pricing/pricing.module.ts
- src/subdomains/supporting/pricing/services/integration/pricing-coin-gecko.service.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
- src/subdomains/supporting/pricing/utils/__mocks__/price-path.mock.ts
- src/subdomains/supporting/pricing/utils/price-step.ts
- src/subdomains/supporting/pricing/utils/pricing.util.ts
> [DEV-1914] fix supportRoute (#907)

- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [DEV-1934] fix amount calculation card payment bug

- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [DEV-1934] fix amount calculation card payment bug (#910)

- migration/1699010411038-addHigRiskAndAmlAccountType.js
- src/subdomains/core/buy-crypto/process/dto/update-buy-crypto.dto.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/dto/update-buy-fiat.dto.ts
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.entity.ts
- src/subdomains/supporting/bank-tx/bank-tx/dto/update-bank-tx.dto.ts
> [DEV-1926]&[DEV-1933] additional column

- migration/1699010411038-addHigRiskAndAmlAccountType.js
- src/config/config.ts
- src/subdomains/core/buy-crypto/buy-crypto.module.ts
- src/subdomains/core/buy-crypto/process/dto/update-buy-crypto.dto.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto-batch.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto-preparation.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/__tests__/buy-fiat.service.spec.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/dto/update-buy-fiat.dto.ts
- src/subdomains/core/sell-crypto/sell-crypto.module.ts
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.entity.ts
- src/subdomains/supporting/bank-tx/bank-tx/dto/update-bank-tx.dto.ts
> [DEV-1900]&[DEV-1926]&[DEV-1933] set buyCrypto fee with api, additional columns

- src/shared/models/setting/dto/custom-sign-up-fees.dto.ts
- src/shared/models/setting/dto/fee-mapper.dto.ts
- src/shared/models/setting/setting.controller.ts
- src/shared/models/setting/setting.service.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/payment/services/fee.service.ts
> [DEV-1925] add fee mapper

- src/subdomains/generic/user/services/webhook/dto/webhook.dto.ts
- src/subdomains/supporting/pricing/services/price-provider.service.ts
> [NO-TASK] Added pricing for custom assets

- src/shared/models/setting/dto/custom-sign-up-fees.dto.ts
- src/shared/models/setting/setting.controller.ts
- src/shared/models/setting/setting.service.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/generic/user/services/webhook/dto/webhook.dto.ts
- src/subdomains/supporting/payment/services/fee.service.ts
- src/subdomains/supporting/pricing/services/price-provider.service.ts
> [NOTASK] set fiatReference for buyCrypto

- migration/1699279253111-addFeeActive.js
- src/shared/models/setting/dto/custom-sign-up-fees.dto.ts
- src/shared/models/setting/setting.service.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/payment/dto/create-fee.dto.ts
- src/subdomains/supporting/payment/entities/fee.entity.ts
- src/subdomains/supporting/payment/services/fee.service.ts
> [DEV-1935]&[FIX] active fee col, fix initial custom sign up fee

- src/subdomains/supporting/payment/services/fee.service.ts
> [NOTASK] allow negative & positive discount fee

- src/integration/lightning/lightning-client.ts
- src/subdomains/supporting/pricing/domain/enums/index.ts
> [DEV-1950] BGB token & LN balance

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- package-lock.json
- package.json
- src/config/config.ts
- src/integration/infrastructure/azure-storage.service.ts
- src/subdomains/generic/generic.module.ts
- src/subdomains/generic/kyc/kyc.module.ts
- src/subdomains/generic/kyc/services/document-storage.service.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
- src/subdomains/generic/user/models/user-data/user-data.controller.ts
- src/subdomains/generic/user/services/spider/spider-sync.service.ts
- src/subdomains/generic/user/user.module.ts
> [DEV-1940] sync kyc files to document storage

- migration/1699717429095-addFatfEnable.js
- src/shared/models/country/country.entity.ts
> [DEV-1955] add fatfEnable

- src/subdomains/generic/admin/admin.controller.ts
- src/subdomains/generic/admin/dto/upload-file.dto.ts
- src/subdomains/generic/admin/dto/upload-spider-file.dto.ts
- src/subdomains/generic/kyc/kyc.module.ts
- src/subdomains/generic/kyc/services/document-storage.service.ts
- src/subdomains/generic/kyc/services/kyc-file.dto.ts
- src/subdomains/generic/user/models/kyc/kyc.service.spec.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
- src/subdomains/generic/user/models/user-data/dto/upload-file.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.controller.ts
- src/subdomains/generic/user/services/spider/spider-sync.service.ts
- src/subdomains/generic/user/user.module.ts
> [DEV-1960] Upload kyc file to userData

- migration/1699975053005-addPayoutRefBonus.js
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.controller.spec.ts
- src/subdomains/supporting/payment/dto/create-fee.dto.ts
- src/subdomains/supporting/payment/dto/fee.dto.ts
- src/subdomains/supporting/payment/entities/fee.entity.ts
- src/subdomains/supporting/payment/services/fee.service.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [DEV-1945] add payoutRefBonus col

- migration/1699975053005-addPayoutRefBonus.js
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.controller.spec.ts
- src/subdomains/generic/admin/admin.controller.ts
- src/subdomains/generic/admin/dto/upload-spider-file.dto.ts
- src/subdomains/generic/kyc/kyc.module.ts
- src/subdomains/generic/kyc/services/document-storage.service.ts
- src/subdomains/generic/kyc/services/kyc-file.dto.ts
- src/subdomains/generic/user/models/kyc/kyc.service.spec.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
- src/subdomains/generic/user/models/user-data/dto/upload-file.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.controller.ts
- src/subdomains/generic/user/services/spider/spider-sync.service.ts
- src/subdomains/generic/user/user.module.ts
- src/subdomains/supporting/payment/dto/create-fee.dto.ts
- src/subdomains/supporting/payment/dto/fee.dto.ts
- src/subdomains/supporting/payment/entities/fee.entity.ts
- src/subdomains/supporting/payment/services/fee.service.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
* [DEV-1960] Upload kyc file to userData
* [DEV-1960] remove metadata
* [DEV-1960] Use document storage service
* [DEV-1960] add user index and change Spider to lower case
* [DEV-1940] Option to disable name check sync
* [DEV-1960] Refactoring
* [DEV-1940] Fixed organization documents, improved error log
---------
- Login/logout
- Registration
[DEV-1960]: https://dfxswiss.atlassian.net/browse/DEV-1960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1960]: https://dfxswiss.atlassian.net/browse/DEV-1960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …
> [DEV-1960] & [DEV-1940] Upload kyc file to userData (#928)

- src/subdomains/generic/gs/dto/db-query.dto.ts
- src/subdomains/generic/gs/gs.service.ts
> [DEV-1982] add gs sortColumn

- migration/1700042209571-addMaxTxUsage.js
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto-preparation.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.controller.spec.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/supporting/payment/dto/create-fee.dto.ts
- src/subdomains/supporting/payment/dto/fee.dto.ts
- src/subdomains/supporting/payment/entities/fee.entity.ts
- src/subdomains/supporting/payment/services/fee.service.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [DEV-1949] add maxTxUsage

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- migration/1700237877955-addApiKey.js
- src/config/config.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
- src/subdomains/generic/user/models/wallet/wallet.entity.ts
- src/subdomains/generic/user/models/wallet/wallet.service.ts
- src/subdomains/generic/user/services/webhook/webhook.service.ts
> [DEV-1927] add wallet apiKey

- .vscode/settings.json
- infrastructure/README.md
- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- infrastructure/config/docker/docker-compose-monero.yml
- infrastructure/scripts/runBackup.sh
- infrastructure/scripts/setupDocker.sh
- infrastructure/scripts/setupEnv.sh
- src/config/config.ts
- src/integration/blockchain/ain/services/__tests__/crypto.service.spec.ts
- src/integration/blockchain/blockchain.module.ts
- src/integration/blockchain/monero/dto/monero.dto.ts
- src/integration/blockchain/monero/monero-client.ts
- src/integration/blockchain/monero/monero.module.ts
- src/integration/blockchain/monero/services/monero.service.ts
- src/integration/blockchain/shared/enums/blockchain.enum.ts
- src/integration/blockchain/shared/services/crypto.service.ts
- src/integration/blockchain/shared/util/blockchain.util.ts
- src/subdomains/core/liquidity-management/adapters/actions/binance.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/kraken.adapter.ts
- src/subdomains/core/referral/reward/ref-reward.service.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
> [DEV-1974] Monero login

- .vscode/settings.json
- infrastructure/README.md
- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- infrastructure/config/docker/docker-compose-monero.yml
- infrastructure/config/openssl/openssl.conf
- infrastructure/scripts/runBackup.sh
- infrastructure/scripts/setupDocker.sh
- infrastructure/scripts/setupEnv.sh
- src/config/config.ts
- src/integration/blockchain/ain/services/__tests__/crypto.service.spec.ts
- src/integration/blockchain/blockchain.module.ts
- src/integration/blockchain/monero/dto/monero.dto.ts
- src/integration/blockchain/monero/monero-client.ts
- src/integration/blockchain/monero/monero.module.ts
- src/integration/blockchain/monero/services/monero.service.ts
- src/integration/blockchain/shared/enums/blockchain.enum.ts
- src/integration/blockchain/shared/services/crypto.service.ts
- src/integration/blockchain/shared/util/blockchain.util.ts
- src/subdomains/core/liquidity-management/adapters/actions/binance.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/kraken.adapter.ts
- src/subdomains/core/referral/reward/ref-reward.service.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/kyc/kyc.service.ts
- src/subdomains/generic/user/models/user-data/user-data.controller.ts
- src/subdomains/generic/user/services/spider/spider-api.service.ts
- src/subdomains/generic/user/services/spider/spider-sync.service.ts
> [DEV-1974] Monero login + file sync improvement

- src/subdomains/generic/user/services/spider/spider-sync.service.ts
> [NO-TASK] Continue on sync error

- src/shared/utils/util.ts
- src/subdomains/core/history/history.controller.ts
- src/subdomains/generic/user/models/limit-request/limit-request.service.ts
> [DEV-1988] Upload limit request to azure

- migration/1700772785883-addMinTxVolume.js
- src/subdomains/supporting/payment/dto/create-fee.dto.ts
- src/subdomains/supporting/payment/entities/fee.entity.ts
> [DEV-1990]&[DEV-1991] add minTxVolume

- migration/1700772785883-addMinTxVolume.js
- src/shared/utils/util.ts
- src/subdomains/core/history/history.controller.ts
- src/subdomains/generic/kyc/services/dilisense.service.ts
- src/subdomains/generic/user/models/limit-request/limit-request.service.ts
- src/subdomains/supporting/payment/dto/create-fee.dto.ts
- src/subdomains/supporting/payment/entities/fee.entity.ts
> [DEV-1988], [DEV-1990], [DEV-1991] limit request to azure and add minTxVolume

- src/subdomains/generic/gs/dto/support-data.dto.ts
- src/subdomains/generic/gs/gs.module.ts
- src/subdomains/generic/gs/gs.service.ts
- src/subdomains/generic/kyc/services/document-storage.service.ts
> [DEV-1989] add user doc list to supportTool

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/supporting/payment/dto/tx-fee-details.dto.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [DEV-1985] add txFeeInfos

- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
> [DEV-2002] fix card fee bug

- src/subdomains/generic/gs/dto/db-query.dto.ts
- src/subdomains/generic/gs/gs.controller.ts
- src/subdomains/generic/gs/gs.service.ts
- src/subdomains/generic/kyc/services/integration/document-storage.service.ts
> [DEV-1996] add db files endpoint

- src/subdomains/generic/gs/dto/db-query.dto.ts
- src/subdomains/generic/gs/gs.controller.ts
- src/subdomains/generic/gs/gs.service.ts
- src/subdomains/generic/kyc/services/integration/document-storage.service.ts
* [DEV-1996] add db files endpoint
* [DEV-1996] Renaming
- Login/logout
- Registration
[DEV-1996]: https://dfxswiss.atlassian.net/browse/DEV-1996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1996]: https://dfxswiss.atlassian.net/browse/DEV-1996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DEV-1996] add db files endpoint (#950)

- src/subdomains/generic/gs/gs.service.ts
> [FIX] fix file explorer

- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/generic/kyc/api/kyc.controller.ts
- src/subdomains/generic/kyc/services/kyc.service.ts
> BuyCrypto preparation fix

- src/subdomains/generic/gs/dto/db-query.dto.ts
- src/subdomains/generic/gs/gs.controller.ts
- src/subdomains/generic/gs/gs.service.ts
* [DEV-2012] file explorer path extension
* [DEV-2012] Refactoring
- Login/logout
- Registration
[DEV-2012]: https://dfxswiss.atlassian.net/browse/DEV-2012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2012]: https://dfxswiss.atlassian.net/browse/DEV-2012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DEV-2012] file explorer path extension (#960)

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
> [FIX] fix cryptoCrypto status

- src/subdomains/generic/user/services/spider/spider-sync.service.ts
> [NO-TASK] Fix KYC sync error

- migration/1701717309599-kycLog.js
- src/subdomains/generic/kyc/entities/step-log.entity.ts
- src/subdomains/generic/kyc/enums/kyc.enum.ts
- src/subdomains/generic/kyc/kyc.module.ts
- src/subdomains/generic/kyc/repositories/step-log.repository.ts
- src/subdomains/generic/kyc/services/kyc.service.ts
- src/subdomains/generic/kyc/services/name-check.service.ts
> [DEV-1992] Add step log

- migration/1702308322848-twoFA.js
- package-lock.json
- package.json
- src/config/config.ts
- src/subdomains/generic/kyc/entities/totp-auth-log.entity.ts
- src/subdomains/generic/kyc/enums/kyc.enum.ts
- src/subdomains/generic/kyc/repositories/totp-auth-log.repository.ts
- src/subdomains/generic/user/models/auth/auth-totp.service.ts
- src/subdomains/generic/user/models/auth/auth.controller.ts
- src/subdomains/generic/user/models/auth/dto/auth-totp.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/user.module.ts
> [DEV-1938] 2FA

- src/subdomains/core/liquidity-management/adapters/balances/blockchain.adapter.ts
> [NO-TASK] add monero to blockchain adapter

- migration/1702387425806-addKycStepsReminderSentDate.js
- src/config/config.ts
- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/subdomains/generic/kyc/entities/kyc-step.entity.ts
- src/subdomains/generic/kyc/kyc.module.ts
- src/subdomains/generic/kyc/services/kyc-notification.service.ts
- src/subdomains/generic/kyc/services/kyc.service.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/services/webhook/dto/kyc-webhook.dto.ts
- src/subdomains/generic/user/services/webhook/webhook.service.ts
- src/subdomains/supporting/notification/factories/mail.factory.ts
> [DEV-1986] add new kyc Mails

- migration/1702398154376-addVerificationDocumentId.js
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
> [DEV-2026] add verificationDocumentId

- migration/1702397850900-addDfxAutoEnableCitizenship.js
- src/shared/models/country/country.entity.ts
> [DEV-2027] add dfxAutoEnableCitizenship

- migration/1702368838915-FiatCardSpec.js
- src/shared/models/fiat/dto/fiat-dto.mapper.ts
- src/shared/models/fiat/dto/fiat.dto.ts
- src/shared/models/fiat/fiat.entity.ts
> [DEV-2021] Added fiat enable for card

- src/subdomains/core/liquidity-management/adapters/balances/bank.adapter.ts
- src/subdomains/core/liquidity-management/adapters/balances/blockchain.adapter.ts
- src/subdomains/core/liquidity-management/factories/liquidity-action-integration.factory.ts
- src/subdomains/core/liquidity-management/factories/liquidity-balance-integration.factory.ts
- src/subdomains/core/liquidity-management/interfaces/index.ts
- src/subdomains/core/liquidity-management/services/liquidity-management-balance.service.ts
- src/subdomains/core/liquidity-management/services/liquidity-management.service.ts
> [DEV-2024] liquidity balance update

- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
> [DEV-2039] sepolia testnet

- migration/1702560534941-addUserApproved.js
- src/subdomains/generic/user/models/user/dto/update-user-admin.dto.ts
- src/subdomains/generic/user/models/user/user.entity.ts
> [DEV-2029] add user approved

- migration/1702566053510-addUserDataUniqueIndex.js
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
> [DEV-2035] add unique index

- src/subdomains/core/buy-crypto/process/buy-crypto.controller.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.controller.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
> [DEV-2033] add specific update volume endpoint

- migration/1702649945339-addVerifiedName.js
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
> [DEV-2040] add verifiedName

- src/subdomains/supporting/bank/bank-account/bank-account-admin.controller.ts
- src/subdomains/supporting/bank/bank-account/bank-account.controller.ts
- src/subdomains/supporting/bank/bank.module.ts
> [DEV-2045] add bankAccount post admin endpoint

- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/subdomains/generic/user/models/auth/auth.controller.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/auth/dto/auth-mail.dto.ts
- src/subdomains/supporting/notification/factories/mail.factory.ts
> [DEV-2044] add auth mail endpoint

- migration/1702910132205-addBankDataType.js
- src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
- src/subdomains/generic/user/models/bank-data/dto/create-bank-data.dto.ts
- src/subdomains/generic/user/models/bank-data/dto/update-bank-data.dto.ts
> [DEV-2046] add bankData type

- migration/1702910132205-addBankDataType.js
- src/subdomains/generic/kyc/api/kyc.controller.ts
- src/subdomains/generic/kyc/services/kyc.service.ts
- src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
- src/subdomains/generic/user/models/bank-data/dto/create-bank-data.dto.ts
- src/subdomains/generic/user/models/bank-data/dto/update-bank-data.dto.ts
- src/subdomains/generic/user/models/user-data-relation/dto/user-data-relation.enum.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/supporting/notification/services/mail.service.ts
> [DEV-2046]&[NOTASK] add bankData type, add ControlHolder enum

- migration/1703043124684-addVerifiedCountry.js
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
> [DEV-2055] add verifiedCountry

- src/subdomains/generic/user/models/user-data-relation/user-data-relation.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
> [DEV-2051] reassign userDataRelations when merging

- migration/1703085045337-addFeeWallet.js
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-preparation.service.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.controller.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/generic/user/user.module.ts
- src/subdomains/supporting/payment/dto/create-fee.dto.ts
- src/subdomains/supporting/payment/entities/fee.entity.ts
- src/subdomains/supporting/payment/services/fee.service.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [DEV-2059] Fee fixes

- src/integration/alchemy/alchemy-network-mapper.ts
- src/integration/alchemy/alchemy.module.ts
- src/integration/alchemy/controllers/alchemy.controller.ts
- src/integration/alchemy/dto/alchemy-asset-transfers.dto.ts
- src/integration/alchemy/dto/alchemy-sync-transactions.dto.ts
- src/integration/alchemy/services/alchemy.service.ts
- src/integration/blockchain/shared/evm/evm-client.ts
- src/shared/models/asset/asset.service.ts
- src/shared/utils/util.ts
- src/subdomains/supporting/payin/strategies/register/impl/arbitrum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/ethereum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/optimism.strategy.ts
> [DEV-1907] alchemy synchronize

- src/integration/alchemy/alchemy-network-mapper.ts
- src/integration/alchemy/alchemy.module.ts
- src/integration/alchemy/controllers/alchemy.controller.ts
- src/integration/alchemy/dto/alchemy-asset-transfers.dto.ts
- src/integration/alchemy/dto/alchemy-sync-transactions.dto.ts
- src/integration/alchemy/services/alchemy.service.ts
- src/integration/blockchain/shared/evm/evm-client.ts
- src/shared/models/asset/asset.service.ts
- src/shared/utils/util.ts
- src/subdomains/generic/user/models/user-data/dto/create-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.controller.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/payin/strategies/register/impl/arbitrum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/ethereum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/optimism.strategy.ts
* [DEV-1907] synchronize via alchemy
* [DEV-1907] improvement getting transaction asset
* [DEV-1907] string ignore case utility
- Login/logout
- Registration
[DEV-1907]: https://dfxswiss.atlassian.net/browse/DEV-1907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1907]: https://dfxswiss.atlassian.net/browse/DEV-1907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-1907]: https://dfxswiss.atlassian.net/browse/DEV-1907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
> [DEV-1907] alchemy synchronize (#1002)

- src/integration/alchemy/alchemy.module.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
> [NO-TASK] Improved merge check

- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
- src/subdomains/core/sell-crypto/route/sell.service.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/bank/bank-account/bank-account.service.ts
- src/subdomains/supporting/fiat-output/fiat-output.service.ts
> [DEV-2061] add kyc & cc to supportTool

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
> [FIX] fix buyCrypto fiat calculation

- migration/1703646442636-addUserDataIndex.js
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
> [DEV-2054] change user data unique index

- migration/1703646442636-addUserDataIndex.js
- src/integration/blockchain/arbitrum/arbitrum.module.ts
- src/integration/blockchain/arbitrum/arbitrum.service.ts
- src/integration/blockchain/ethereum/ethereum.module.ts
- src/integration/blockchain/ethereum/ethereum.service.ts
- src/integration/blockchain/optimism/optimism.module.ts
- src/integration/blockchain/optimism/optimism.service.ts
- src/integration/blockchain/shared/evm/evm-client.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
> [DEV-2054] Document ID index & Alchemy fix

- src/shared/utils/util.ts
- src/subdomains/generic/user/models/user/user.entity.ts
- src/subdomains/generic/user/models/user/user.repository.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
> [DEV-2076] fix user ref activation

- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-notification.service.ts
> [DEV-2072] fix pending mails - missing url

- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/auth/dto/auth-mail.dto.ts
> [DEV-2063] mail login: create userData option

- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/subdomains/generic/user/models/auth/auth.service.ts
> [DEV-2080] add link in login mail

- src/subdomains/core/buy-crypto/process/buy-crypto.controller.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.controller.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
> [DEV-2068] extend buyCrypto volumes endpoint

- src/subdomains/core/liquidity-management/adapters/balances/blockchain.adapter.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
> [NOTASK] remove unique index check

- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/subdomains/core/buy-crypto/process/entities/buy-crypto-batch.entity.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
> [DEV-2053] add waitingForLowerFee Mail

- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/shared/utils/util.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto-batch.entity.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/liquidity-management/adapters/balances/blockchain.adapter.ts
- src/subdomains/generic/kyc/services/kyc.service.ts
> [DEV-2075] KYC step retry + balance update fix

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/generic/user/models/user-data/user-data-notification.service.ts
> [FIX] mail fixes

- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
> [DEV-2097] fix paymentInfo conflict

- migration/1703805093068-addMaxUserTxUsage.js
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat-preparation.service.ts
- src/subdomains/supporting/payment/entities/fee.entity.ts
- src/subdomains/supporting/payment/services/fee.service.ts
> [DEV-2071] add maxUserTxUsages

- src/subdomains/core/buy-crypto/process/entities/__mocks__/buy-crypto.entity.mock.ts
- src/subdomains/core/buy-crypto/process/entities/__tests__/buy-crypto-batch.entity.spec.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto-batch.entity.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
> [DEV-2073] handle lightning no route

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/config/config.ts
> [DEV-2094] replace infura

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/config/config.ts
- src/subdomains/core/history/mappers/transaction-dto.mapper.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.service.ts
> [DEV-2094]&[FIX] webhook missing relation

- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
> [NOTASK] deactivate waitingForLowerFee mail

- src/integration/exchange/entities/exchange-tx.entity.ts
- src/integration/exchange/mappers/exchange-tx.mapper.ts
- src/integration/exchange/services/exchange-tx.service.ts
- src/shared/models/asset/asset.entity.ts
- src/shared/models/asset/asset.service.ts
- src/subdomains/supporting/dex/strategies/purchase-liquidity/impl/defichain-poolpair.strategy.ts
> [DEV-2101] Added Binance exchange TXs

- src/integration/exchange/entities/exchange-tx.entity.ts
- src/integration/exchange/mappers/exchange-tx.mapper.ts
- src/integration/exchange/services/exchange-tx.service.ts
- src/shared/models/asset/asset.entity.ts
- src/shared/models/asset/asset.service.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/supporting/dex/strategies/purchase-liquidity/impl/defichain-poolpair.strategy.ts
> [DEV-2101]&[DEV-2125] add binance exchange tx & fix user mail login

- src/subdomains/generic/user/models/user-data-relation/dto/user-data-relation.enum.ts
> [DEV-2123] extend userDataRelation enum

- src/integration/blockchain/ain/services/__tests__/crypto.service.spec.ts
- src/integration/blockchain/shared/enums/blockchain.enum.ts
- src/integration/blockchain/shared/services/crypto.service.ts
- src/integration/blockchain/shared/util/blockchain.util.ts
- src/subdomains/core/liquidity-management/adapters/actions/binance.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/kraken.adapter.ts
- src/subdomains/core/referral/reward/ref-reward.service.ts
> [DEV-2086] base blockchain

- migration/1705317913911-LmRuleOneToOne.js
- src/config/config.ts
- src/integration/blockchain/ain/services/__tests__/crypto.service.spec.ts
- src/integration/blockchain/shared/enums/blockchain.enum.ts
- src/integration/blockchain/shared/services/crypto.service.ts
- src/integration/blockchain/shared/util/blockchain.util.ts
- src/shared/models/asset/asset.entity.ts
- src/shared/models/asset/asset.service.ts
- src/subdomains/core/liquidity-management/adapters/actions/binance.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/kraken.adapter.ts
- src/subdomains/core/liquidity-management/entities/liquidity-management-rule.entity.ts
- src/subdomains/core/referral/reward/ref-reward.service.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
> [DEV-2101] Binance API bug, [DEV-2127] OneToOne LM rule asset

- migration/1705329071570-addUserDataBusinessCols.js
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
> [DEV-2121] add userData business cols

- src/integration/blockchain/monero/monero-client.ts
- src/integration/exchange/services/exchange.service.ts
- src/shared/utils/util.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto-batch.entity.ts
- src/subdomains/core/history/services/history.service.ts
- src/subdomains/core/monitoring/observers/whale-health.observer.ts
- src/subdomains/generic/gs/gs.service.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/link/link.service.ts
> [DEV-2126] add util sort

- package-lock.json
- package.json
- src/config/__tests__/config.spec.ts
- src/config/config.ts
- src/integration/blockchain/ain/services/__tests__/crypto.service.spec.ts
- src/integration/blockchain/liquid/liquid-helper.ts
- src/integration/blockchain/shared/enums/blockchain.enum.ts
- src/integration/blockchain/shared/services/crypto.service.ts
- src/integration/blockchain/shared/util/blockchain.util.ts
- src/subdomains/core/liquidity-management/adapters/actions/binance.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/kraken.adapter.ts
- src/subdomains/core/referral/reward/ref-reward.service.ts
> [DEV-2087] liquid blockchain

- src/subdomains/generic/kyc/api/kyc.controller.ts
- src/subdomains/generic/kyc/dto/mapper/kyc-info.mapper.ts
- src/subdomains/generic/kyc/dto/mapper/kyc-step.mapper.ts
- src/subdomains/generic/kyc/entities/kyc-step.entity.ts
- src/subdomains/generic/kyc/enums/kyc.enum.ts
- src/subdomains/generic/kyc/services/kyc-notification.service.ts
- src/subdomains/generic/kyc/services/kyc.service.ts
- src/subdomains/generic/kyc/services/tfa.service.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
…YC level < 0
- Login/logout
- Registration
> [DEV-2089] Cancel unnecessary steps

- migration/1705932599781-changeAccountOpenerRelation.js
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
> [DEV-2139] change accountOpener relation

- src/config/config.ts
> [NOTASK] change cc fee

- migration/1706520096880-addOlkypayAllowed.js
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
> [DEV-2159] add olkypayAllowed

- migration/1706615639015-addCheckoutEnable.js
- src/shared/models/country/country.entity.ts
> [DEV-2166] add checkoutEnable

- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-notification.service.ts
> [DEV-2164] remove mail reason text for NA amlReason

- package-lock.json
- package.json
- src/integration/blockchain/blockchain.module.ts
- src/integration/blockchain/frankencoin/dto/frankencoin.dto.ts
- src/integration/blockchain/frankencoin/frankencoin-client.ts
- src/integration/blockchain/frankencoin/frankencoin.module.ts
- src/integration/blockchain/frankencoin/frankencoin.service.ts
- src/integration/blockchain/shared/evm/abi/frankencoin-position.abi.json
- src/integration/blockchain/shared/evm/abi/frankencoin.abi.json
- src/shared/services/process.service.ts
- src/subdomains/supporting/log/log.module.ts
> [DEV-2158] Frankencoin log

- src/subdomains/supporting/payin/strategies/register/__tests__/register.registry.spec.ts
- src/subdomains/supporting/payin/strategies/register/impl/arbitrum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/ethereum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/optimism.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/polygon.strategy.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
> [DEV-2168] add skip zchf testswap

- src/subdomains/supporting/payin/strategies/register/__tests__/register.registry.spec.ts
- src/subdomains/supporting/payin/strategies/register/impl/arbitrum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/ethereum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/optimism.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/polygon.strategy.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
> [DEV-2168] Skip PayIn ZCHF testswap

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [FIX] fix transactionHelper minFee bug

- src/shared/services/payment-info.service.ts
- src/subdomains/core/sell-crypto/route/sell.service.ts
> [DEV-2171] block chf sell routes

- migration/1706893942400-addFeeBlockchainFactor.js
- src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.controller.spec.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/payment/dto/create-fee.dto.ts
- src/subdomains/supporting/payment/dto/fee.dto.ts
- src/subdomains/supporting/payment/entities/fee.entity.ts
- src/subdomains/supporting/payment/services/fee.service.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [DEV-2174] add fee blockchainFactor

- migration/1706893942400-addFeeBlockchainFactor.js
- src/shared/services/payment-info.service.ts
- src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.controller.spec.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/monitoring/observers/banking-bot.observer.ts
- src/subdomains/core/monitoring/observers/node-balance.observer.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/payment/dto/create-fee.dto.ts
- src/subdomains/supporting/payment/dto/fee.dto.ts
- src/subdomains/supporting/payment/entities/fee.entity.ts
- src/subdomains/supporting/payment/services/fee.service.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
* [DEV-2171] block chf sell routes
* [DEV-2171] Refactoring
- Login/logout
- Registration
[DEV-2171]: https://dfxswiss.atlassian.net/browse/DEV-2171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-2171]: https://dfxswiss.atlassian.net/browse/DEV-2171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DEV-2171]&[DEV-2174] block chf sell routes, add blockchainFactor

- migration/1707143190169-PriceRules.js
- src/shared/models/asset/asset.entity.ts
- src/shared/models/asset/asset.service.ts
- src/shared/models/fiat/fiat.entity.ts
- src/shared/utils/util.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/supporting/dex/services/base/dex-evm.service.ts
- src/subdomains/supporting/dex/services/dex-defichain.service.ts
- src/subdomains/supporting/dex/services/dex.service.ts
- src/subdomains/supporting/dex/strategies/supplementary/impl/base/evm.strategy.ts
- src/subdomains/supporting/dex/strategies/supplementary/impl/base/supplementary.strategy.ts
- src/subdomains/supporting/dex/strategies/supplementary/impl/bitcoin.strategy.ts
- src/subdomains/supporting/dex/strategies/supplementary/impl/defichain.strategy.ts
- src/subdomains/supporting/dex/strategies/supplementary/impl/monero.strategy.ts
- src/subdomains/supporting/payin/entities/crypto-input.entity.ts
- src/subdomains/supporting/pricing/domain/entities/price-rule.entity.ts
- src/subdomains/supporting/pricing/domain/entities/price.ts
- src/subdomains/supporting/pricing/pricing.controller.ts
- src/subdomains/supporting/pricing/pricing.module.ts
- src/subdomains/supporting/pricing/repositories/price-rule.repository.ts
- src/subdomains/supporting/pricing/services/integration/coin-gecko.service.new.ts
- src/subdomains/supporting/pricing/services/integration/coin-gecko.service.ts
- src/subdomains/supporting/pricing/services/integration/pricing-dex.service.ts
- src/subdomains/supporting/pricing/services/price-provider.service.ts
- src/subdomains/supporting/pricing/services/pricing.service.new.ts
> [DEV-1882] Pricing service

- src/subdomains/generic/kyc/services/integration/ident.service.ts
- src/subdomains/generic/kyc/services/kyc.service.ts
> [DEV-2198] Send user data to Intrum

- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/get-buy-quote.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/get-crypto-quote.dto.ts
- src/subdomains/core/sell-crypto/route/dto/get-sell-quote.dto.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/payment/services/fee.service.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [DEV-2202] Extended quote endpoint

- src/subdomains/supporting/bank/bank-account/bank-account.service.ts
- src/subdomains/supporting/bank/bank-account/dto/update-bank-account.dto.ts
> [DEV-2183] return existing bankAccount

- migration/1707381820806-addFeeMaxAnnualTxVolume.js
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
- src/subdomains/supporting/payment/entities/fee.entity.ts
- src/subdomains/supporting/payment/services/fee.service.ts
> [DEV-2172] add fee maxAnnualTxVolume

- src/integration/blockchain/blockchain.module.ts
- src/integration/blockchain/frankencoin/frankencoin.module.ts
- src/integration/blockchain/frankencoin/frankencoin.service.ts
- src/subdomains/supporting/pricing/domain/entities/price-rule.entity.ts
- src/subdomains/supporting/pricing/pricing.module.ts
- src/subdomains/supporting/pricing/services/integration/pricing-frankencoin.service.ts
- src/subdomains/supporting/pricing/services/pricing.service.new.ts
> [DEV-2205] FPS price

- package-lock.json
- package.json
- src/integration/blockchain/polygon/polygon-client.ts
- src/subdomains/core/liquidity-management/adapters/actions/polygon-l2-bridge.adapter.ts
- src/subdomains/core/liquidity-management/enums/index.ts
- src/subdomains/core/liquidity-management/factories/liquidity-action-integration.factory.ts
- src/subdomains/core/liquidity-management/liquidity-management.module.ts
> [DEV-2176] Polygon bridge

- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/subdomains/generic/kyc/services/limit-request-notification.service.ts
> [DEV-2194] change limit request mail

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/config/config.ts
- src/integration/blockchain/frankencoin/dto/frankencoin.dto.ts
- src/integration/blockchain/frankencoin/frankencoin-client.ts
- src/integration/blockchain/frankencoin/frankencoin.service.ts
- src/integration/blockchain/shared/evm/abi/frankencoin-stablecoin-bridge.abi.json
> [DEV-2214] Frankencoin Swap Log

- migration/1707779311833-removeFeeTier.js
- src/config/config.ts
- src/shared/models/asset/asset.entity.ts
- src/shared/models/asset/dto/asset-dto.mapper.ts
- src/shared/models/asset/dto/asset.dto.ts
> [DEV-2162] remove old fee code

- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
> [DEV-2118] remove waitingForLowerFee mail

- migration/1707842967880-bankDataNameNullable.js
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-registration.service.ts
- src/subdomains/generic/kyc/entities/kyc-step.entity.ts
- src/subdomains/generic/kyc/services/kyc-admin.service.ts
- src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
- src/subdomains/generic/user/models/bank-data/dto/create-bank-data.dto.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.entity.ts
> [DEV-1671] auto create bankData

- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/subdomains/core/buy-crypto/process/enums/aml-reason.enum.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-notification.service.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/supporting/notification/factories/mail.factory.ts
> [DEV-2189] change kyc missing mail text

- src/shared/models/asset/dto/asset-dto.mapper.ts
- src/shared/models/asset/dto/asset.dto.ts
> [NO-TASK] Re-add fee tier

- src/config/config.ts
- src/shared/models/country/dto/country-dto.mapper.ts
- src/shared/models/country/dto/country.dto.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/buy-quote.dto.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/dto/crypto-quote.dto.ts
- src/subdomains/core/sell-crypto/route/dto/sell-quote.dto.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/dto/user.dto.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [NO-TASK] Added country allowed fields, min/max volume on quotes

- src/subdomains/supporting/pricing/utils/pricing.util.ts
> [NO-TASK] Fixed XMR pricing

- migration/1708443094666-FiatChfPrice.js
- src/shared/models/asset/asset.service.ts
- src/shared/models/fiat/dto/fiat-dto.mapper.ts
- src/shared/models/fiat/fiat.entity.ts
- src/shared/models/fiat/fiat.service.ts
- src/subdomains/supporting/pricing/pricing.module.ts
- src/subdomains/supporting/pricing/services/asset-prices.service.ts
- src/subdomains/supporting/pricing/services/fiat-prices.service.ts
> [DEV-2246] Added fiat CHF price

- src/integration/blockchain/optimism/optimism-client.ts
- src/integration/blockchain/shared/evm/evm-client.ts
- src/shared/services/process.service.ts
- src/subdomains/supporting/payout/payout.controller.ts
- src/subdomains/supporting/payout/services/payout-evm.service.ts
- src/subdomains/supporting/payout/services/payout.service.ts
- src/subdomains/supporting/payout/strategies/payout/impl/arbitrum-coin.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/arbitrum-token.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/base/bitcoin-based.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/base/evm.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/bsc-coin.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/bsc-token.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/ethereum-coin.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/ethereum-token.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/optimism-coin.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/optimism-token.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/polygon-coin.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/polygon-token.strategy.ts
> [NO-TASK] Implemented EVM TX speedup

- src/integration/blockchain/frankencoin/frankencoin.service.ts
- src/subdomains/supporting/log/log.service.ts
> [DEV-2248] Frankencoin log

- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
> [DEV-1882] Minor fix

- src/integration/blockchain/shared/evm/evm-client.ts
> [NO-TASK] Fixed EVM token payout

- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [DEV-2262] remove referencePrice in txPreparation

- src/subdomains/generic/gs/dto/db-query.dto.ts
- src/subdomains/generic/gs/gs.controller.ts
> [DEV-2196] add gs identifier

- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.controller.ts
- src/subdomains/core/sell-crypto/route/__tests__/sell.controller.spec.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/core/sell-crypto/route/sell.service.ts
- src/subdomains/generic/user/models/user/user.service.ts
> [DEV-2255] get fee for sell route

- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/shared/utils/util.ts
- src/subdomains/generic/user/models/account-merge/account-merge.service.ts
- src/subdomains/generic/user/models/user-data/user-data-notification.service.ts
- src/subdomains/generic/user/models/user-data/user-data.controller.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/supporting/notification/factories/mail.factory.ts
> [DEV-2104] add user merge mail

- src/subdomains/supporting/bank/bank/bank.service.ts
> [NO-TASK] Olki fallback

- src/shared/utils/async-cache.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
> [DEV-2263] Improved pricing performance

- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
> [DEV-2250] Calculate 24h volume in DB

- src/shared/utils/__tests__/lock.spec.ts
- src/shared/utils/util.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
> [DEV-2224] Add verified name check

- migration/1709002783827-addBuyFiatOutputAssetEntity.js
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-job.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
> [DEV-2047] set buyFiat output values + new outputAsset entities

- migration/1709074419260-addBlockchainFee.js
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/monitoring/observers/node-health.observer.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/supporting/payment/entities/blockchain-fee.entity.ts
- src/subdomains/supporting/payment/entities/blockchain-fee.ts
- src/subdomains/supporting/payment/payment.module.ts
- src/subdomains/supporting/payment/repositories/blockchain-fee.repository.ts
- src/subdomains/supporting/payment/services/fee.service.ts
- src/subdomains/supporting/payout/services/payout.service.ts
- src/subdomains/supporting/payout/strategies/payout/impl/base/bitcoin-based.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/base/evm.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/base/payout.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/lightning.strategy.ts
> [DEV-1954] Add blockchain fee table

- migration/1709074419260-addBlockchainFee.js
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/buy-crypto/routes/crypto-route/crypto-route.service.ts
- src/subdomains/core/history/dto/output/transaction.dto.ts
- src/subdomains/core/history/mappers/transaction-dto.mapper.ts
- src/subdomains/core/monitoring/observers/node-health.observer.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-notification.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
- src/subdomains/generic/user/services/webhook/dto/payment-webhook.dto.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.entity.ts
- src/subdomains/supporting/payment/entities/blockchain-fee.entity.ts
- src/subdomains/supporting/payment/payment.module.ts
- src/subdomains/supporting/payment/repositories/blockchain-fee.repository.ts
- src/subdomains/supporting/payment/services/fee.service.ts
- src/subdomains/supporting/payment/services/transaction-request.service.ts
- src/subdomains/supporting/payout/services/payout.service.ts
- src/subdomains/supporting/payout/strategies/payout/impl/base/bitcoin-based.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/base/evm.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/base/payout.strategy.ts
- src/subdomains/supporting/payout/strategies/payout/impl/lightning.strategy.ts
> [DEV-1954] & [FIXES]

- src/config/config.ts
> [NO-TASK] Allowed hash signatures

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/__tests__/buy-crypto.service.spec.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-out.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-webhook.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/generic/user/services/webhook/webhook-notification.service.ts
- src/subdomains/generic/user/services/webhook/webhook.service.ts
> Buy-crypto fixes

- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/wallet/wallet.service.ts
> [NO-TASK] Improved master key login

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-registration.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/__tests__/buy-fiat.service.spec.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-registration.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
- src/subdomains/supporting/fiat-payin/services/checkout-tx.service.ts
> [NO-TASK] Improved convert and sell creation

- src/integration/blockchain/ain/services/__tests__/crypto.service.spec.ts
- src/integration/blockchain/shared/enums/blockchain.enum.ts
- src/integration/blockchain/shared/services/crypto.service.ts
- src/integration/blockchain/shared/util/blockchain.util.ts
- src/subdomains/core/liquidity-management/adapters/actions/binance.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/kraken.adapter.ts
- src/subdomains/core/referral/reward/ref-reward.service.ts
> [DEV-2308] Added HAQQ blockchain

- src/shared/utils/__tests__/lock.spec.ts
- src/shared/utils/__tests__/util.spec.ts
- src/shared/utils/util.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
> [DEV-2313]&[FIX] Improvment verifiedName check, amlCheck referenceAsset fix

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
- src/subdomains/supporting/payment/services/transaction-request.service.ts
- src/subdomains/supporting/payout/strategies/payout/impl/monero.strategy.ts
> [NOTASK]&[DEV-2317]&[DEV-2319] improved log, payout order limit, amlCheck for revolut tx

- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
> [DEV-2321] improve changed mail text

- src/config/config.ts
- src/integration/blockchain/frankencoin/frankencoin.service.ts
- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/subdomains/supporting/bank-tx/bank-tx/__tests__/bank-tx.entity.spec.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.entity.ts
> [DEV-2321] Mail text, bank TX sender account

- src/shared/models/asset/asset.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
> [FIX] fix cryptoCrypto tx referenceAsset

- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/subdomains/generic/kyc/dto/input/ident-result.dto.ts
- src/subdomains/generic/kyc/services/kyc-notification.service.ts
- src/subdomains/generic/kyc/services/kyc.service.ts
> [DEV-2288] add ident fail reason in mail

- migration/1710147158334-checkoutTxApprovedNullable.js
- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/subdomains/generic/kyc/dto/input/ident-result.dto.ts
- src/subdomains/generic/kyc/services/kyc-notification.service.ts
- src/subdomains/generic/kyc/services/kyc.service.ts
- src/subdomains/supporting/fiat-payin/entities/checkout-tx.entity.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [NOTASK] set checkoutTx approved nullable

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
> [DEV-2301] add auto amlCheck for checkoutTx

- src/subdomains/core/buy-crypto/routes/buy/buy.service.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
> [DEV-2328] add buy route cache

- migration/1710171992947-removeCryptoInputReferenceAmounts.js
- src/subdomains/supporting/dex/strategies/check-liquidity/impl/base/check-liquidity.strategy.ts
- src/subdomains/supporting/payin/entities/__mocks__/crypto-input.entity.mock.ts
- src/subdomains/supporting/payin/entities/crypto-input.entity.ts
- src/subdomains/supporting/payin/factories/payin.factory.ts
- src/subdomains/supporting/payin/interfaces/index.ts
- src/subdomains/supporting/payin/services/payin.service.ts
- src/subdomains/supporting/payin/strategies/register/__tests__/register.registry.spec.ts
- src/subdomains/supporting/payin/strategies/register/impl/arbitrum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/jellyfish.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/register.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bitcoin.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/ethereum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/lightning.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/monero.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/optimism.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/polygon.strategy.ts
> [DEV-2268] remove btc/usdt amount in cryptoInput

- migration/1710171992947-removeCryptoInputReferenceAmounts.js
- src/integration/blockchain/shared/util/blockchain.util.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-batch.service.ts
- src/subdomains/core/trading/dto/trading.dto.ts
- src/subdomains/core/trading/entities/trading-order.entity.ts
- src/subdomains/core/trading/services/trading-order.service.ts
- src/subdomains/core/trading/services/trading.service.ts
- src/subdomains/supporting/dex/entities/liquidity-order.entity.ts
- src/subdomains/supporting/dex/strategies/check-liquidity/impl/base/check-liquidity.strategy.ts
- src/subdomains/supporting/payin/entities/__mocks__/crypto-input.entity.mock.ts
- src/subdomains/supporting/payin/entities/crypto-input.entity.ts
- src/subdomains/supporting/payin/factories/payin.factory.ts
- src/subdomains/supporting/payin/interfaces/index.ts
- src/subdomains/supporting/payin/services/payin.service.ts
- src/subdomains/supporting/payin/strategies/register/__tests__/register.registry.spec.ts
- src/subdomains/supporting/payin/strategies/register/impl/arbitrum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/evm.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/jellyfish.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/base/register.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bitcoin.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/bsc.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/ethereum.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/lightning.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/monero.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/optimism.strategy.ts
- src/subdomains/supporting/payin/strategies/register/impl/polygon.strategy.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
> [DEV-2247] Fixes

- src/shared/utils/async-cache.ts
- src/subdomains/core/trading/services/trading-order.service.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
> [DEV-2247] Fixes, price cache improvements

- src/integration/blockchain/shared/evm/evm-client.ts
> [NO-TASK] Added custom gas price to swaps

- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/generic/kyc/controllers/kyc.controller.ts
- src/subdomains/generic/kyc/services/kyc-notification.service.ts
- src/subdomains/generic/kyc/services/kyc.service.ts
> [NOTASK] Fixes

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/generic/kyc/services/kyc-notification.service.ts
> [NOTASK]&[DEV-2348] improve logging, ip check for checkoutTx

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
> [NOTASK]&[DEV-2358] amlCheck improvements

- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/enums/aml-reason.enum.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-notification.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
> [DEV-2357] add amlReason manualCheck

- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/enums/aml-reason.enum.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-notification.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
> [DEV-2352] add highRisk amlReason

- migration/1710508901053-addWalletAmlRule.js
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/generic/user/models/wallet/wallet.entity.ts
- src/subdomains/supporting/payment/dto/transaction-error.enum.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [DEV-2360] add wallet amlRule

- src/subdomains/core/referral/reward/ref-reward.service.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/fiat-payin/services/checkout-tx.service.ts
- src/subdomains/supporting/payin/services/payin.service.ts
- src/subdomains/supporting/payment/services/transaction-job.service.ts
- src/subdomains/supporting/payment/transaction-job.module.ts
> [NOTASK] transaction sync refactoring

- src/subdomains/supporting/payin/services/payin.service.ts
- src/subdomains/supporting/payment/dto/input/create-transaction.dto.ts
- src/subdomains/supporting/payment/services/transaction-job.service.ts
> [FIX] fix cryptoInput transaction method

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- package-lock.json
- package.json
- src/config/config.ts
- src/integration/blockchain/blockchain.module.ts
- src/integration/blockchain/ebel2x/ebel2x-client.ts
- src/integration/blockchain/ebel2x/ebel2x.module.ts
- src/integration/blockchain/ebel2x/ebel2x.service.ts
- src/integration/blockchain/shared/evm/evm-client.ts
- src/subdomains/supporting/pricing/domain/entities/price-rule.entity.ts
- src/subdomains/supporting/pricing/pricing.module.ts
- src/subdomains/supporting/pricing/services/integration/pricing-ebel2x.service.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
> [DEV-2315] Ebel2x pricing

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- package-lock.json
- package.json
- src/config/config.ts
- src/integration/blockchain/blockchain.module.ts
- src/integration/blockchain/ebel2x/ebel2x-client.ts
- src/integration/blockchain/ebel2x/ebel2x.module.ts
- src/integration/blockchain/ebel2x/ebel2x.service.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/enums/aml-error.enum.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/generic/user/models/wallet/wallet.entity.ts
- src/subdomains/supporting/pricing/domain/entities/price-rule.entity.ts
- src/subdomains/supporting/pricing/pricing.module.ts
- src/subdomains/supporting/pricing/services/integration/pricing-ebel2x.service.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
> [DEV-2369] maxVolume aml riskRule

- src/subdomains/core/aml/aml.service.ts
- src/subdomains/core/aml/enums/aml-error.enum.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
> [DEV-2377] amlCheck bankDataNotActive error

- migration/1711018262474-changeUserSignatureLength.js
- src/subdomains/generic/user/models/user/user.entity.ts
> [DEV-2367] Arweave signature length

- src/shared/models/active.ts
- src/shared/utils/async-cache.ts
- src/subdomains/core/aml/aml.service.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-notification.service.ts
- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
> [DEV-2385] fix email bug

- src/subdomains/supporting/payout/strategies/payout/impl/monero.strategy.ts
> [DEV-2388] XMR unlocked balance check

- migration/1711103926691-TradingAmountOut.js
- src/subdomains/core/trading/dto/trading.dto.ts
- src/subdomains/core/trading/entities/trading-order.entity.ts
- src/subdomains/core/trading/exceptions/pool-out-of-range.exception.ts
- src/subdomains/core/trading/services/trading-rule.service.ts
- src/subdomains/core/trading/services/trading.service.ts
> [NO-TASK] Improved trading

- migration/1711103926691-TradingAmountOut.js
- src/shared/models/asset/dto/asset-dto.mapper.ts
- src/shared/models/fiat/dto/fiat-dto.mapper.ts
- src/shared/utils/util.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/history/mappers/transaction-dto.mapper.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-notification.service.ts
- src/subdomains/core/trading/dto/trading.dto.ts
- src/subdomains/core/trading/entities/trading-order.entity.ts
- src/subdomains/core/trading/exceptions/pool-out-of-range.exception.ts
- src/subdomains/core/trading/services/trading-rule.service.ts
- src/subdomains/core/trading/services/trading.service.ts
- src/subdomains/supporting/payment/dto/transaction.dto.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
- src/subdomains/supporting/payout/strategies/payout/impl/monero.strategy.ts
- src/subdomains/supporting/pricing/domain/entities/price-rule.entity.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
> [DEV-2386]&[NOTASK] Improvements, fixes

- migration/1711385233909-AssetCategory.js
- src/shared/models/asset/__mocks__/asset.entity.mock.ts
- src/shared/models/asset/asset.controller.ts
- src/shared/models/asset/asset.entity.ts
- src/shared/models/asset/asset.service.ts
- src/shared/models/asset/dto/asset-query.dto.ts
- src/subdomains/core/trading/entities/trading-order.entity.ts
- src/subdomains/supporting/dex/entities/__mocks__/liquidity-order.entity.mock.ts
- src/subdomains/supporting/dex/factories/__tests__/liquidity-order.factory.spec.ts
> [DEV-2270] Reusing asset category

- src/subdomains/supporting/payment/services/transaction.service.ts
> [NOTASK] improve tx sync db call

- src/shared/utils/util.ts
- src/subdomains/core/history/controllers/transaction.controller.ts
- src/subdomains/core/history/dto/transaction-filter.dto.ts
- src/subdomains/core/history/history.module.ts
- src/subdomains/core/history/mappers/transaction-dto.mapper.ts
- src/subdomains/core/history/services/history.service.ts
- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
- src/subdomains/generic/user/services/webhook/dto/payment-webhook.dto.ts
- src/subdomains/generic/user/services/webhook/mapper/webhook-data.mapper.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/payment/dto/transaction.dto.ts
- src/subdomains/supporting/payment/services/transaction.service.ts
> [DEV-2258] Added new transaction endpoints

- src/shared/utils/util.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/core/history/controllers/transaction.controller.ts
- src/subdomains/core/history/dto/transaction-filter.dto.ts
- src/subdomains/core/history/history.module.ts
- src/subdomains/core/history/mappers/transaction-dto.mapper.ts
- src/subdomains/core/history/services/history.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
- src/subdomains/core/trading/services/trading-order.service.ts
- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
- src/subdomains/generic/user/services/webhook/dto/payment-webhook.dto.ts
- src/subdomains/generic/user/services/webhook/mapper/webhook-data.mapper.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
- src/subdomains/supporting/payin/services/payin.service.ts
- src/subdomains/supporting/payment/dto/transaction.dto.ts
- src/subdomains/supporting/payment/entities/transaction.entity.ts
- src/subdomains/supporting/payment/services/fee.service.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
- src/subdomains/supporting/payment/services/transaction.service.ts
- src/subdomains/supporting/pricing/domain/entities/price-rule.entity.ts
> Fixes / improvements

- src/subdomains/core/aml/aml-helper.service.ts
- src/subdomains/core/aml/aml.module.ts
- src/subdomains/core/aml/aml.service.ts
- src/subdomains/core/aml/enums/aml-error.enum.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-job.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-job.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
- src/subdomains/core/trading/services/trading.service.ts
- src/subdomains/generic/kyc/services/name-check.service.ts
- src/subdomains/supporting/notification/templates/generic.hbs
- src/subdomains/supporting/notification/templates/internal.hbs
> [DEV-2404] buyCrypto return mail fix [DEV-2393] aml check improvement

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/generic/user/models/user/dto/update-user-admin.dto.ts
> [NOTASK] add usedRef in update dto

- migration/1712139649720-TransactionRequestFees.js
- src/subdomains/core/aml/aml-helper.service.ts
- src/subdomains/core/aml/aml.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-job.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-job.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-preparation.service.ts
- src/subdomains/generic/user/models/auth/auth.controller.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/supporting/payment/entities/transaction-request.entity.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
- src/subdomains/supporting/payment/services/transaction-request.service.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
> [DEV-2422]&[DEV-2421] fixed namecheck, card limit error in txHelper

- src/subdomains/core/aml/aml-helper.service.ts
- src/subdomains/core/aml/aml.service.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/create-buy.dto.ts
- src/subdomains/core/buy-crypto/routes/buy/dto/get-buy-payment-info.dto.ts
- src/subdomains/core/sell-crypto/route/dto/create-sell.dto.ts
- src/subdomains/core/sell-crypto/route/dto/get-sell-payment-info.dto.ts
- src/subdomains/supporting/bank/bank-account/dto/create-bank-account.dto.ts
- src/subdomains/supporting/bank/bank-account/is-dfx-iban.validator.ts
- src/subdomains/supporting/payment/entities/special-external-account.entity.ts
- src/subdomains/supporting/payment/services/special-external-account.service.ts
> [DEV-2414] differentiate blocked ibans

- src/subdomains/core/aml/aml-helper.service.ts
- src/subdomains/core/aml/aml.service.ts
- src/subdomains/core/aml/enums/aml-error.enum.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
> [DEV-2415] aml check auto failed

- src/subdomains/core/history/controllers/transaction.controller.ts
- src/subdomains/generic/user/models/bank-data/bank-data.entity.ts
- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
- src/subdomains/supporting/bank/bank-account/bank-account.controller.ts
- src/subdomains/supporting/bank/bank-account/dto/iban.dto.ts
- src/subdomains/supporting/bank/bank-account/is-dfx-iban.validator.ts
> [DEV-2428] Added IBAN API

- migration/1712301393382-changeNotificationCols.js
- src/subdomains/supporting/notification/entities/mail/personal-mail.ts
- src/subdomains/supporting/notification/entities/mail/user-mail.ts
- src/subdomains/supporting/notification/entities/notification.entity.ts
- src/subdomains/supporting/notification/services/notification.service.ts
> [DEV-2431] reduce notification data

- migration/1712301393382-changeNotificationCols.js
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
- src/subdomains/supporting/notification/entities/mail/personal-mail.ts
- src/subdomains/supporting/notification/entities/mail/user-mail.ts
- src/subdomains/supporting/notification/entities/notification.entity.ts
- src/subdomains/supporting/notification/services/notification.service.ts
> [DEV-2432]&[DEV-2431] fix GS pending amlReason bug, reduce notification

- src/subdomains/core/aml/aml-helper.service.ts
- src/subdomains/core/aml/enums/aml-error.enum.ts
> [DEV-2425] aml auto annualLimit

- src/subdomains/generic/kyc/entities/name-check-log.entity.ts
- src/subdomains/generic/kyc/services/name-check.service.ts
> [DEV-2429] optimize name check

- migration/1712837309998-removeCryptoCryptoAllowed.js
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
> [DEV-2440] remove cryptoCryptoAllowed

- .vscode/settings.json
- migration/1712912069605-SenderAccount.js
- src/subdomains/core/aml/aml.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/buy-crypto/routes/swap/dto/swap-payment-info.dto.ts
- src/subdomains/core/history/controllers/transaction.controller.ts
- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
- src/subdomains/supporting/bank-tx/bank-tx/__tests__/bank-tx.entity.spec.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.entity.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
> [DEV-2446] Use multi-account IBANs for unassigned transactions

- .vscode/settings.json
- migration/1712837309998-removeCryptoCryptoAllowed.js
- migration/1712912069605-SenderAccount.js
- src/subdomains/core/aml/aml.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/buy-crypto/routes/swap/dto/swap-payment-info.dto.ts
- src/subdomains/core/history/controllers/transaction.controller.ts
- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
- src/subdomains/generic/user/models/user-data/dto/update-user-data.dto.ts
- src/subdomains/generic/user/models/user-data/user-data.entity.ts
- src/subdomains/supporting/bank-tx/bank-tx/__tests__/bank-tx.entity.spec.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.entity.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
> [DEV-2440] Cleanup [DEV-2446] Multi-account IBANs

- src/subdomains/core/aml/aml.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
> [DEV-2446] Cleanup

- src/subdomains/core/aml/aml.service.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
> [DEV-2446] Cleanup (#1237)

- src/subdomains/supporting/payment/dto/transaction-helper/quote-error.enum.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [DEV-2447] tx error limit exceeded

- src/subdomains/core/monitoring/monitoring.module.ts
- src/subdomains/core/monitoring/observers/aml.observer.ts
> [DEV-2349] aml observer

- src/integration/blockchain/shared/evm/evm-client.ts
- src/integration/blockchain/shared/evm/evm.util.ts
- src/subdomains/core/history/mappers/chain-report-history-dto.mapper.ts
- src/subdomains/core/trading/entities/trading-order.entity.ts
- src/subdomains/core/trading/services/trading-order.service.ts
- src/subdomains/core/trading/services/trading.service.ts
- src/subdomains/core/trading/trading.module.ts
- src/subdomains/generic/user/models/auth/auth.controller.ts
> [DEV-2448] Improved pool trading + chain report fix

- src/subdomains/core/aml/aml-helper.service.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [DEV-2473] adapt kyc rules for lightning

- src/subdomains/core/aml/aml.service.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
> [DEV-2460] auto amlCheck bankDataUserMismatch

- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.controller.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.entity.ts
- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
> [DEV-2471] reset bankTx

- src/subdomains/core/buy-crypto/process/entities/buy-crypto-fees.entity.ts
- src/subdomains/supporting/payout/strategies/payout/impl/bitcoin.strategy.ts
- src/subdomains/supporting/support-issue/support-issue.controller.ts
- src/subdomains/supporting/support-issue/support-issue.service.ts
> Small fixes

- src/subdomains/core/buy-crypto/process/entities/buy-crypto-fees.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-preparation.service.ts
> [FIX] fix buyCrypto preparation

- src/shared/services/payment-info.service.ts
- src/subdomains/core/buy-crypto/routes/swap/swap.entity.ts
> [DEV-2492] restrict swap chains

- src/subdomains/core/buy-crypto/process/dto/update-buy-crypto.dto.ts
> [DEV-2498] buyCrypto blockchainFee update

- migration/1714134150049-notificationUserData.js
- src/shared/services/process.service.ts
- src/subdomains/supporting/notification/entities/mail/personal-mail.ts
- src/subdomains/supporting/notification/entities/mail/user-mail.ts
- src/subdomains/supporting/notification/entities/notification.entity.ts
- src/subdomains/supporting/notification/services/notification-job.service.ts
- src/subdomains/supporting/notification/services/notification.service.ts
> [DEV-2494] add userData in notification

- src/subdomains/core/liquidity-management/controllers/rule.controller.ts
- src/subdomains/core/liquidity-management/dto/input/liquidity-management-update.dto.ts
- src/subdomains/core/liquidity-management/services/liquidity-management-rule.service.ts
> [DEV-2497] liq management rule update

- src/subdomains/core/history/mappers/transaction-dto.mapper.ts
- src/subdomains/supporting/payment/dto/transaction.dto.ts
> [DEV-2465] add fee dto in transactionDto

- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/subdomains/core/aml/enums/aml-reason.enum.ts
- src/subdomains/supporting/payment/dto/transaction.dto.ts
> [DEV-2502] new amlReason receiver rejected tx

- src/subdomains/core/trading/controllers/trading-rule.controller.ts
- src/subdomains/core/trading/dto/update-trading-rule.dto.ts
- src/subdomains/core/trading/services/trading-rule.service.ts
> [DEV-2496] trading rule update

- src/subdomains/core/history/mappers/transaction-dto.mapper.ts
- src/subdomains/supporting/notification/services/notification-job.service.ts
- src/subdomains/supporting/notification/services/notification.service.ts
> [FIX] small fixes

- src/config/config.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto-batch.entity.ts
- src/subdomains/generic/kyc/services/kyc-notification.service.ts
> [NOTASK] blockchain fee buffer, kyc reminder mails fix

- src/integration/blockchain/shared/evm/evm-client.ts
- src/subdomains/core/trading/services/trading.service.ts
- src/subdomains/supporting/dex/services/base/dex-evm.service.ts
- src/subdomains/supporting/dex/services/dex.service.ts
- src/subdomains/supporting/dex/strategies/supplementary/impl/base/evm.strategy.ts
- src/subdomains/supporting/dex/strategies/supplementary/impl/base/supplementary.strategy.ts
- src/subdomains/supporting/pricing/domain/entities/price-rule.entity.ts
- src/subdomains/supporting/pricing/domain/interfaces/index.ts
- src/subdomains/supporting/pricing/dto/price-request-raw.ts
- src/subdomains/supporting/pricing/pricing.controller.ts
- src/subdomains/supporting/pricing/services/integration/pricing-dex.service.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
> [DEV-2472] Get price from exact pool

- migration/1713784225473-addTransactionMailCol.js
- src/config/config.ts
- src/shared/i18n/de/mail.json
- src/shared/i18n/en/mail.json
- src/shared/i18n/es/mail.json
- src/shared/i18n/fr/mail.json
- src/shared/i18n/it/mail.json
- src/shared/i18n/pt/mail.json
- src/shared/services/process.service.ts
- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto-notification.service.ts
- src/subdomains/core/history/controllers/transaction.controller.ts
- src/subdomains/core/referral/reward/ref-reward.entity.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat-notification.service.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/supporting/notification/enums/index.ts
- src/subdomains/supporting/notification/factories/mail.factory.ts
- src/subdomains/supporting/payment/dto/input/update-transaction.dto.ts
- src/subdomains/supporting/payment/entities/transaction.entity.ts
- src/subdomains/supporting/payment/services/transaction-notification.service.ts
- src/subdomains/supporting/payment/services/transaction.service.ts
- src/subdomains/supporting/payment/transaction.module.ts
- src/subdomains/supporting/pricing/services/pricing.service.ts
- src/subdomains/supporting/support-issue/support-issue.service.ts
- Login/logout
- KYC page
- add txMailSendDate in transaction table
> [DEV-2413]&[DEV-2458]&[NOTASK] auth endpoint, adapt mails, support file fix

- src/subdomains/core/history/controllers/transaction.controller.ts
> [NO-TASK] Fixed tx endpoint bug

- README.md
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
- src/subdomains/generic/user/models/kyc/kyc.controller.ts
- src/subdomains/supporting/payment/entities/transaction.entity.ts
- src/subdomains/supporting/payment/services/transaction-notification.service.ts
> [NOTASK] Improvements

- src/shared/services/process.service.ts
- src/subdomains/supporting/payment/entities/transaction.entity.ts
- src/subdomains/supporting/payment/services/transaction-notification.service.ts
> [NOTASK] add unassigedMail process

- .vscode/settings.json
- src/integration/blockchain/ain/services/__tests__/crypto.service.spec.ts
- src/integration/blockchain/shared/services/crypto.service.ts
- src/shared/services/api-key.service.ts
- src/shared/shared.module.ts
- src/subdomains/core/buy-crypto/routes/swap/swap.controller.ts
- src/subdomains/core/history/controllers/history.controller.ts
- src/subdomains/core/referral/reward/ref-reward.service.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/user/dto/user-dto.mapper.ts
- src/subdomains/generic/user/models/user/dto/user-v2.dto.ts
- src/subdomains/generic/user/models/user/dto/user.dto.ts
- src/subdomains/generic/user/models/user/tests/user.service.spec.ts
- src/subdomains/generic/user/models/user/user.controller.ts
- src/subdomains/generic/user/models/user/user.entity.ts
- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/generic/user/user.module.ts
- src/subdomains/supporting/address-pool/deposit/deposit.service.ts
> [DEV-2449] Added v2 user endpoint

- migration/1714983022675-TradingRuleTargets.js
- migration/1714993664547-TradingRuleCheckPrice.js
- src/integration/blockchain/shared/evm/evm-client.ts
- src/subdomains/core/trading/entities/trading-order.entity.ts
- src/subdomains/core/trading/entities/trading-rule.entity.ts
- src/subdomains/core/trading/services/trading-order.service.ts
- src/subdomains/core/trading/services/trading-rule.service.ts
- src/subdomains/core/trading/services/trading.service.ts
- src/subdomains/supporting/dex/services/base/dex-evm.service.ts
> Trading improvements

- src/subdomains/core/aml/aml-helper.service.ts
> [DEV-2526] change amlCheck suspiciousMail

- src/subdomains/generic/gs/gs.module.ts
- src/subdomains/generic/gs/gs.service.ts
- src/subdomains/supporting/payment/services/transaction.service.ts
> [DEV-2530] add transaction in supportTool

- src/subdomains/generic/user/models/user-data/user-data-notification.service.ts
> [DEV-2531] send merge mail to slave

- src/subdomains/core/trading/services/trading-order.service.ts
- src/subdomains/generic/gs/gs.module.ts
- src/subdomains/generic/gs/gs.service.ts
- src/subdomains/generic/user/models/user-data/user-data-notification.service.ts
- src/subdomains/supporting/payment/services/transaction.service.ts
> [DEV-2513]&[DEV-2530]&[DEV-2531] fix liq request, transaction in supportTool, merge mail

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/config/config.ts
- src/integration/checkout/services/checkout.service.ts
- src/shared/repositories/repository.factory.ts
- src/subdomains/core/aml/enums/aml-error.enum.ts
- src/subdomains/core/monitoring/monitoring.module.ts
- src/subdomains/core/monitoring/observers/checkout.observer.ts
- src/subdomains/generic/user/models/user/dto/user-dto.mapper.ts
> [DEV-2469] Add checkout balance to monitoring

- src/subdomains/generic/user/models/user/user.service.ts
- src/subdomains/supporting/payment/services/fee.service.ts
- src/subdomains/supporting/payment/services/transaction-helper.ts
> [DEV-2533] no cached blockchainFee for payment processing

- migration/1715673475995-changeSupportIssueTable.js
- src/shared/models/asset/dto/asset-dto.mapper.ts
- src/shared/models/fiat/dto/fiat-dto.mapper.ts
- src/subdomains/supporting/support-issue/entities/support-issue.entity.ts
- src/subdomains/supporting/support-issue/services/support-issue-notification.service.ts
> [NOTASK] change supportIssue mail

- src/subdomains/supporting/payment/services/fee.service.ts
> [NO-TASK] Fixed blockchain fee if 0

- src/integration/lightning/services/lightning.service.ts
- src/subdomains/supporting/payment/entities/blockchain-fee.entity.ts
- src/subdomains/supporting/payment/services/fee.service.ts
> [NO-TASK] Fixed blockchain fees

- src/subdomains/core/aml/aml.service.ts
> [DEV-2565] auto merge only with iban

- src/shared/auth/jwt-payload.interface.ts
- src/shared/auth/jwt.strategy.ts
- src/shared/auth/role.guard.ts
- src/shared/auth/user-role.enum.ts
- src/subdomains/core/aml/aml.service.ts
- src/subdomains/core/buy-crypto/routes/buy/__tests__/buy.controller.spec.ts
- src/subdomains/core/buy-crypto/routes/buy/buy.controller.ts
- src/subdomains/core/buy-crypto/routes/swap/swap.controller.ts
- src/subdomains/core/history/controllers/transaction.controller.ts
- src/subdomains/core/history/mappers/transaction-dto.mapper.ts
- src/subdomains/core/sell-crypto/route/sell.controller.ts
- src/subdomains/generic/kyc/controllers/kyc-client.controller.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
- src/subdomains/generic/user/models/kyc/kyc.controller.ts
- src/subdomains/generic/user/models/user/user.controller.ts
- src/subdomains/supporting/bank/bank-account/bank-account.controller.ts
- src/subdomains/supporting/payment/dto/transaction.dto.ts
- src/subdomains/supporting/payment/services/transaction-request.service.ts
- src/subdomains/supporting/support-issue/support-issue.controller.ts
> [DEV-2565] Auto merge improvements [DEV-2449] Update JWT payload

- src/subdomains/core/aml/aml-helper.service.ts
> [DEV-2576] add crucial amlError timeLimit

- src/subdomains/core/buy-crypto/process/entities/buy-crypto.entity.ts
- src/subdomains/core/buy-crypto/process/services/buy-crypto.service.ts
- src/subdomains/core/sell-crypto/process/buy-fiat.entity.ts
- src/subdomains/core/sell-crypto/process/services/buy-fiat.service.ts
> [DEV-2577] allow amlCheck Fail manual update

- src/subdomains/core/aml/aml.service.ts
> [DEV-2573] cryptoCrypto aml auto nameCheck

- src/subdomains/supporting/bank-tx/bank-tx/bank-tx.service.ts
> [DEV-2575] improve bankTx buyCrypto assignment

- src/subdomains/core/buy-crypto/routes/swap/swap.service.ts
> [DEV-2578] fix swap error with txHelper

- src/subdomains/core/trading/exceptions/waiting-for-liquidity.exception.ts
- src/subdomains/core/trading/services/trading-order.service.ts
- src/subdomains/core/trading/trading.module.ts
- src/subdomains/generic/user/models/auth/auth.service.ts
> [DEV-2449] Mail login fix, trading liquidity improvement

- src/subdomains/generic/gs/dto/support-data.dto.ts
- src/subdomains/generic/gs/gs.service.ts
- src/subdomains/generic/kyc/services/kyc-admin.service.ts
> [DEV-2585] add kycSteps in supportData

- migration/1716448529870-LmActionTag.js
- src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/binance.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/kraken.adapter.ts
- src/subdomains/core/liquidity-management/entities/liquidity-management-action.entity.ts
> [DEV-2560] Implemented LM exchange transfers

- migration/1716448529870-LmActionTag.js
- src/shared/utils/util.ts
- src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/binance.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/kraken.adapter.ts
- src/subdomains/core/liquidity-management/entities/liquidity-management-action.entity.ts
- src/subdomains/generic/gs/dto/support-data.dto.ts
- src/subdomains/generic/gs/gs.service.ts
- src/subdomains/generic/kyc/services/kyc-admin.service.ts
- src/subdomains/generic/user/models/user-data/user-data.service.ts
- src/subdomains/generic/user/models/user/dto/user-dto.mapper.ts
- src/subdomains/generic/user/models/user/dto/user-v2.dto.ts
- src/subdomains/generic/user/models/user/user.controller.ts
> [DEV-2585] KYC steps in support [DEV-2560] LM exchange transfers

- infrastructure/bicep/dfx-api.bicep
- infrastructure/bicep/parameters/dev.json
- infrastructure/bicep/parameters/loc.json
- infrastructure/bicep/parameters/prd.json
- src/integration/exchange/services/__tests__/exchange.test.ts
- src/integration/exchange/services/binance.service.ts
- src/integration/exchange/services/bitpanda.service.ts
- src/integration/exchange/services/bitstamp.service.ts
- src/integration/exchange/services/exchange.service.ts
- src/integration/exchange/services/kraken.service.ts
- src/integration/exchange/services/kucoin.service.ts
- src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/binance.adapter.ts
- src/subdomains/core/liquidity-management/adapters/actions/kraken.adapter.ts
> [DEV-2560] Exchange transfer improvements

- src/subdomains/generic/user/models/bank-data/bank-data.service.ts
> [FIX] fix auto nameCheck

- migration/1716479348259-SupportIssueUser.js
- src/subdomains/supporting/support-issue/dto/create-support-issue.dto.ts
- src/subdomains/supporting/support-issue/entities/support-issue.entity.ts
- src/subdomains/supporting/support-issue/entities/support-message.entity.ts
- src/subdomains/supporting/support-issue/services/support-issue.service.ts
- src/subdomains/supporting/support-issue/support-issue.controller.ts
> [DEV-2507] Added API for general support issues

- migration/1716479348259-SupportIssueUser.js
- src/subdomains/core/buy-crypto/routes/swap/swap.controller.ts
- src/subdomains/core/liquidity-management/adapters/actions/base/ccxt-exchange.adapter.ts
- src/subdomains/core/liquidity-management/services/liquidity-management-pipeline.service.ts
- src/subdomains/core/sell-crypto/route/dto/sell-payment-info.dto.ts
- src/subdomains/supporting/address-pool/route/route.controller.ts
- src/subdomains/supporting/support-issue/dto/create-support-issue.dto.ts
- src/subdomains/supporting/support-issue/entities/support-issue.entity.ts
- src/subdomains/supporting/support-issue/entities/support-message.entity.ts
- src/subdomains/supporting/support-issue/services/support-issue.service.ts
- src/subdomains/supporting/support-issue/support-issue.controller.ts
> [DEV-2507] Added API for general support issues + fixes

- migration/1716501966588-SupportIssueUserNonNullable.js
- src/subdomains/supporting/support-issue/entities/support-issue.entity.ts
- src/subdomains/supporting/support-issue/entities/support-message.entity.ts
> [DEV-2507] User data non nullable
